### PR TITLE
should check for tagged number in JITJavascriptString::Is

### PR DESCRIPTION
**Pull request by MikeHolman**

### CODE REVIEW

**Comment by MikeHolman** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug_static
@dotnet-bot test Ubuntu ubuntu_linux_release_static

**Comment by MikeHolman** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_release_static

**Comment by rajatd** [comment]
:shipit:

**Comment by leirocks** [comment]
:shipit:

**Pull request merged**
