### PR TITLE
Remove libunwind dependency

### PR DESCRIPTION
**Pull request by obastemur**
ChakraCore no longer depends on libunwind on cross platform

### CODE REVIEW

**Comment by obastemur** [comment]
Fixes #2079 

/cc @digitalinfinity @jianchun

**Comment by obastemur** [comment]
CI errors due to #2085

**Comment by ThomsonTan** [comment]
Wondering how stack unwind is implemented without libunwind?

**Comment by obastemur** [comment]
@dotnet-bot test OSX please

**Comment by obastemur** [comment]
@dotnet-bot test OSX* please

**Comment by obastemur** [comment]
@dotnet-bot test this please

**Comment by obastemur** [comment]
Couldn't make CI to re-test this PR. Will try force pushing the same commit.

**Comment by obastemur** [comment]
> Wondering how stack unwind is implemented without libunwind?

@ThomsonTan C++ exceptions use `.eh_frame` and we were managing that already without an external dependency. PAL libunwind dependency was for SEH and that we haven't used at all.

**Comment by obastemur** [comment]
@jianchun Thanks for the review

**Pull request merged**
