### PR TITLE
Update Jenkins script locations and definitions for release/1.1 branch.

### PR DESCRIPTION
**Pull request by dilijev**
This change will unblock the Jenkins checks in #666

### CODE REVIEW

**Comment by dilijev** [comment]
FYI @Yongqu. Please sign off when the checks pass.

**Comment by Yongqu** [comment]
LGTM

**Comment by dilijev** [comment]
@ianwjhalliday FYI in case this needs to happen again for another branch in the future, I just did:

```
rm jenkins.*
git checkout master jenkins/*
git checkout master netci.groovy
```

**Comment by ianwjhalliday** [comment]
@dilijev noted

**Comment by dilijev** [comment]
Sorry, that `rm` should have been `git rm`. Updated above.

**Pull request merged**
