### PR TITLE
Fix clang compiler error caused by enum < 0

### LINKED ISSUE #4961: Compile failed with build.sh and clang 6.0
It seems that clang treat all enum variable as unsigned, so compare unsigned to 0 should always be >= 

```
[  0%] Building CXX object pal/src/CMakeFiles/Chakra.Pal.Singular.dir/shmemory/shmemory.cpp.o
/home/xm1994/ChakraCore/pal/src/shmemory/shmemory.cpp:904:16: error: comparison of unsigned enum expression < 0 is always false [-Werror,-Wtautological-unsigned-enum-zero-compare]
    if(element < 0 || element >= SIID_LAST)
       ~~~~~~~ ^ ~
/home/xm1994/ChakraCore/pal/src/shmemory/shmemory.cpp:946:16: error: comparison of unsigned enum expression < 0 is always false [-Werror,-Wtautological-unsigned-enum-zero-compare]
    if(element < 0 || element >= SIID_LAST)
       ~~~~~~~ ^ ~
2 errors generated.
```

### PR DESCRIPTION
**Pull request by summershrimp**
Fixes #4961

### CODE REVIEW

**Comment by obastemur** [comment]
@summershrimp Thanks for this!
LGTM

**Comment by jackhorton** [comment]
Updated your comment so it will close the relevant issue when this is merged. I am going to wait until _one_ of the OS X CIs pass, since this is a somewhat relevant change to them, but we have been having numerous issues with OS X CI recently, so I am expecting most of them to fail for unrelated reasons.

**Comment by summershrimp** [comment]
@jackhorton I checked the jenkins log, and it says git clone failed LOL.

**Comment by jackhorton** [comment]
Yeah... unfortunately, the .NET team manages the CI rather than us, and so theres not a ton we can do except wait for them to fix it. It looks like some of the OS X legs passed so I will merge this tonight or tomorrow.

**Comment by obastemur** [comment]
@dotnet-bot test OSX static_osx_osx_test please

**Comment by obastemur** [comment]
@dotnet-bot test OSX _no_jit_shared_osx_osx_test please

**Comment by jackhorton** [comment]
Thanks for the ping @obastemur , merging now. Thanks for the pr, @summershrimp !

**Pull request merged**
