### PR TITLE
Interpreter/IRBuilder function expression scope fix

### PR DESCRIPTION
**Pull request by pleath**
Correct the construction of scope chain structures in corner cases involving named function expressions.

### CODE REVIEW

**Comment by pleath** [comment]
@LouisLaf @rajatd

**Comment by pleath** [comment]
@LouisLaf @rajatd

**Comment by rajatd** [comment]
:shipit:

**Comment by pleath** [comment]
Making new PR; this one is trying to merge with the wrong branch.

**Pull request closed without merging**
