### PR TITLE
Add out-of-process JIT support

### PR DESCRIPTION
**Pull request by MikeHolman**
This change adds support for hosts to optionally supply chakra with an external process (initialized with JsInitializeJITServer) to act as a JIT Server. A JIT server supports running any number of Chakra runtime clients.

The basic idea is that we have separated the JIT and runtime via an RPC interface, which is called in place of Func::CodeGen (when out-of-process JIT is enabled).

The CodeGen interface takes a workitem datastructure, containing all the information necessary to JIT a function (bytecode, profile data, obj typespec info, etc.), and addresses of ScriptContext and ThreadContext specific data which live on the server.

These structures are initialized via RPC whenever the first workitem is created for a context. This lifetime of these data structures is maintained by the runtime. When a ThreadContext or ScriptContext is freed, it requests the server to free their respective datastructures as well.

Code pages are allocated and written to with VirtualAllocEx/WriteProcessMemory, and the CustomHeap for code pages is maintained by the server (it lives off of the ThreadContext datastructure).

When the JIT wants to heap allocate some data for the code to reference, we allocate it on the JIT process and copy it to a buffer when returning back from the codegen call. The JIT code references the data as an offset from the base of the buffer, who's address is on the entrypoint. Any allocated structures with pointer fields have an associated fixup function that gets called after RPC returns.

Also, note that in ChakraCore this is currently only available using testhooks.

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by MikeHolman** [comment]
I ask anyone who is interested to please help with this review. But there are a few areas which had the most changes that I believe deserve specific review:

@Yongqu Can you review the RPC/midl code?

@LouisLaf Can you review the overall JIT interface?

@rajatd @abchatra Can you review inlining changes?

@satheeshravi Can you review encoder changes?

@curtisman @digitalinfinity Can you review allocator changes?

**Comment by dilijev** [comment]
@MikeHolman Can you share some numbers about overhead of using the JIT server?

**Comment by MikeHolman** [comment]
On x64 console benchmarks, I'm seeing the following perf cost for enabling out-of-proc JIT:
```
Octane            Left score        Right score       ∆ Score   ∆ Score %  Comment
----------------  ----------------  ----------------  --------  ---------  ----------------
Box2d              41353.70 ±0.21%   38731.92 ±0.23%  -2621.78     -6.34%  Regressed
Code-load          17292.50 ±0.33%   17302.50 ±0.17%     10.00      0.06%
Crypto             32966.73 ±0.24%   31587.57 ±0.23%  -1379.16     -4.18%  Regressed
Deltablue          24415.75 ±0.91%   24754.25 ±0.40%    338.50      1.39%
Earley-boyer       40055.00 ±0.64%   40128.00 ±0.06%     73.00      0.18%
Gbemu              58581.20 ±0.92%   57433.00 ±0.40%  -1148.20     -1.96%
Mandreel           32950.79 ±0.08%   32978.56 ±0.05%     27.77      0.08%
Mandreel latency  108374.00 ±0.00%  102666.06 ±0.26%  -5707.94     -5.27%  Regressed
Navier-stokes      36655.50 ±0.10%   36193.00 ±0.56%   -462.50     -1.26%
Pdfjs              22283.13 ±0.71%   22015.00 ±0.70%   -268.13     -1.20%
Raytrace           54075.00 ±0.46%   53934.20 ±0.22%   -140.80     -0.26%
Regexp              4222.50 ±0.30%    4237.00 ±0.14%     14.50      0.34%
Richards           29124.00 ±0.23%   29703.00 ±0.22%    579.00      1.99%  Improved
Splay              23143.81 ±0.25%   22813.67 ±0.24%   -330.15     -1.43%  Regressed
Splay latency      42033.27 ±0.16%   41673.50 ±0.92%   -359.77     -0.86%
Typescript         41429.80 ±0.97%   40714.50 ±0.30%   -715.30     -1.73%
Zlib               74864.50 ±0.21%   75673.00 ±0.67%    808.50      1.08%
----------------  ----------------  ----------------  --------  ---------  ----------------
Total              33373.70 ±0.39%   32985.19 ±0.34%   -388.51     -1.16%  Likely regressed
```
```
JetStream      Left score     Right score    ∆ Score  ∆ Score %  Comment
-------------  -------------  -------------  -------  ---------  ---------
Bigfib.cpp     348.65 ±0.24%  344.48 ±0.10%    -4.17     -1.20%  Regressed
Cdjs           180.35 ±0.21%  169.90 ±0.45%   -10.45     -5.79%  Regressed
Container.cpp  333.36 ±0.12%  328.45 ±0.78%    -4.91     -1.47%
Dry.c          379.24 ±0.22%  364.20 ±0.11%   -15.04     -3.97%  Regressed
Float-mm.c     385.42 ±0.07%  389.21 ±0.04%     3.79      0.98%  Improved
Gcc-loops.cpp  494.73 ±0.14%  488.97 ±0.14%    -5.77     -1.17%  Regressed
Hash-map       134.05 ±0.83%  131.55 ±0.12%    -2.51     -1.87%
N-body.c       313.60 ±0.19%  310.00 ±0.99%    -3.60     -1.15%
Quicksort.c    259.81 ±0.10%  255.52 ±0.10%    -4.29     -1.65%  Regressed
Towers.c       266.44 ±0.34%  267.60 ±0.47%     1.16      0.44%
-------------  -------------  -------------  -------  ---------  ---------
Total          291.38 ±0.25%  286.42 ±0.33%    -4.96     -1.70%  Regressed
```
```
Kraken                            Left run time      Right run time     ∆ Run time  ∆ Run time %  Comment
--------------------------------  -----------------  -----------------  ----------  ------------  ---------
Ai-astar                           255.75 ms ±0.19%   250.00 ms ±0.23%    -5.75 ms        -2.25%  Improved
Audio-beat-detection                62.50 ms ±0.80%    63.67 ms ±0.52%     1.17 ms         1.87%
Audio-dft                          162.00 ms ±0.94%   162.50 ms ±0.73%     0.50 ms         0.31%
Audio-fft                           41.00 ms ±0.00%    41.00 ms ±0.00%     0.00 ms         0.00%
Audio-oscillator                    47.38 ms ±0.26%    49.00 ms ±0.00%     1.63 ms         3.43%  Regressed
Imaging-darkroom                   153.30 ms ±0.10%   155.00 ms ±0.20%     1.70 ms         1.11%  Regressed
Imaging-desaturate                  42.00 ms ±0.00%    45.00 ms ±0.45%     3.00 ms         7.14%  Regressed
Imaging-gaussian-blur              101.89 ms ±0.96%   103.25 ms ±0.24%     1.36 ms         1.34%
Json-parse-financial                39.00 ms ±0.00%    39.38 ms ±0.46%     0.38 ms         0.96%
Json-stringify-tinderbox            41.33 ms ±0.81%    41.67 ms ±0.80%     0.33 ms         0.81%
Stanford-crypto-aes                 81.50 ms ±0.79%    80.50 ms ±0.62%    -1.00 ms        -1.23%
Stanford-crypto-ccm                 63.73 ms ±0.22%    68.27 ms ±0.21%     4.55 ms         7.13%  Regressed
Stanford-crypto-pbkdf2             115.50 ms ±0.43%   116.50 ms ±0.43%     1.00 ms         0.87%
Stanford-crypto-sha256-iterative    38.00 ms ±0.00%    40.00 ms ±0.00%     2.00 ms         5.26%  Regressed
--------------------------------  -----------------  -----------------  ----------  ------------  ---------
Total                             1244.87 ms ±0.43%  1255.73 ms ±0.36%    10.86 ms         0.87%
```
```
SunSpider                 Left run time     Right run time    ∆ Run time  ∆ Run time %  Comment
------------------------  ----------------  ----------------  ----------  ------------  ----------------
3d-cube                     3.00 ms ±0.00%    3.00 ms ±0.00%     0.00 ms         0.00%
3d-morph                    1.00 ms ±0.00%    1.00 ms ±0.00%     0.00 ms         0.00%
3d-raytrace                 4.00 ms ±0.00%    4.00 ms ±0.00%     0.00 ms         0.00%
Access-binary-trees         2.00 ms ±0.00%    2.00 ms ±0.00%     0.00 ms         0.00%
Access-fannkuch             2.00 ms ±0.00%    2.00 ms ±0.00%     0.00 ms         0.00%
Access-nbody                2.00 ms ±0.00%    2.00 ms ±0.00%     0.00 ms         0.00%
Access-nsieve               1.00 ms ±0.00%    1.00 ms ±0.00%     0.00 ms         0.00%
Bitops-3bit-bits-in-byte    0.00 ms ±0.00%    0.00 ms ±0.00%     0.00 ms         0.00%
Bitops-bits-in-byte         1.00 ms ±0.00%    1.00 ms ±0.00%     0.00 ms         0.00%
Bitops-bitwise-and          2.00 ms ±0.00%    2.00 ms ±0.00%     0.00 ms         0.00%
Bitops-nsieve-bits          2.00 ms ±0.00%    2.00 ms ±0.00%     0.00 ms         0.00%
Controlflow-recursive       1.00 ms ±0.00%    1.00 ms ±0.00%     0.00 ms         0.00%
Crypto-aes                  4.00 ms ±0.00%    4.00 ms ±0.00%     0.00 ms         0.00%
Crypto-md5                  0.00 ms ±0.00%    0.00 ms ±0.00%     0.00 ms         0.00%
Crypto-sha1                 0.00 ms ±0.00%    0.00 ms ±0.00%     0.00 ms         0.00%
Date-format-tofte           7.00 ms ±0.00%    8.00 ms ±0.00%     1.00 ms        14.29%  Regressed
Date-format-xparb          14.00 ms ±0.00%   14.00 ms ±0.00%     0.00 ms         0.00%
Math-cordic                 1.00 ms ±0.00%    1.00 ms ±0.00%     0.00 ms         0.00%
Math-partial-sums           7.00 ms ±0.00%    7.00 ms ±0.00%     0.00 ms         0.00%
Math-spectral-norm          0.00 ms ±0.00%    0.00 ms ±0.00%     0.00 ms         0.00%
Regexp-dna                  4.44 ms ±2.89%    4.94 ms ±3.44%     0.50 ms        11.27%  Likely regressed
String-base64               1.00 ms ±0.00%    2.00 ms ±0.00%     1.00 ms       100.00%  Regressed
String-fasta                8.00 ms ±0.00%    8.00 ms ±0.00%     0.00 ms         0.00%
String-tagcloud            15.00 ms ±0.00%   15.36 ms ±0.99%     0.36 ms         2.42%
String-unpack-code         16.56 ms ±0.77%   17.00 ms ±0.00%     0.44 ms         2.64%  Regressed
String-validate-input       5.00 ms ±0.00%    6.00 ms ±0.00%     1.00 ms        20.00%  Regressed
------------------------  ----------------  ----------------  ----------  ------------  ----------------
Total                     104.00 ms ±0.25%  108.30 ms ±0.31%     4.30 ms         4.14%  Regressed
```

**Comment by dilijev** [comment]
I doubt any of the improvements are real improvements. As for the regressions, is there anything we can tune in way we do OOP JIT that could recover those losses or are these going to be unrecoverable regressions in favor of the improved security?

**Comment by dilijev** [comment]
Is there any perf impact from the previous version when these changes are in the code but OOP JIT is not turned on?

**Comment by MikeHolman** [comment]
@dilijev The improvement in Richards at least has consistently showed up for months. Haven't looked much at others. My working theory is that worse JIT throughput has us rejit something slower, where the old code was better. Some of these losses are still recoverable, however this is within the realm of acceptable loss.

Thus far, we haven't seen any perf difference with oop jit disabled vs. master. There is some possibility of working set regression due to more data being copied at workitem creation, however in local traces we haven't seen this as an issue. But this is still pending verification from perf lab runs.

**Comment by dilijev** [comment]
@MikeHolman Thanks for explaining the improvements. When you say consistently showing up for months, I assume you mean in this branch. It's interesting to see that OOP JIT could potentially improve performance in some scenarios.

I agree that the amount of the regressions doesn't seem especially concerning given the nature of this PR.

**Comment by dilijev** [comment]
@MikeHolman I see that you needed to fix NoJIT build previously.  Think it's a good idea to ask dotnet-bot for the full set those builds to show up on this PR to make sure they are all good?

https://github.com/Microsoft/ChakraCore/wiki/Jenkins-Build-Triggers#disablejit-builds

**Comment by dilijev** [comment]
@dotnet-bot test nojit tests please

**Comment by dilijev** [comment]
Review status: 0 of 296 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[bin/ch/ch.cpp, line 671 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1561#-KRkJTBN6OFc8kZpF5ww:-KRkJTBO9_8odMxoaHir:b-icfn29) ([raw file](https://github.com/microsoft/chakracore/blob/32f729b13fc4931d5abe2ace3e1b51e27a23358c/bin/ch/ch.cpp#L671)):*
> ```cpp
> 
>     if (i == argc)
>         return false;
> ```

Please put braces around body of if-statement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1561)*

**Comment by MikeHolman** [comment]
@dotnet-bot test nojit tests

**Comment by MikeHolman** [comment]
At suggestion of @EdMaurer I will be merging this in today to start getting test coverage. However, I will still very much appreciate CR feedback.

**Comment by leirocks** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_release_static please

**Comment by jdalton** [comment]
That's one big PR 😲 🥇

**Pull request merged**
