### PR TITLE
swb: write barrier annotations 2

### PR DESCRIPTION
**Pull request by jianchun**
### swb,plugin: better integration, -fix … 

To check all build files for write barrier annotations while building
the project:
```
  build.sh -n -d --wb-check
```

With above switch, a missing annotation is a build error.

To add missing annotations automatically (limited support):
```
  build.sh -n -d --wb-check --wb-args=-fix
```

Automatically build the plugin when above switches are used.

### swb: write barrier annotations 1 … 

Change CopyArray/MoveArray policy. Now they template specialize on
element type only, and specializes differently to Fields. They only
trigger write barrier if element type is WriteBarrierPtr. (We choose
to wrap element type with WriteBarrierPtr if needed so that we don't
worry about individual item operations.)

Change WriteBarrierPtr::AddressOf to return its address (instead of
ptr field's address). Add global `AddressOf()` function. Use to pass
WriteBarrierPtr by reference when calling a function that may change
the field value.

stringification fix in `WriteBarrierMacros.h`.

This commit contains some annotations that involved more manual fixes.

### swb: write barrier annotations 2

Mostly less interesting changes (or automatic changes from
`build.sh -n -d --wb-check --wb-args=-fix`).

### CODE REVIEW

**Comment by jianchun** [comment]
@dotnet-bot test Windows x86_release please

**Comment by jianchun** [comment]
@dotnet-bot test Linux tests please

**Comment by jianchun** [comment]
@dotnet-bot test Windows x86_release please

**Comment by jianchun** [comment]
@dotnet-bot test Windows x86_release please

**Comment by jianchun** [comment]
@dotnet-bot test Linux tests please

**Comment by jianchun** [comment]
@dotnet-bot test Windows x86_release please

**Comment by jianchun** [comment]
@dotnet-bot test Linux tests please

**Comment by leirocks** [comment]
:shipit:

**Comment by jianchun** [comment]
@dotnet-bot test Linux tests please

**Comment by jianchun** [comment]
Thanks @leirocks !

**Pull request merged**
