### PR TITLE
Expose platform.winglob to Intl.js to detect which i18n lib we are using in the native code.

### PR DESCRIPTION
**Pull request by jackhorton**

### CODE REVIEW

**Comment by dilijev** [comment]
@jackhorton Looks like that EOL diff we saw is because your EOL settings are off. ChakraCore should have 

```
ChakraCore>git config core.autocrlf
true
```

**Comment by jackhorton** [comment]
Its interesting, it looks like the latest gvfs update killed all of my settings, not just autocrlf.  I have fixed it now.

**Comment by dilijev** [comment]
@jackhorton To improve our inner-loop speed (mainly reduce infra overhead), I'm going to create branch `intlicu` off `release/1.7` and retarget this PR there. This shouldn't affect our workflow except that PRs should target that new branch instead. We will merge back to `release/1.7` when the work is complete.

**Comment by dilijev** [comment]
@dotnet-bot test this please

**Comment by dilijev** [comment]
@dotnet-bot test this please

**Comment by dilijev** [comment]
@dotnet-bot test this please

**Comment by dilijev** [comment]
@jackhorton You're good to merge!

**Pull request merged**
