### PR TITLE
WASM.SIMD int64x2 operations

### PR DESCRIPTION
**Pull request by Krovatkin**
This PR includes:
 * interpreter handlers + lowerer evaluators for most int64x2 ops (e.g. no conversion ops yet since we need float64x2 for that)
 * tests

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/3490)

### CODE REVIEW

**Comment by Krovatkin** [comment]
@Cellule @MikeHolman please ignore this PR for now.

**Comment by Krovatkin** [comment]
@Cellule could you please take a look at this PR when you have a chance?

**Comment by Krovatkin** [comment]
@Cellule please ignore this PR. Looks like I have a few more things to look at.

**Comment by Krovatkin** [comment]
@Cellule @MikeHolman Hey guys! Could you please take a look? It finally looks somewhat decent. I'm thinking revisiting `AllTrue` implementation after we are operation-complete

**Comment by Cellule** [comment]
Reviewed 45 of 47 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[lib/Backend/IRBuilderAsmJs.cpp, line 4526 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-KrhH4YMZnmJUxxC1Jb7:-KrhH4YMZnmJUxxC1Jb8:b-7bcvh2) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Backend/IRBuilderAsmJs.cpp#L4526)):*
> ```cpp
> IRBuilderAsmJs::BuildInt64x2_1Long1(Js::OpCodeAsmJs newOpcode, uint32 offset, BUILD_SIMD_ARGS_REG2)
> {
> ```

nit: extra newline

---

*[lib/Backend/LowerMDSharedSimd128.cpp, line 1164 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-KrhK4awqyefy4yiFQ3o:-KrhK4awqyefy4yiFQ3p:bvwmdk4) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Backend/LowerMDSharedSimd128.cpp#L1164)):*
> ```cpp
>     Assert(src1 && src1->IsRegOpnd() && (src1->GetType() == TyFloat32 || src1->GetType() == TyInt32 || src1->GetType() == TyFloat64 ||
>         src1->GetType() == TyInt16 || src1->GetType() == TyInt8 || src1->GetType() == TyUint16 ||
>         src1->GetType() == TyUint8 || src1->GetType() == TyUint32 || src1->GetType() == TyInt64));
> ```

nit: Prefer `src1->IsInt64()`

---

*[lib/Runtime/ByteCode/AsmJsByteCodeDumper.cpp, line 380 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh5EGf-JAsKeiGa9Ua:-Krh5EGgzysCGyRW1KIS:b-7howlv) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/ByteCode/AsmJsByteCodeDumper.cpp#L380)):*
> ```cpp
>     }
> 
>     // Float64x2
> ```

nit: Int64x2

---

*[lib/Runtime/ByteCode/OpLayoutsAsmJs.h, line 301 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh-iPTCQR3E3blM70E:-Krh-iPUqgzzxyJTNAVN:bjm74g) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/ByteCode/OpLayoutsAsmJs.h#L301)):*
> ```objc
> #define LAYOUT_FIELDS_DEF(x, y) LAYOUT_FIELDS_HELPER(x, y)
> 
> //LAYOUT_TYPE_WMS_REG2(Int64x2_1Long1, Int64x2, Long)
> ```

nit: I believe this is a remnant of testing. Can you clean up please ?

---

*[lib/Runtime/Language/Chakra.Runtime.Language.vcxproj, line 98 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh9YI27fCELHRwNRfg:-Krh9YI27fCELHRwNRfh:b-tzd9dr) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/Chakra.Runtime.Language.vcxproj#L98)):*
> ```XML
>     <ClCompile Include="$(MSBuildThisFileDirectory)JavascriptMathOperators.cpp" />
>     <ClCompile Include="$(MSBuildThisFileDirectory)ProfilingHelpers.cpp" />
>     <ClCompile Include="$(MSBuildThisFileDirectory)SimdInt64x2Operation.cpp" />
> ```

Please add the header file below

---

*[lib/Runtime/Language/SimdInt64x2Operation.cpp, line 43 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-KrhB0ebkNZEmpWz9Z6B:-KrhB0ebkNZEmpWz9Z6C:b-nfukbj) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/SimdInt64x2Operation.cpp#L43)):*
> ```cpp
>     }
> 
>     void SIMDInt64x2Operation::OpShiftLeftByScalar(SIMDValue* dst, SIMDValue* src, int count)
> ```

Why did you changed to passing the dst and src by pointer instead of returning the dst and receive the src by reference ?

---

*[lib/Runtime/Language/SimdUtils.h, line 234 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-KrhF8XMwiAWHo3aAa9z:-KrhF8XNNOFjiTKaGmHu:b-jmu1fi) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/SimdUtils.h#L234)):*
> ```objc
>         static inline SIMDValue SIMD128InnerReplaceLaneI2(SIMDValue simdVal, const uint32 lane, const int64 value)
>         {
>             simdVal.i64[lane] = value;
> ```

I didn't realize before, but it would be nice to have `Assert(lane < 2)` here and in the other helpers.

---

*[lib/Runtime/Language/ValueType.h, line 193 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-KrhGQo6fZ0y_SRG84jA:-KrhGQo6fZ0y_SRG84jB:b-8ctyfi) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/ValueType.h#L193)):*
> ```objc
>     bool IsLikelySimd128Uint8x16() const;
>     bool IsLikelySimd128Float64x2() const;
>     bool IsLikelySimd128Int64x2() const;
> ```

Do we really need Likely types in Wasm ?

---

*[test/wasm.simd/int64x2.wast, line 16 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh2N8mmJ98Ey4blXlr:-Krh2N8mmJ98Ey4blXls:b-e68fv8) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/test/wasm.simd/int64x2.wast#L16)):*
> ```WebAssembly
>         (i64x2.all_true (m128.load offset=0 align=4 (i32.const 0)))
>     )
>     
> ```

nit: trailing whitespaces

---

*[test/wasm.simd/int64x2.wast, line 18 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh2WnZlpfdsxOggV0M:-Krh2WnZlpfdsxOggV0N:b-jm8bl3) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/test/wasm.simd/int64x2.wast#L18)):*
> ```WebAssembly
>     
>     (func (export "func_i64x2_extractlane_0") (local $v1 m128)
>         (set_local $v1 (m128.load offset=0 align=4 (i32.const 0)))
> ```

nit: You could write this without locals using the stack
ie:
```
(m128.load offset=0 align=4 (i32.const 0))
(i64x2.extract_lane lane=0)
(i64.store offset=0 (i32.const 8))
```

---

*[test/wasm.simd/int64x2Tests.js, line 31 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh1c8LHVNyFgIwE7Bb:-Krh1c8LHVNyFgIwE7Bc:b6x58y9) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/test/wasm.simd/int64x2Tests.js#L31)):*
> ```JavaScript
> 
>     moveArgsIntoArray(inputArr, 0, array);
>     moveArgsIntoArray(resultArr, 64, array);
> ```

Any reason to move the result into the array ? It doesn't look like it is used by the test and is simply reread for asserting.
You could do `resultArr[i]|0` or `resultArr[i]>>>0` to guaranty int32 (or uint32)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3490)*

**Comment by Krovatkin** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[lib/Runtime/Language/Chakra.Runtime.Language.vcxproj, line 98 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh9YI27fCELHRwNRfg:-KrmLHgc6p8XzLyYDI9G:bj6q6ys) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/Chakra.Runtime.Language.vcxproj#L98)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

Please add the header file below
</blockquote></details>

You mean to exclude it from ARM builds? 
It doesn't contain any x86-specific intrinsics, though.

---

*[lib/Runtime/Language/SimdInt64x2Operation.cpp, line 43 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-KrhB0ebkNZEmpWz9Z6B:-KrkvOORVW7fZ8Z6JhoJ:b6k734o) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/SimdInt64x2Operation.cpp#L43)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

Why did you changed to passing the dst and src by pointer instead of returning the dst and receive the src by reference ?
</blockquote></details>

The calling convention behaviour was inconsistent: arguments would end up either in a register or on a stack. I figured an added complexity required to handle both cases wasn't worth it considering this path is a fallback.

---

*[lib/Runtime/Language/SimdUtils.h, line 234 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-KrhF8XMwiAWHo3aAa9z:-KrkxFniyMNBoFOS0lED:b-5g6w03) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/SimdUtils.h#L234)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

I didn't realize before, but it would be nice to have `Assert(lane < 2)` here and in the other helpers.
</blockquote></details>

I was thinking the same thing, but I didn't note it down, so I forgot to eventually add it. 

---

*[lib/Runtime/Language/ValueType.h, line 193 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-KrhGQo6fZ0y_SRG84jA:-Krkx_uRLzv9xuhiz2I8:b-acl82b) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/ValueType.h#L193)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

Do we really need Likely types in Wasm ?
</blockquote></details>

I'd keep it for the sake of completeness for now :smile:  I'm a bit fuzzy if we are going to get JavaScript API for handling SIMD types. 

---

*[test/wasm.simd/int64x2.wast, line 18 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh2WnZlpfdsxOggV0M:-KrmKfLBmuVz3oUuLB76:b8zurxb) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/test/wasm.simd/int64x2.wast#L18)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

nit: You could write this without locals using the stack
ie:
```
(m128.load offset=0 align=4 (i32.const 0))
(i64x2.extract_lane lane=0)
(i64.store offset=0 (i32.const 8))
```
</blockquote></details>

I'd like to keep the current version unless you feel strongly against it.
Stack versions seem to be harder to follow since mappings between operations 
and arguments aren't explicit in the stack versions. 
For example, it isn't immediately clear if `(i32.const 0)` belongs to `replace_lane` or
`store` in the snippet below.

```lisp
    (func (export "func_i64x2_replacelane_0") (local $v1 m128) (local $val i64)
        (i32.const 0)
        (m128.load offset=0 align=4 (i32.const 0))
        (i64.load offset=16 align=4 (i32.const 0))
        (i64x2.replace_lane lane=1)
        (m128.store offset=0)
    )
```

---

*[test/wasm.simd/int64x2Tests.js, line 31 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh1c8LHVNyFgIwE7Bb:-KrmKqsevLRkajgI_vbs:bp053kw) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/test/wasm.simd/int64x2Tests.js#L31)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

Any reason to move the result into the array ? It doesn't look like it is used by the test and is simply reread for asserting.
You could do `resultArr[i]|0` or `resultArr[i]>>>0` to guaranty int32 (or uint32)
</blockquote></details>

No reason. In fact, I started doing just that in my recent tests. I'll change the tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3490)*

**Comment by Cellule** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[lib/Runtime/Language/Chakra.Runtime.Language.vcxproj, line 98 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh9YI27fCELHRwNRfg:-Krqe0CPShbHTfzHoWzI:ba6716x) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/Chakra.Runtime.Language.vcxproj#L98)):*
<details><summary><i>Previously, Krovatkin (Nick Korovaiko) wrote…</i></summary><blockquote>

You mean to exclude it from ARM builds? 
It doesn't contain any x86-specific intrinsics, though.
</blockquote></details>

I mean to add `<ClInclude Include="SimdInt64x2Operation.h" />` in the header ItemGroup below in this file.
This way, the file will be part of the project and show up in the Solution Explorer in Visual Studio

---

*[lib/Runtime/Language/SimdInt64x2Operation.cpp, line 43 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-KrhB0ebkNZEmpWz9Z6B:-KrqeRrBu_OholZho1o1:b-iyfbnc) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/SimdInt64x2Operation.cpp#L43)):*
> required to handle both cases wasn't worth it considering this path is a fallback

I see, so I guess if/when we'll implement these call directly in the jit and not call helper we could/should use the previous calling convention. Is that right ?
If so, can you put a todo where the helpers are defined to remember to do this.

---

*[test/wasm.simd/int64x2.wast, line 18 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh2WnZlpfdsxOggV0M:-KrqewQlm8wOoFj-sS8z:bltrer0) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/test/wasm.simd/int64x2.wast#L18)):*
<details><summary><i>Previously, Krovatkin (Nick Korovaiko) wrote…</i></summary><blockquote>

I'd like to keep the current version unless you feel strongly against it.
Stack versions seem to be harder to follow since mappings between operations 
and arguments aren't explicit in the stack versions. 
For example, it isn't immediately clear if `(i32.const 0)` belongs to `replace_lane` or
`store` in the snippet below.

```lisp
    (func (export "func_i64x2_replacelane_0") (local $v1 m128) (local $val i64)
        (i32.const 0)
        (m128.load offset=0 align=4 (i32.const 0))
        (i64.load offset=16 align=4 (i32.const 0))
        (i64x2.replace_lane lane=1)
        (m128.store offset=0)
    )
```
</blockquote></details>

I see your point. I don't feel particularly strongly about it so we can keep like that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3490)*

**Comment by Cellule** [comment]
:lgtm:
I don't remember are able to run the tests in the private repository ?
Also, I would recommend doing an integration of master into wasm.simd after this PR

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-:-KrrJ-RTu9lnZxZpnYH-:bgvnt6u)*

**Comment by Krovatkin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[lib/Runtime/Language/Chakra.Runtime.Language.vcxproj, line 98 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh9YI27fCELHRwNRfg:-Krr1TIGh0J2xrPtEoLd:b-l6dldn) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/Chakra.Runtime.Language.vcxproj#L98)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

I mean to add `<ClInclude Include="SimdInt64x2Operation.h" />` in the header ItemGroup below in this file.
This way, the file will be part of the project and show up in the Solution Explorer in Visual Studio
</blockquote></details>

got you! 

---

*[lib/Runtime/Language/SimdInt64x2Operation.cpp, line 43 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-KrhB0ebkNZEmpWz9Z6B:-Krqz4zgvL9q_gR-WaiN:b-dfckwv) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/lib/Runtime/Language/SimdInt64x2Operation.cpp#L43)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

> required to handle both cases wasn't worth it considering this path is a fallback

I see, so I guess if/when we'll implement these call directly in the jit and not call helper we could/should use the previous calling convention. Is that right ?
If so, can you put a todo where the helpers are defined to remember to do this.
</blockquote></details>

Will do. We already map `i64x2.shr_u` to `pshrlq` and `i64x2.shl` to `pshlq`.  There's no instruction for `i64x2.shr_s`, unfortunately, so we generate a helper call.  I'm planning to revisit `i64x2.shr_s` and `i64x2.alltrue` after we are instruction-complete.

---

*[test/wasm.simd/int64x2.wast, line 16 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh2N8mmJ98Ey4blXlr:-KrrHncEryvftt3GcOGb:b-2ceokl) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/test/wasm.simd/int64x2.wast#L16)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

nit: trailing whitespaces
</blockquote></details>

Hm... interesting. I don't see any trailing whitespaces in this file :cry: 

---

*[test/wasm.simd/int64x2.wast, line 18 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3490#-Krh2WnZlpfdsxOggV0M:-Krr0vldjf07RNKT5XEJ:bv39mkr) ([raw file](https://github.com/microsoft/chakracore/blob/b8c4da2bdddf2453ce19bd80b858220ddd3e8b98/test/wasm.simd/int64x2.wast#L18)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

I see your point. I don't feel particularly strongly about it so we can keep like that.
</blockquote></details>

great! I was debating about changing *some* functions to a stack form, but I realized that this kind of inconsistency would look even worse

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3490)*

**Comment by Krovatkin** [comment]
@Cellule 

> Also, I would recommend doing an integration of master into wasm.simd after this PR

Lettuce do that next!

> I don't remember are able to run the tests in the private repository ?

Could you please rephrase this question a bit; I can't seem to parse it 😕 ?

**Comment by Cellule** [comment]
> I don't remember are able to run the tests in the private repository ?

Wow that was bad sorry.
The question is: Are you able to run unit tests from the private chakra repository or do you need me to do it for you ?

**Comment by Krovatkin** [comment]
> The question is: Are you able to run unit tests from the private chakra repository or do you need me to do it for you ?

Ah! Let me talk to @arunetm , I think we should be able to run the tests in the private repo now.

**Comment by arunetm** [comment]
Yes. We will run the private Tests on the branch.

**Comment by Krovatkin** [comment]
Merged... Closing this PR

**Pull request closed without merging**
