### PR TITLE
Fix for VS2013

### PR DESCRIPTION
**Pull request by Cellule**
Add missing include necessary in VS2013.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1481)

### CODE REVIEW

**Comment by Cellule** [comment]
@dotnet-bot please test Windows daily_dev12_x64_debug_prtest

**Comment by Cellule** [comment]
@dotnet-bot please test Windows daily_dev12_x64_debug

**Comment by Cellule** [comment]
@dilijev Can I get a jenkins test run for dev12 on this pr ?

**Comment by Cellule** [comment]
@mrkmarron @dilijev Could you review this please ?

**Comment by Cellule** [comment]
I did a manual run on jenkins on x64_debug for dev12
http://dotnet-ci.cloudapp.net/me/my-views/view/All/job/Microsoft_ChakraCore/job/master/job/daily_dev12_x64_debug/

**Comment by Cellule** [comment]
@dotnet-bot test dev12 tests please

**Comment by mrkmarron** [comment]
I noticed that <sys/stat.h> is already included for Linux and now we are also including for Win32 (and presumably will for OSX as well once it is there). So maybe it makes sense to hoist the include out to the top in a single place.

**Comment by mrkmarron** [comment]
Also it looks like this will resolve issue [#1398](https://github.com/Microsoft/ChakraCore/issues/1398) which seems to be based on missing the definition of S_IREAD/S_IWRITE (which stat,h defines). Is this correct?

**Comment by dilijev** [comment]
Echo concerns re: divergence/convergence with xplat

Otherwise LGTM

**Comment by Cellule** [comment]
@dotnet-bot test dev12 tests please

**Comment by Cellule** [comment]
I hoisted the include for all Architecture.
I will merge once all checks pass.
This does fix the build issue, it should auto-close once merged.

**Pull request merged**
