### PR TITLE
Fix #5314: removed last param

### LINKED ISSUE #5314: RtlVirtualUnwind last parameter is optional and not needed here.
https://github.com/Microsoft/ChakraCore/blob/99f04016d044360b637a654a274c167d026cb020/lib/Common/Core/FaultInjection.cpp#L153

### PR DESCRIPTION
**Pull request by bingr001**
I removed the last param, but I'm not sure if I did it right

Fixes #5314

### CODE REVIEW

**Comment by MSLaguana** [comment]
Why do you want to remove this parameter?

**Comment by bingr001** [comment]
I believe that's what hte issue was requiring.
Was I missing th epoint?

**Comment by MSLaguana** [comment]
Which issue are you referring to? Could you provide a link?

**Comment by bingr001** [comment]
Sorry about that. Here you go.
https://github.com/Microsoft/ChakraCore/issues/5314

**Comment by MSLaguana** [comment]
I see. I believe they were pointing out that we can provide a null pointer there rather than having to create and zero out a `KNONVOLATILE_CONTEXT_POINTERS` structure. There still needs to be a positional argument in that spot. You've also accidentally removed the closing paren for the function, which is causing parse errors.

If you wanted to remove the `NvContext` local and fix up your change so it passes CI, then I think we can take it.

**Comment by bhavayAnand9** [comment]
Hi! @bingr001 sorry about creating a PR for the same issue that you was working on. I just want to know if you're still working on this issue or can I take this one?

**Comment by bingr001** [comment]
Yeah sure

**Comment by dilijev** [comment]
Closing this PR in favor of https://github.com/Microsoft/ChakraCore/pull/5750 
Thanks @bingr001 for your contribution!

**Pull request closed without merging**
