### PR TITLE
Add Sharp S and Kelvin sign to word-chars. Fixes #1181.

### LINKED ISSUE #1181: [RegExp] Match updated spec for `/\w/iu` and `/\W/iu`
Now that https://github.com/tc39/ecma262/pull/525 has landed, `\u017F` (LATIN SMALL LETTER LONG S) and `\u212A` (KELVIN SIGN) are word characters for `/iu` patterns.

Expected vs. actual behavior:

``` js
/\w/iu.test('\u017F') // true
/\w/iu.test('\u212A') // true
/\W/iu.test('\u017F') // false, actual: true
/\W/iu.test('\u212A') // false, actual: true
/\W/iu.test('s')      // false
/\W/iu.test('S')      // false
/\W/iu.test('K')      // false
/\W/iu.test('k')      // false
```
#### See also
- V8: https://bugs.chromium.org/p/v8/issues/detail?id=5145
- JavaScriptCore: https://bugs.webkit.org/show_bug.cgi?id=159055
- SpiderMonkey: https://bugzilla.mozilla.org/show_bug.cgi?id=1281739
- regexpu-core: https://github.com/mathiasbynens/regexpu-core/issues/8

### PR DESCRIPTION
**Pull request by dilijev**
Fixes #1181 

Reviewed by @tcare and @bterlson

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug_static please

**Comment by dilijev** [comment]
Failures are baselines that need updating. Also, I'm going to look into the non-unicode case and make sure that works.

**Comment by dilijev** [comment]
@bterlson FYI - I updated to the correct behavior per-spec. (Thanks for clarifying, @matthiasbynens.) Compared with Firefox nightly to confirm that this new "correct" behavior matches theirs, and it does. 🎉

**Comment by tcare** [comment]
Looks good.

**Comment by dilijev** [comment]
Thanks for the reviews @tcare and @bterlson!

**Pull request merged**
