### PR TITLE
WASM.SIMD Merge master into wasm.simd 2017/09/15

### PR DESCRIPTION
**Pull request by Krovatkin**
This PR merges master(as of 2017/09/15) into wasm.simd

### CODE REVIEW

**Comment by Krovatkin** [comment]
@Cellule would you be able to help me merge this PR?

**Comment by Krovatkin** [comment]
tagging @arunetm

**Comment by Krovatkin** [comment]
@Cellule ping, sry to pester you :-(

**Comment by Cellule** [comment]
I'll look into it today

**Comment by Cellule** [comment]
I have reviewed the conflict resolution and it looks good.
I am currently running test in ChakraFull, if everything comes back green, I'll go ahead and merge this.

**Comment by Cellule** [comment]
I had to do an additional merge because there was a build break in ChakraFull for the commit you chose.
Make sure to update your local wasm.simd .

**Comment by Krovatkin** [comment]
yay! thank you!

**Pull request merged**
