### PR TITLE
Fix #5349: Rename Atomics.wake to Atomics.notify, per ES spec change.

### LINKED ISSUE #5349: Rename Atomics.wake to Atomics.notify per ES standard change
At the May 2018 TC39 meeting, consensus was reached to rename Atomics.wake to Atomics.notify (while the API is temporarily disabled). 

The spec change can be found here: https://github.com/tc39/ecma262/pull/1220

### PR DESCRIPTION
**Pull request by dilijev**
Fix #5349

### CODE REVIEW

**Comment by MSLaguana** [comment]
Do we need to go through a process to announce / enable toggles for this breaking change? Are there potentially user scripts that try to use `Atomics.wake`?

**Comment by dilijev** [comment]
I'm not sure of the process but I'm interested to figure it out. I assume that because TC39 has reached consensus on this that it is not used / was still experimental. #5349 says "(while the API is temporarily disabled)" -- although I'm not sure what that means exactly. We probably need a crawler run for this change before including it in a release. Maybe 1.10 is too aggressive for a breaking change.

**Comment by akroshg** [comment]
Telemetry?
This feature disabled for us already so I don't think there should be lot of impact. Are there any transpiler support already?

**Comment by dilijev** [comment]
From using eshost, it looks like sm, v8, xs have Atomics.wait defined, and ch and jsc have Atomics disabled.

**Comment by MSLaguana** [comment]
For what it's worth, node has added a test which essentially assumes that both `Atomics.wake` and `Atomics.nofity` exist and are equivalent.

**Comment by MSLaguana** [comment]
Although, I think that is node adding a stopgap-measure until v8 makes the change. The same commit that added that test also made host changes to create `Atomics.notify` as a duplicate of `Atomics.wake`.

**Comment by dilijev** [comment]
Per the fact that it's disabled in ChakraCore, does node-ChakraCore pass that test?

**Comment by MSLaguana** [comment]
It did not (which is how I came to see it) but with a small change to bring node-chakracore more inline with node-v8, it now does (looks like atomics are enabled in node-chakracore). My change to fix things can be seen at https://github.com/nodejs/node-chakracore/commit/6eea50d39ed5a6bf98e960a5d54d4638cedabaad if you are curious

**Comment by dilijev** [comment]
@MSLaguana Any reason to block this PR on node-ChakraCore?

**Comment by dilijev** [comment]
@akroshg do you think this is okay to merge?

**Comment by akroshg** [comment]
go ahead.

**Comment by dilijev** [comment]
If it's actually disabled at the moment there should be no change, but we could maybe do crawler runs with it enabled and before|after the change

**Pull request merged**
