### PR TITLE
Enable es3 extension methods for WWA

### PR DESCRIPTION
**Pull request by abchatra**
See github issue #618

### CODE REVIEW

**Comment by tcare** [comment]
Looks good.

**Comment by akroshg** [comment]
So we are not getting rid of `SupportES3Entensions `altogether ?

**Comment by Yongqu** [comment]
annex b only have 2 String.prototype methods: substr and anchor.
What's the backward compat impact for existing wwa apps?

**Comment by abchatra** [comment]
@akroshg SupportES3Entensions still guards getVarDate which is not a standard. 
@Yongqu This is a known bug with existing WWA App which fails due to non-availability of  these string built-in. This issue\pull request is to address the same. I agree, this has a potential to break existing apps, though chances are remote. Is there a way to test the compat?

**Comment by bterlson** [comment]
It is not worth testing compat for these. These exist on the web everywhere, so we're talking about some code breaking that exists in WWA only that is polyfilling these methods but in a way that isn't web compatible. I think this is fine to go in as-is.

**Pull request merged**
