### PR TITLE
Merged PR 129185: [MERGE #5297 @VSadov] Adding telemetry for pinned objects and closed script contexts

### PR DESCRIPTION
**Pull request by mike-kaufman**
[MERGE #5297 @VSadov] Adding telemetry for pinned objects and closed script contexts

Cherry-picked from commit `ea9a1d6d`.

### CODE REVIEW

**Comment by mike-kaufman** [comment]
@VSadov - this change went into master just after cut-off to automatically pump into release/1.10.  There's some benefit in having this data in release/1.10 and it will simplify merges & conflict resolutions going forward.  

Any reason we don't want to take this in release/1.10 now?

**Comment by dilijev** [comment]
Is this the same as https://github.com/Microsoft/ChakraCore/pull/5346 ?

**Comment by mike-kaufman** [comment]
It's close, looks like #5346 has some more changes than what's in here.  @vsadov?

**Comment by VSadov** [comment]
Let's make this PR go through. I have couple additional changes. 
They are easier to do once these are in. (I tried to do all at once and it seems unnecessary hard)

**Pull request merged**
