### PR TITLE
xplat: disable typedarray/samethread.js until #2135 is fixed

### PR DESCRIPTION
**Pull request by obastemur**

### CODE REVIEW

**Comment by obastemur** [comment]
This `slow test` constantly fails and makes it harder (for xplat CI) to detect other potential issues. We have a bug report at #2135 . Once that is fixed, we can enable this test back.

**Comment by obastemur** [comment]
/cc @jianchun 

We better merge master to swb after this. Once it is under swb branch, I will enable swb testing on xplat-ci

**Comment by Cellule** [comment]
Fixed by #2228

**Comment by obastemur** [comment]
@Cellule Thanks for taking care of this

**Pull request closed without merging**
