### PR TITLE
Wasm SIMD opcodes

### PR DESCRIPTION
**Pull request by ppenzin**
Bring wasm SIMD opcodes up to speed with current state of the proposal (for supported instructions)

### CODE REVIEW

**Comment by ppenzin** [comment]
Constant literals can be further improved for i8x16 and i16x8 tests using new format, though that won't change their values.

**Comment by ppenzin** [comment]
Kicking tires - Windows 7 build failed with "Insufficient disk space"

**Comment by ppenzin** [comment]
Sigh, Windows 7 is failing again, restart attempt number 3.

**Comment by ppenzin** [comment]
This is how support would look like from the point of view of Wasm SIMD proposal: ppenzin/simd@e29998a

@MikeHolman @Fly-Style feel free to take a look.

**Comment by ppenzin** [comment]
@pleath sorry to bug you about this again - we were able to merge one PR before this - but Win7 job seems to be stuck again (restarted three times).

**Comment by ppenzin** [comment]
Win7 job again errored out with not enough space on disk.

**Comment by pleath** [comment]
@boingoing, do you remember how we dealt with the Win7 CI problem before?

**Comment by boingoing** [comment]
Yes, I know how to poke at the Win7 CI machines which usually gets them past this. Sorry for the inconvenience, all. I'll make an attempt at fixing this in an hour or so.

**Comment by boingoing** [comment]
I kicked those CI machines and restarted the tests. Fingers crossed, should be fine.

**Comment by ppenzin** [comment]
Thank you @boingoing! We will keep in mind that you can restart the CI jobs. Is it possible to make Win7 check optional, so that we don't have to bug you every time it has issues?

**Pull request merged**
