### PR TITLE
ChakraCore 2018-04 security updates

### PR DESCRIPTION
**Pull request by rajatd**

### CODE REVIEW

**Comment by rajatd** [comment]
FYI @pleath @MikeHolman @meg-gupta @thomasmo @akroshg 

/cc @MSLaguana

**Comment by MSLaguana** [comment]
Can you please also include version bumps to https://github.com/Microsoft/ChakraCore/blob/master/Build/NuGet/.pack-version and https://github.com/Microsoft/ChakraCore/blob/master/lib/Common/ChakraCoreVersion.h

**Comment by MSLaguana** [comment]
@dotnet-bot test OSX static_osx_osx_test please

**Comment by rajatd** [comment]
@dotnet-bot test static_osx_osx_debug

**Comment by rajatd** [comment]
@dotnet-bot test OSX static_osx_osx_debug please
@dotnet-bot test OSX static_osx_osx_release please
@dotnet-bot test OSX static_osx_osx_test please

**Comment by MSLaguana** [comment]
@dotnet-bot test OSX static_osx_osx_release please

**Pull request merged**
