### PR TITLE
Adding checks to WASM division and remainder instructions

### LINKED ISSUE #1857: WASM - i32.trunc_u/f32
Implement operator i32.trunc_u/f32

### LINKED ISSUE #1858: WASM - i32.trunc_u/f64
Implement operator i32.trunc_u/f64

### LINKED ISSUE #1860: WASM - i64.trunc_s/f32
Implement operator i64.trunc_s/f32
Should trap when the floating point value is NaN or outside the range which rounds to an integer in range

### LINKED ISSUE #1861: WASM - i64.trunc_s/f64
Implement operator i64.trunc_s/f64
Should trap when the floating point value is NaN or outside the range which rounds to an integer in range

### LINKED ISSUE #1862: WASM - i64.trunc_u/f32
Implement operator i64.trunc_u/f32
Should trap when the floating point value is NaN or outside the range which rounds to an integer in range

### LINKED ISSUE #1863: WASM - i64.trunc_u/f64
Implement operator i64.trunc_u/f64
Should trap when the floating point value is NaN or outside the range which rounds to an integer in range

### LINKED ISSUE #1878: WASM - Int32 Math and conversion traps
Verify and implement math operators that need to trap
https://github.com/WebAssembly/design/blob/binary_0xc/AstSemantics.md#32-bit-integer-operators

### LINKED ISSUE #1900: WASM - Int64 Math Traps
For i64.div/rem add checks to handle DivideByZero, IntegerOverflow

### PR DESCRIPTION
**Pull request by Krovatkin**
Closes #1878
Closes #1857 
Closes #1858 
Closes #1860 
Closes #1861 
Closes #1862 
Closes #1863 
Closes #1900

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1848)

### CODE REVIEW

**Comment by Krovatkin** [comment]
fyi: @arunetm @commonlisp

**Comment by Cellule** [comment]
Related #1878

**Comment by Cellule** [comment]
From the conversation we had with @louislaf 

We should be emitting the following bytecode for a division
```
TrapIfZero I2
TrapIfDivOverFlow I1 I2
I3 = DIV I1 I3
```
instead of creating a specialized opcode for div and rem

---

Reviewed 6 of 18 files at r1.
Review status: 6 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[lib/Parser/rterrors.h, line 367 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVRyo0S1C2NNOanE3Bx:-KVRyo0T72rPex2gpi5L:b-55mbiz) ([raw file](https://github.com/microsoft/chakracore/blob/02f112c5c45fc11a0a38d42c939539b2960924eb/lib/Parser/rterrors.h#L367)):*
> ```objc
> RT_ERROR_MSG(JSERR_CantDeleteNonConfigProp, 5666, "Cannot delete non-configurable property '%s'", "Cannot delete non-configurable property", kjstTypeError, 0)
> RT_ERROR_MSG(WASMERR_Unreachable, 5667, "", "Unreachable Code", kjstError, 0)
> RT_ERROR_MSG(WASMERR_DivideByZero, 5668,    "",  "Division by zero", kjstError, 0)
> ```

Heads up, #1821 is also adding error message here

---

*[test/wasm/exceptions.js, line 22 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVRzWsx86xO8xsqyONc:-KVRzWsx86xO8xsqyONd:bojy2ee) ([raw file](https://github.com/microsoft/chakracore/blob/02f112c5c45fc11a0a38d42c939539b2960924eb/test/wasm/exceptions.js#L22)):*
> ```JavaScript
> print(trap(a.i32_rem_s, 5, 0));
> 
> print(trap(a.i32_div_s, 5, -2));
> ```

Since we don't expect those to trap, I would call them directly, that way it will be more obvious if we fail

---

*[test/wasm/exceptions.wast, line 1 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVRzAkdqqbr3KxrzqJw:-KVRzAkdqqbr3KxrzqJx:b-306a4g) ([raw file](https://github.com/microsoft/chakracore/blob/02f112c5c45fc11a0a38d42c939539b2960924eb/test/wasm/exceptions.wast#L1)):*
> ```
> ;;-------------------------------------------------------------------------------------------------------
> ```

I suggest we add these in math.wast instead and do the checks in math.js

---

*[test/wasm/exceptions.wast, line 11 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVRz5riJ0r9dR6h6uIv:-KVRz5riJ0r9dR6h6uIw:b-pntkyh) ([raw file](https://github.com/microsoft/chakracore/blob/02f112c5c45fc11a0a38d42c939539b2960924eb/test/wasm/exceptions.wast#L11)):*
> ```
>   (func (export "i32_div_u") (param $x i32) (param $y i32) (result i32)
>     (i32.div_u (get_local $x) (get_local $y)))
>     
> ```

nit: trailing whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-:-KVS-S5MNbsq5E1Jkia1:b-mtpsoc)*

**Comment by Krovatkin** [comment]
@Cellule @MikeHolman I think I might have jumped the gun a little bit with this. I realized that I'd like to add a small bit of logic in globopt for removing checks, so we could get a clearer picture and see if all the parts of this puzzle fit together and go where they are supposed to. I'll ping you guys in a bit!

**Comment by Krovatkin** [comment]
@Cellule @MikeHolman Consolidated trap and trunc-related stuff into this PR. I tried to keep the number of commits to a minimum. @MikeHolman already reviewed **i32 trunc**  in PR #1812. I included his suggestion to switch a packed subtraction instruction to a scalar one. Also, I switched to using `FindSingleDefInstr` to find a trap instruction. Other than that it should be identical to what Mike has reviewed. 

* **i32 div/rem** 
	* checked div/rem  …	        2d76975
	* optimizer part		      	ebd4462
	* review p1  			        cd2eb79
* **i32 trunc** 
	* truncation instructions  …	6a627d6
* **i64 trunc** 
	i64 truncation instructions	 e77e8c4

FYI  @arunetm @commonlisp

**Comment by Krovatkin** [comment]
@Cellule I missed your comment regarding the traps in `trunc.js`

> Since we don't expect those to trap, I would call them directly, that way it will be more obvious if we fail

I'll fix the test case first thing tmr morning!

**Comment by Cellule** [comment]
Reviewed 1 of 18 files at r1, 10 of 19 files at r2, 3 of 7 files at r3, 27 of 27 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[lib/Backend/IRBuilderAsmJs.cpp, line 1940 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVg9UVNllKLzxtoea27:-KVg9UVO_GfLolPFPszH:b-klmhe0) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Backend/IRBuilderAsmJs.cpp#L1940)):*
> StackSym::New(m_func), 

Remove that argument so the StackSym is created using the same type as the RegOpnd

---

*[lib/Backend/IRBuilderAsmJs.cpp, line 1980 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVg9ZrkSXXbW-0lUg72:-KVg9ZrkSXXbW-0lUg73:b-klmhe0) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Backend/IRBuilderAsmJs.cpp#L1980)):*
> StackSym::New(m_func), 

Remove that argument so the StackSym is created using the same type as the RegOpnd

---

*[lib/Backend/IRBuilderAsmJs.cpp, line 2410 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVg9_wYYnNxpcmkBvaG:-KVg9_w_VC0oms9-dBh9:b-klmhe0) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Backend/IRBuilderAsmJs.cpp#L2410)):*
> StackSym::New(m_func), 

Remove that argument so the StackSym is created using the same type as the RegOpnd

---

*[lib/Backend/IRBuilderAsmJs.cpp, line 2418 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVg9a__ZB-MCly0x1em:-KVg9a__ZB-MCly0x1en:b-klmhe0) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Backend/IRBuilderAsmJs.cpp#L2418)):*
> StackSym::New(m_func), 

Remove that argument so the StackSym is created using the same type as the RegOpnd

---

*[lib/Backend/IRBuilderAsmJs.cpp, line 3224 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVg9cEFynqNERybbdZc:-KVg9cEFynqNERybbdZd:b-klmhe0) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Backend/IRBuilderAsmJs.cpp#L3224)):*
> StackSym::New(m_func), 

Remove that argument so the StackSym is created using the same type as the RegOpnd

---

*[lib/Backend/IRBuilderAsmJs.cpp, line 3253 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVg9eQmJL5yzMmC22L_:-KVg9eQmJL5yzMmC22La:b-klmhe0) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Backend/IRBuilderAsmJs.cpp#L3253)):*
> StackSym::New(m_func), 

Remove that argument so the StackSym is created using the same type as the RegOpnd

---

*[lib/Runtime/ByteCode/OpCodes.h, line 272 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgBDMZtXQ0T3kKk_J7:-KVgBDMZtXQ0T3kKk_J8:b-pfgr2l) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Runtime/ByteCode/OpCodes.h#L272)):*
> ```objc
> MACRO_BACKEND_ONLY(     Conv_Bool,          Reg2,           OpTempNumberSources|OpCanCSE)                           // Convert from i4 to bool
> MACRO_BACKEND_ONLY(     Reinterpret_Prim,   Reg2,           OpTempNumberProducing|OpTempNumberSources|OpCanCSE)  // Reinterpret bits between primitives (int32/float32)
> MACRO_BACKEND_ONLY(     OverflowCheckReg2,  Reg2,           OpSideEffect)
> ```

Could you rename that to `TrapIfTruncOverflow`

---

*[lib/Runtime/ByteCode/OpCodes.h, line 739 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgBlyco22i8H_Zwb3t:-KVgBlyco22i8H_Zwb3u:bbtmfmy) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Runtime/ByteCode/OpCodes.h#L739)):*
> ```objc
> MACRO_BACKEND_ONLY(     Nearest_A,          Empty,          OpTempNumberSources|OpCanCSE|OpProducesNumber)
> MACRO_BACKEND_ONLY(     Unreachable_Void,   Empty,          OpSideEffect|OpNoFallThrough)
> MACRO_BACKEND_ONLY(     OverflowCheckReg3,  Reg3,           OpSideEffect)
> ```

Could you rename that to `TrapIfMintIntOverNegOne`

---

*[lib/Runtime/ByteCode/OpCodes.h, line 740 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgBrEewqKxUaabY38m:-KVgBrEewqKxUaabY38n:bjek1dj) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Runtime/ByteCode/OpCodes.h#L740)):*
> ```objc
> MACRO_BACKEND_ONLY(     Unreachable_Void,   Empty,          OpSideEffect|OpNoFallThrough)
> MACRO_BACKEND_ONLY(     OverflowCheckReg3,  Reg3,           OpSideEffect)
> MACRO_BACKEND_ONLY(     DivideByZeroCheck,  Reg3,           OpSideEffect)
> ```

Could you rename that to `TrapIfZero`

---

*[lib/Runtime/Language/JavascriptConversion.cpp, line 1517 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVfz8TGeROQZTzvWxGF:-KVfz8TGeROQZTzvWxGG:b-vryb64) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Runtime/Language/JavascriptConversion.cpp#L1517)):*
> ```cpp
>     }
> 
>     int64 JavascriptConversion::F32TOI64(float src, ScriptContext * ctx)
> ```

These need to be WebAssembly specific and use  `ThrowWebAssemblyRuntimeError` instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1848)*

**Comment by Cellule** [comment]
> These need to be WebAssembly specific and use ThrowWebAssemblyRuntimeError instead

Ignore this comment, will do this in a separate PR

**Comment by Cellule** [comment]
Reviewed 12 of 12 files at r5.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[lib/Runtime/Language/AsmJsUtils.cpp, line 238 at r5](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgFSWNmriZFdoixC1G:-KVgFSWPiCrg_1t2iaP0:b-3tyugc) ([raw file](https://github.com/microsoft/chakracore/blob/1367be171821c8b54f6aaab924f4ca71265f72fb/lib/Runtime/Language/AsmJsUtils.cpp#L238)):*
> ```cpp
> 
>                 *(int64*)(argDst) = 0;
>                 *(int64*)argDst = intVal;
> ```

`intVal` is int32 and this case is used for both int64 and int32
Per spec, I think we should trap when trying to unbox an int64.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1848)*

**Comment by Krovatkin** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[lib/Runtime/ByteCode/OpCodes.h, line 272 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgBDMZtXQ0T3kKk_J7:-KVgLkGZD-lZ1sJE9wy6:bgvs52k) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Runtime/ByteCode/OpCodes.h#L272)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Could you rename that to `TrapIfTruncOverflow`
</details>
will do 

---

*[lib/Runtime/ByteCode/OpCodes.h, line 739 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgBlyco22i8H_Zwb3t:-KVgLj4PBl7pdPESprLl:b-d7bhn0) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Runtime/ByteCode/OpCodes.h#L739)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Could you rename that to `TrapIfMintIntOverNegOne`
</details>
will do

---

*[lib/Runtime/ByteCode/OpCodes.h, line 740 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgBrEewqKxUaabY38m:-KVgLhfG__QykTEEE6-R:b-d7bhn0) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Runtime/ByteCode/OpCodes.h#L740)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Could you rename that to `TrapIfZero`
</details>
will do

---

*[lib/Runtime/Language/AsmJsUtils.cpp, line 238 at r5](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgFSWNmriZFdoixC1G:-KVgLmTPv0R46_wdKRbV:b7hhv6e) ([raw file](https://github.com/microsoft/chakracore/blob/1367be171821c8b54f6aaab924f4ca71265f72fb/lib/Runtime/Language/AsmJsUtils.cpp#L238)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> `intVal` is int32 and this case is used for both int64 and int32
> Per spec, I think we should trap when trying to unbox an int64.
</details>
I was actually going to ping you guys about this. Hit this issue in one of my tests. I needed a temp fix so I could run my tests and check the results. Let me double check what the spec has to say. If the spec says we need to throw I simply add an extra check or is this problem more pervasive? 

```cpp
if (info->GetArgType(i).isInt64())
{
     ThrowWebAssemblyRuntimeError ...
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1848)*

**Comment by Cellule** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[lib/Runtime/Language/AsmJsUtils.cpp, line 238 at r5](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgFSWNmriZFdoixC1G:-KVgWvePeNOXXVHWLNvG:b-nelq52) ([raw file](https://github.com/microsoft/chakracore/blob/1367be171821c8b54f6aaab924f4ca71265f72fb/lib/Runtime/Language/AsmJsUtils.cpp#L238)):*
<details><summary><i>Previously, Krovatkin (Nick Korovaiko) wrote…</i></summary>
> I was actually going to ping you guys about this. Hit this issue in one of my tests. I needed a temp fix so I could run my tests and check the results. Let me double check what the spec has to say. If the spec says we need to throw I simply add an extra check or is this problem more pervasive? 
> 
> ```cpp
> if (info->GetArgType(i).isInt64())
> {
>      ThrowWebAssemblyRuntimeError ...
> }
> ```
</details>
I think you can do the throw now. Normally with my incoming change we should throw before reaching this code.
However, I forgot about this one, so it would be better to throw now.

---

*[test/wasm/trunc.js, line 54 at r5](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgXOMSZyjBicIiM3Tf:-KVgXOMSZyjBicIiM3Tg:b-y9xffy) ([raw file](https://github.com/microsoft/chakracore/blob/1367be171821c8b54f6aaab924f4ca71265f72fb/test/wasm/trunc.js#L54)):*
> ```JavaScript
> print(trap(a.i64_trunc_s_f32,Number.NaN));
> print ("====");
> print(a.i64_trunc_u_f64(14757395258967641292));
> ```

Related to my other comment
I had forgotten about that. You can't pass int64 arguments directly from javascript.
I suggest you make a table with the int64 trunc functions then have a few functions that will do call_indirect passing a hardcoded int64.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1848)*

**Comment by Cellule** [comment]
Reviewed 10 of 15 files at r6, 12 of 12 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/Runtime/ByteCode/OpCodes.h, line 739 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgBlyco22i8H_Zwb3t:-KW-VCW_0VdDZ_LvqHg7:bc5v1um) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Runtime/ByteCode/OpCodes.h#L739)):*
<details><summary><i>Previously, Krovatkin (Nick Korovaiko) wrote…</i></summary>
> will do
</details>
nit: sorry I made a typo, it should be `TrapIfMinIntOverNegOne` not `TrapIfMintIntOverNegOne`

---

*[lib/Runtime/Language/AsmJsUtils.cpp, line 238 at r5](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgFSWNmriZFdoixC1G:-KW-U2rrLte4hHbjhv6x:b-plr4ts) ([raw file](https://github.com/microsoft/chakracore/blob/1367be171821c8b54f6aaab924f4ca71265f72fb/lib/Runtime/Language/AsmJsUtils.cpp#L238)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> I think you can do the throw now. Normally with my incoming change we should throw before reaching this code.
> However, I forgot about this one, so it would be better to throw now.
</details>
Please revert this change to `*(int32*)argDst = intVal;`

---

*[test/wasm/trunc.js, line 54 at r5](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgXOMSZyjBicIiM3Tf:-KW-VUNGa0FaaiN7iDbE:b-3pzsvi) ([raw file](https://github.com/microsoft/chakracore/blob/1367be171821c8b54f6aaab924f4ca71265f72fb/test/wasm/trunc.js#L54)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Related to my other comment
> I had forgotten about that. You can't pass int64 arguments directly from javascript.
> I suggest you make a table with the int64 trunc functions then have a few functions that will do call_indirect passing a hardcoded int64.
</details>
Why did you remove the int32 tests ?
Where is the wast for all the `exports.testX` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1848)*

**Comment by Krovatkin** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/Runtime/ByteCode/OpCodes.h, line 739 at r4](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgBlyco22i8H_Zwb3t:-KW-aFmSwdK5TirceeWs:bxava6n) ([raw file](https://github.com/microsoft/chakracore/blob/4a1254d5cf0d80e408c26019d332fa1ff3798147/lib/Runtime/ByteCode/OpCodes.h#L739)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> nit: sorry I made a typo, it should be `TrapIfMinIntOverNegOne` not `TrapIfMintIntOverNegOne`
</details>
yup, will fix that. 

---

*[lib/Runtime/Language/AsmJsUtils.cpp, line 238 at r5](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgFSWNmriZFdoixC1G:-KW-aTBBvBwocLbwn8-T:b-d7bhn0) ([raw file](https://github.com/microsoft/chakracore/blob/1367be171821c8b54f6aaab924f4ca71265f72fb/lib/Runtime/Language/AsmJsUtils.cpp#L238)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Please revert this change to `*(int32*)argDst = intVal;`
</details>
will do

---

*[test/wasm/trunc.js, line 54 at r5](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-KVgXOMSZyjBicIiM3Tf:-KW-aMf4I-1tpW7ujYp1:bhn4btq) ([raw file](https://github.com/microsoft/chakracore/blob/1367be171821c8b54f6aaab924f4ca71265f72fb/test/wasm/trunc.js#L54)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Why did you remove the int32 tests ?
> Where is the wast for all the `exports.testX` ?
</details>
oh, shoot :-( 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1848)*

**Comment by Krovatkin** [comment]
@MikeHolman I was testing a truncation sequence we have implemented for i32 and i realized it returns incorrect results if we feed it values like  `-0.4` (unsigned) or `-2147483648.8` (signed). 
This equality comparison we are using, ` (double) MIN_VALUE == initialValue`, isn't strong enough to capture MIN_VALUE.xxx (**xxx** is a fractional part) cases.

I can't seem to come up with a small enough fix :-( 

We either have to do 
* in an **overflow** (0x80000000) case, two inequality comparisons to make sure the original number was in the range (MIN_VALUE-1,MIN_VALUE+1] 
* even worse: in an **overflow** (0x80000000) case, add `+1` then convert and check for the overflow again.

I was wondering if you might have a better idea?

**Comment by Cellule** [comment]
@Krovatkin At this point I would prefer if you opened a new issues for this new bug, finish up this pull request and then fix the bug in a different pull request

**Comment by Krovatkin** [comment]
@Cellule, sure!

**Comment by Krovatkin** [comment]
@Cellule alright, it looks like all the little things are fixed now. Could you please take another look?

**Comment by Cellule** [comment]
:lgtm:

---

Reviewed 2 of 19 files at r2, 11 of 20 files at r8, 24 of 24 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1848#-:-KW4aj4wt0j7BfJUeQoW:bnfp4nl)*

**Comment by Cellule** [comment]
@dotnet-bot test OSX osx_osx_test please
@dotnet-bot test Ubuntu ubuntu_linux_test please

**Comment by commonlisp** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_test please
@dotnet-bot test OSX osx_osx_test please

**Comment by Krovatkin** [comment]
@Cellule @commonlisp I'm getting a feeling that one of the latest changes I have rebased upon is a bit funny. I have noticed other PRs that are up-to-date with the latest master failing the same test  whereas PRs that say they need to be rebased pass this test.

**Comment by Cellule** [comment]
@Krovatkin don't worry about it.
I am only waiting on our branch to stabilize then I will manually merge this in.

**Comment by Krovatkin** [comment]
@Cellule Awesome! Thanks!

**Pull request merged**
