### PR TITLE
WASM: Adding support for 64bit reinterpret casts

### LINKED ISSUE #1870: WASM - f64.reinterpret/i64
Implement operator f64.reinterpret/i64

### LINKED ISSUE #1871: WASM - i64.reinterpret/f64
Implement operator i64.reinterpret/f64

### PR DESCRIPTION
**Pull request by arunetm**
adding i64.reinterpret/f64
adding f64.reinterpret/i64
updating spec test baslines

Fixes #1870, Fixes #1871

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1919)

### CODE REVIEW

**Comment by arunetm** [comment]
@Cellule @MikeHolman please review.

**Comment by Cellule** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/Backend/LowerMDShared.cpp, line 8738 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1919#-KVlFk0iMUedKIJS7tOI:-KVlFk0iMUedKIJS7tOJ:b-k4p2es) ([raw file](https://github.com/microsoft/chakracore/blob/19edabff079b685f24e212dc6015ab1fddf77166/lib/Backend/LowerMDShared.cpp#L8738)):*
> ```cpp
> LowererMD::LowerReinterpretPrimitive(IR::Instr* instr, IR::Opnd& dst, IR::Opnd& src)
> {
>     if ((dst.IsInt64() && src.IsFloat64()) ||
> ```

You do not need nor should pass the dst and src as arguments.
Please get the dst and src operands from the instr instead.

---

*[lib/Backend/LowerMDShared.cpp, line 8749 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1919#-KVlJF9eUiGTcA4HPkCY:-KVlJF9eUiGTcA4HPkCZ:b-omk45i) ([raw file](https://github.com/microsoft/chakracore/blob/19edabff079b685f24e212dc6015ab1fddf77166/lib/Backend/LowerMDShared.cpp#L8749)):*
> ```cpp
>         if (dst.IsInt64())
>         {
>             Assert(src.IsFloat64());
> ```

This can be done without helper call
```asm
movsd mmword ptr [esp+40h],src
mov dst.lowbits,dword ptr [esp+40h]
mov dst.highBits,dword ptr [esp+44h]
```

You can use `Int64RegPair dstPair = m_lowerer->FindOrCreateInt64Pair(dst);` to get the low/high bits pair

---

*[lib/Backend/LowerMDShared.cpp, line 8755 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1919#-KVlIz7OnQTWNVZsSAEX:-KVlIz7OnQTWNVZsSAEY:b-57876l) ([raw file](https://github.com/microsoft/chakracore/blob/19edabff079b685f24e212dc6015ab1fddf77166/lib/Backend/LowerMDShared.cpp#L8755)):*
> ```cpp
>         else
>         {
>             Assert(src.IsInt64());
> ```

This can be done without helper call.
```asm
mov dword ptr [esp+40h],src.lowbits
mov dword ptr [esp+44h],src.highBits
movsd dst,mmword ptr [esp+40h] 
```
You can use `Int64RegPair srcPair = m_lowerer->FindOrCreateInt64Pair(src);` to get the low/high bits pair

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1919)*

**Comment by arunetm** [comment]
Review status: 12 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/Backend/LowerMDShared.cpp, line 8738 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1919#-KVlFk0iMUedKIJS7tOI:-KW05oorY5xVhsHgTTZb:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/19edabff079b685f24e212dc6015ab1fddf77166/lib/Backend/LowerMDShared.cpp#L8738)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> You do not need nor should pass the dst and src as arguments.
> Please get the dst and src operands from the instr instead.
</details>
Done.

---

*[lib/Backend/LowerMDShared.cpp, line 8749 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1919#-KVlJF9eUiGTcA4HPkCY:-KW05mqFfgX8MH2haSCE:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/19edabff079b685f24e212dc6015ab1fddf77166/lib/Backend/LowerMDShared.cpp#L8749)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> This can be done without helper call
> ```asm
> movsd mmword ptr [esp+40h],src
> mov dst.lowbits,dword ptr [esp+40h]
> mov dst.highBits,dword ptr [esp+44h]
> ```
> 
> You can use `Int64RegPair dstPair = m_lowerer->FindOrCreateInt64Pair(dst);` to get the low/high bits pair
</details>
Done.

---

*[lib/Backend/LowerMDShared.cpp, line 8755 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1919#-KVlIz7OnQTWNVZsSAEX:-KW05nlRTM4OClgzPl8O:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/19edabff079b685f24e212dc6015ab1fddf77166/lib/Backend/LowerMDShared.cpp#L8755)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> This can be done without helper call.
> ```asm
> mov dword ptr [esp+40h],src.lowbits
> mov dword ptr [esp+44h],src.highBits
> movsd dst,mmword ptr [esp+40h] 
> ```
> You can use `Int64RegPair srcPair = m_lowerer->FindOrCreateInt64Pair(src);` to get the low/high bits pair
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1919)*

**Comment by arunetm** [comment]
*[lib/Backend/LowerMDShared.cpp, line 8755 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1919#-KVlIz7OnQTWNVZsSAEX:-KW09RObLAW00WuyDKkx:b3z85n7) ([raw file](https://github.com/microsoft/chakracore/blob/19edabff079b685f24e212dc6015ab1fddf77166/lib/Backend/LowerMDShared.cpp#L8755)):*
<details><summary><i>Previously, arunetm (Arun Purushan) wrote…</i></summary>
> Done.
</details>
fastpath using
            //    movd low_bits, xmm1
            //    shufps xmm1, xmm1, 2
            //    movd high_bits, xmm1 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1919)*

**Comment by Cellule** [comment]
Reviewed 7 of 11 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/Backend/LowerMDShared.cpp, line 8755 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1919#-KVlIz7OnQTWNVZsSAEX:-KW0BQ30SUMr3eKaYxt1:b78me3b) ([raw file](https://github.com/microsoft/chakracore/blob/19edabff079b685f24e212dc6015ab1fddf77166/lib/Backend/LowerMDShared.cpp#L8755)):*
<details><summary><i>Previously, arunetm (Arun Purushan) wrote…</i></summary>
> fastpath using
>             //    movd low_bits, xmm1
>             //    shufps xmm1, xmm1, 2
>             //    movd high_bits, xmm1 
</details>
The last movd will overwrite the first value you've set.
In this case, the only solution I found is
```asm
movd xmm0, lowBits;
movd xmm1, highBits;
shufps xmm0, xmm1, (0 | 2 << 2 | 0 << 4 | 1 << 6);
shufps xmm0, xmm0, (0 | 2 << 2 | 3 << 4 | 3 << 6);
```
The first shufps will leave lowBits where it is and place highBits from xmm1 to 3rd slot
The second shufps will move the highBits from the 3rd slot to the 2nd.

From the doc for shufps here's the actions:
1st
```
0: DEST[31:0] ← DEST[31:0];
2: DEST[63:32] ← DEST[95:64];
0: DEST[95:64] ← SRC[31:0];
1: DEST[127:96] ← SRC[63:32];
With xmm0 as DEST and xmm1 as SRC
```
2nd
```
0: DEST[31:0] ← DEST[31:0];
2: DEST[63:32] ← DEST[95:64];
3: DEST[95:64] ← SRC[127:96];
3: DEST[127:96] ← SRC[127:96];
With xmm0 as DEST and SRC
```

---

*[lib/Backend/LowerMDShared.cpp, line 8757 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1919#-KW07MZ_4-emdGmpxDgB:-KW07MZ_4-emdGmpxDgC:br7ncq5) ([raw file](https://github.com/microsoft/chakracore/blob/5716b8489586a937ad1fbeff05a1d8ad7df81f86/lib/Backend/LowerMDShared.cpp#L8757)):*
> IR::IntConstOpnd::New(2, TyInt8, m_func, true)

This needs to be 1 for `1: DEST[31:0] ← DEST[63:32];`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1919)*

**Comment by Cellule** [comment]
Merged in https://github.com/Microsoft/ChakraCore/commit/781b81b8740e0b9d739c4fde5171c427400265e6

**Pull request closed without merging**
