### PR TITLE
Fix Ubuntu build

### PR DESCRIPTION
**Pull request by pleath**
Fix Ubuntu build following check-in of code that requires SSE4.2 support on AMD64.

### CODE REVIEW

**Comment by MikeHolman** [comment]
@pleath I already had fix for this out last night (now merged) https://github.com/Microsoft/ChakraCore/pull/1743

**Comment by pleath** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_test_static

**Comment by pleath** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug_static

**Comment by pleath** [comment]
Good. Thanks.

-- Paul

**Comment by pleath** [comment]
@MikeHolman already pushed this fix.

**Pull request closed without merging**
