### PR TITLE
Remove starting and ending newline character from function display string

### PR DESCRIPTION
**Pull request by agarwal-sandeep**
Chakra  "\nfunction(){\n  [native code]\n}\n"
Firefox "function (){\n}"
Chrome "function () {}"

For arguments.callee.__proto__.toString() (or any native function toString) Chakra shows form feed character (\012) at begining and end whereas Firefox and Chrome doesn't.

VSCode removes the newline after function but doesn't remove the starting so it shows up in locals display.

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks, this has long been the case for IE as well, and it'll be good to have some coherence across browsers :-)

**Comment by akroshg** [comment]
:shipit:

**Comment by jianchun** [comment]
Any reason why not use `\n` there?

**Comment by agarwal-sandeep** [comment]
@jianchun This has been like this from very beginning and it seems we use \012 at other places as well like closeFormals. @bterlson to see if this is something related to spec though I couldn't find anything related

**Comment by jianchun** [comment]
@agarwal-sandeep Thanks for look! I wondered why we used `\012` instead of `\n` every time I saw them.

**Comment by dilijev** [comment]
@jianchun do you mean we render them as literal text `\n` or `\012` or do we render them as newlines?

**Comment by jianchun** [comment]
@dilijev No problem for rendering. The source code uses `\012` where we'd usually use `\n`. I think they are equivalent, and `\012` is less apparent than `\n`.

**Comment by dilijev** [comment]
@jianchun yes they are equivalent. I agree `\n` is more apparent.

**Pull request merged**
