### PR TITLE
xplat: build-time fixes and enabling runtime features

### PR DESCRIPTION
**Pull request by obastemur**
- xplat: library visibility changes [/cc nodejs-chakracore]
- osx: enable temp disabled profiling/tracking features
- osx: make 10.9 default minimum target [/cc nodejs-chakracore]
- xplat: do not static link to libstdc++ (shared)

### CODE REVIEW

**Comment by obastemur** [comment]
removed libstdc++ update from the PR but somehow unable to edit merge description..

**Comment by obastemur** [comment]
@dotnet-bot test OSX osx_osx_test_static

**Comment by jianchun** [comment]
:shipit:

**Comment by obastemur** [comment]
@jianchun Thanks for the review!

**Pull request merged**
