### PR TITLE
Added test case where string.replace hangs

### PR DESCRIPTION
**Pull request by dryganets**

### CODE REVIEW

**Comment by dryganets** [comment]
@kfarnung you can remove external contributor tag I'm Microsoft employee.

**Comment by dilijev** [comment]
@dryganets it's possibly a bad name for the idea but "External Contributor" means that someone with access to Chakra's internal infrastructure needs to adopt this PR, run internal (Chakra + ChakraCore) tests, and merge it through our tools. If you'd like to do this yourself, please contact us offline and we can walk you through it.

**Comment by kfarnung** [comment]
Hey @dryganets, I originally added and then removed it when I realized that you work at Microsoft, but the purpose of the tag is to indicate PRs which need to be landed by a Chakra developer.

**Comment by jackhorton** [comment]
The bug has already been filed: https://github.com/Microsoft/ChakraCore/issues/4774

**Comment by dryganets** [comment]
@dilijev I didn't mean to contribute this.
This way it is just easier to repro for you.

**Comment by kfarnung** [comment]
Thanks for the detailed report and repro @dryganets, we'll continue to track this in #4774.

**Comment by dilijev** [comment]
@dryganets feel free to contact me at work and I can walk you through how to get a better sense of how your regex would be evaluated which might help put your mind at ease.

**Pull request closed without merging**
