### PR TITLE
Fix some mac compile errors (now just warnings)

### PR DESCRIPTION
**Pull request by Fishrock123**
Fixes https://github.com/Microsoft/ChakraCore/issues/1436

### CODE REVIEW

**Comment by Fishrock123** [comment]
fml I screwed this up completely, rebasing and fixing WIP

**Comment by obastemur** [comment]
@dotnet-bot test Windows arm_release please

**Comment by obastemur** [comment]
@Fishrock123 LGTM, going to merge this one once the tests are complete. Thanks!

**Comment by Fishrock123** [comment]
yay! Thanks! :D

**Pull request merged**
