### PR TITLE
Add C++98 native test to ensure we don't break again

### PR DESCRIPTION
**Pull request by obastemur**
#2001 fixes Jsrt C99/C++98 compatibility issue. @dilijev brought the idea of adding a test to make sure we don't break it again.

This native test should take care of that.

p.s.: This PR will break until #2001 is merged.

/cc @dilijev @jcoffland

### CODE REVIEW

**Comment by dilijev** [comment]
LGTM

**Comment by dilijev** [comment]
It looks like in this case the failure of OSX tasks before the outage will prevent our automation from merging this PR (because it looks like tests failed, and we can't requeue).

Options are to wait for OSX coverage to come back online or merge manually without OSX coverage.

/cc @mmitche @obastemur

**Comment by obastemur** [comment]
@dilijev Thanks for dealing with this. IMHO we can wait for CI. Nothing urgent here.

**Comment by mmitche** [comment]
@dilijev Things should be up sometime today.

**Comment by dilijev** [comment]
@obastemur looks like there are still some failures related to `nullptr` in Linux tests.

**Comment by obastemur** [comment]
@dilijev let me rebase.

**Comment by obastemur** [comment]
@dilijev Thanks for the review

**Pull request merged**
