### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by EdMaurer**
Code coverage identified several untested paths that upon analysis only existed to support an old IE technology, HTC. Get rid of it.

### CODE REVIEW

**Comment by akroshg** [comment]
:shipit:

**Comment by dilijev** [comment]
Noting XamlTaskFactory issue. /cc @mmitche 
http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/x64_release_prtest/1943/

@dotnet-bot test Windows x64_release please

**Comment by dilijev** [comment]
LGTM

**Comment by digitalinfinity** [comment]
LGTM- although IIRC, this code was for the old language service, no?

**Comment by pleath** [comment]
LGTM, though I’m almost sad to see it go. There are some stories that go with that code…

-- Paul

**Comment by dilijev** [comment]
@dotnet-bot test OSX osx_osx_debug_static please

**Pull request merged**
