### PR TITLE
master: Update version to 1.7.0; set to DEV mode; no new GUID is needed.

### PR DESCRIPTION
**Pull request by dilijev**

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test ci_disablejit_x64_debug please

**Comment by dilijev** [comment]
@mmitche That's funny, the name of the check `ci_disablejit_x64_debug` overlapped the trigger for `ci`. Did you add the `\b` boundaries on the RegExp for `ci`? Is there any way I can re-trigger that build without re-triggering them all (by e.g. pushing a new ref, close/reopen)?

**Comment by dilijev** [comment]
@mmitche ping

I'm pushing a new ref to reset the CI

**Comment by mmitche** [comment]
@dilijev you can do '@dotnet-bot test this plaese' (spell correctly)

I haven't changed anything about the triggers in a while

**Comment by dilijev** [comment]
@mmitche I was hoping to avoid re-triggering all checks if possible. There's that overlap between the ci trigger and the trigger with ci in the name. Maybe we should just update the name of those checks to put ci at the end instead of the beginning. /cc @MSLaguana

**Comment by mmitche** [comment]
@dilijev If it failed, you can click on the details link, log in and click "retry" on the left.

**Comment by dilijev** [comment]
@dotnet-bot 
test Ubuntu shared_ubuntu_linux_debug 
test Ubuntu shared_ubuntu_linux_test

@mmitche I thought retry didn't usually have the desired effect, but if that works now, that's good to know.

**Comment by mmitche** [comment]
@dilijev Retry does, Rebuild does not.

**Pull request merged**
