### PR TITLE
Fix #3597

### LINKED ISSUE #3597: [1.7] daily_slow_x64_test failures in WASM tests
```
14:52:07 4>Summary: wasm had 39 tests; 3 failures
14:52:45 interpreted\rl.results.log:wasm (limits.js ( -wasm -args --no-verbose --start 4 --end 12 -endargs) exe) -- failed : exec time=4
14:52:45 interpreted\rl.results.log:wasm (limits.js ( -wasm -args --no-verbose --end 4 -endargs) exe) -- failed : exec time=7
14:52:45 interpreted\rl.results.log:wasm (limits.js ( -wasm -args --no-verbose --start 12 -endargs) exe) -- failed : exec time=54
```

Changes resulting in first occurrence of failure:
https://ci2.dot.net/job/Microsoft_ChakraCore/job/release_1.7/job/daily_slow_x64_test/37/changes

Started failing on 8/21

### PR DESCRIPTION
**Pull request by Cellule**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/3598)

Fixes #3597

### CODE REVIEW

**Comment by Cellule** [comment]
@dotnet-bot test daily_slow_x64_test

**Comment by Cellule** [comment]
@dotnet-bot test Windows ci_slow_x64_test

**Comment by Cellule** [comment]
@dotnet-bot test Windows daily_slow_x64_test

**Comment by dilijev** [comment]
You could run all the slow tests if you wanted as well. https://github.com/Microsoft/ChakraCore/wiki/Jenkins-Build-Triggers#daily-builds-with-slow-tests

**Pull request merged**
