### PR TITLE
Disable adding daily triggers for CI dev branches ending in '-ci'

### PR DESCRIPTION
**Pull request by dilijev**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/966)

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by dilijev** [comment]
//FYI @mmitche @digitalinfinity @obastemur

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by dilijev** [comment]
@dotnet-bot test this please

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by digitalinfinity** [comment]
lgtm

**Comment by mmitche** [comment]
LGTM

**Pull request merged**
