### PR TITLE
xplat: fix CI

### PR DESCRIPTION
**Pull request by obastemur**
~~Trying a change on CI.~~ fix CI

### CODE REVIEW

**Comment by obastemur** [comment]
Changes will be tracked by #4204

**Comment by MSLaguana** [comment]
Is this just hiding/ignoring the issue for the short term?

**Comment by obastemur** [comment]
@MSLaguana below is a copy-paste from the changes

```
// xplat-todo: pal pthread-exit strategy needs a revisit for the last! thread.
```

This is a long term PAL issue with xplat static builds on linux. It again showed up because I did enable the asserts with last PR. The asserts are still enabled on OSX. It happens during last thread exit. No harmful (since no other thread left and locking doesn't really matter) but it's annoying and now being tracked by #4204 

> I understand the rtti fix.

@MSLaguana , could you please share what is that? I was going to look at that separately.

**Comment by jackhorton** [comment]
We don't fully understand the RTTI issue, but up until recently, we had RTTI enabled at all times on xplat and disabled at all times on Windows. I had to use RTTI for something in ICU, so I tried to disable it everywhere on xplat except for PlatformAgnostic, but then we found that Debug and Test builds used it for something (I think its involved in garbage collection tracing). So, we added an initial change to disable RTTI only in Release mode on xplat, which is really where we care about it not being there anyways. However, since we didn't have CI for xplat intl until a few days ago, we didn't realize that since that time, there has been an issue with xplat builds that are release + shared + with-intl where loading libChakraCore.so fails saying it can't find a whole bunch of symbols (Js::DynamicObject is the one that shows up but dumping the .so shows a bunch of undefined symbols being referenced). As it stands right now, we don't have any idea why doing a .so build with intl in release mode causes this but release .so's without Intl and release .a's with intl dont show this problem. Since release + shared + intl isnt the default build config (and the historical behavior was to always use RTTI everywhere), we decided to add it to the list of RTTI-enabled configs for now until we understand it better.

**Comment by MSLaguana** [comment]
Perhaps "understand" is putting it too strongly; I understand the symptoms and why it fixes the issue, but I don't fully know why it is needed yet.

Jack explained it well above, but I'll just add that the specific symbols that are missing from the .so are RTTI typeinfos for things like Js::DynamicObject, which we didn't think we actually needed.

**Comment by obastemur** [comment]
I will merge this PR as is but I just looked at the RTTI problem and it looks like the type information is being optimized away. I had patched ChakraCore.so before (https://github.com/Microsoft/ChakraCore/blob/master/bin/ChakraCore/ChakraCoreShared.cpp#L13) and looks like it needs some additions for O3 builds.

**Comment by obastemur** [comment]
Possible fix RTTI, remove `__APPLE__` from https://github.com/Microsoft/ChakraCore/blob/master/bin/ChakraCore/ChakraCoreShared.cpp#L13 and use the same approach for linux shared builds

**Comment by MSLaguana** [comment]
I'm not sure that's the right approach; in release builds we want to build without rtti as much as possible to reduce binary size, and the scope where rtti is required should be limited to PlatformAgnostic, which shouldn't see into the `Js::` namespace at all. Thus, we expected that we should not need rtti typeinfos for things like Js::DynamicObject; I believe that the bug here is that `libChakraCore.so` is asking for the typeinfos to be provided by some object, and it should not.

**Comment by obastemur** [comment]
>  I believe that the bug here is that libChakraCore.so is asking for the typeinfos to be provided by some object, and it should not.

Not sure I understood. Do you have a call stack etc. showing that?

For what exactly we need RTTI for?

**Comment by jackhorton** [comment]
ICU's C++ API expects that you can dynamic_cast for certain operations. They also seem to have their own mini-RTTI interface but we didn't look into using that for now. Regardless, in the future we hope to actually not need the C++ API at all since the system-installed ICU doesnt _technically_ support it, so I don't think its worth investing too much time into.

**Pull request merged**
