### PR TITLE
Globopt Instr string config flag

### PR DESCRIPTION
**Pull request by Cellule**
Add option to disable printing Globopt instr strings post lower.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/3571)

### CODE REVIEW

**Comment by Cellule** [comment]
@meg-gupta Yeah, when trying to look at the asm code we generate, the globopt instr are in the way and make it hard to wrap your head around the asm code

**Comment by agarwal-sandeep** [comment]
For most cases the globopt string is useful. I think instead of enabling this using a switch you should not print if the switch is passed so that others don't need to pass a new switch and for asm you can pass the switch to not print the string.

**Comment by thomasmo** [comment]
looks like the default behavior is a no-op, so no objections here

**Comment by Cellule** [comment]
> For most cases the globopt string is useful. I think instead of enabling this using a switch you should not print if the switch is passed so that others don't need to pass a new switch and for asm you can pass the switch to not print the string.

@agarwal-sandeep: like @thomasmo said, I haven't changed the default. If you pass `-PrintGlobOptInstrString-` now it won't print them anymore

**Comment by agarwal-sandeep** [comment]
@Cellule thanks. I missed looking at the default true value.

**Comment by LouisLaf** [comment]
Let's use a -off: switch for this.

**Pull request merged**
