### PR TITLE
Remove ch.exe and rl.exe from Release build configurations

### LINKED ISSUE #90: Building x64_release: ch.exe doesn't do anything
Built x64_release Using Visual Studio 2015 Update 1.   When running ch.exe from the command prompt it says:

    Try 'ch.exe -?' for help

When issuing 'ch.exe -?', program reports error:

    The binary chakracore.dll is not test enabled, please use chakracore.dll from debug/test flavor

### PR DESCRIPTION
**Pull request by ianwjhalliday**
Fix #90.  ch.exe does not work with Release builds of ChakraCore.dll so
do not bother building it in Release builds.  Since there's no ch.exe in
Release builds there is then also no need for rl.exe so remove it as
well from Release builds.

### CODE REVIEW

**Comment by dilijev** [comment]
LGTM

**Comment by ianwjhalliday** [comment]
@dilijev do the CI and internal builds use the .sln file to decide which projects to build?  This change here only affects the .sln file.

**Comment by MikeHolman** [comment]
Not sure if this removes ch.exe from building in CI as well, but I believe static analysis tool only runs on release build... so I'm a little hesitant to remove it.

**Comment by ianwjhalliday** [comment]
Fair point and it also doesn't necessarily help clarify since now ch.exe won't exist in a Release build and there will be no explanation.

Changing the error message to be more explicit would be a better short term solution and then opening an issue to allow ch.exe to work with a release build would be the next step towards ideal solution.

**Pull request closed without merging**
