### PR TITLE
Post-Op bailout with unconditional branches

### PR DESCRIPTION
**Pull request by Cellule**
When searching for new bytecode instr for a post-op bailout, follow unconditional branches.

OS#17449647

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/5250)

### CODE REVIEW

**Comment by rajatd** [comment]
What does the test/IR look like?

**Comment by Cellule** [comment]
The test looked something like
```js
function foo(a) {
  switch (a) {
    case '': return this;
    case 1:
  }
}
foo(1);
```

Because of Switch case int/string optimisation we could end up with the following IR after IRBuilder
```
BrSrEq_A $L2 s1, s2
// case 1:
BrSrEq_A $L3 s1, s3  #0004
Br $L1                #0004
// EndSwitch    
Br $L1                #0006
// return this <== body of first case
$L2: ... Br $L1
$L3: ...
$L1: // end of switch
```
FG Peeps would then remove `Br $L1 #0006` because it is unreachable.
Later, when trying to add a bailout on implicit calls to BrSrEq_A, just looking at next instr, we would end up tyring to bailout to the body of the first case instead of the end of the switch case.
By Following unconditional branches, we at least bailout after the switch case.

This sounds pretty bad as it is, however, it turns out that bailout is actually impossible, because BrSrEq_A cannot have implicit calls when one of the opnd is guarantied to be an int or string.
I will follow up in another PR to prevent emitting the bailout in the first place.

**Comment by Cellule** [comment]
ping

**Comment by meg-gupta** [comment]
Would be good to add the unit test. Otherwise LGTM.

**Pull request merged**
