### PR TITLE
make it still working with disabling concurrent GC

### PR DESCRIPTION
**Pull request by leirocks**

### CODE REVIEW

**Comment by leirocks** [comment]
@dotnet-bot  test this please

**Comment by dilijev** [comment]
Should we add a CI definition to test with concurrent GC disabled?

**Comment by leirocks** [comment]
I don't think that is still needed. This is just make sure it's still easy to be disabled, and in the future if someone wants to disable concurrent GC to do some testing, it will be less work to do.

**Comment by dilijev** [comment]
This replaces https://github.com/Microsoft/ChakraCore/pull/2454 right? If so, can you close that PR?

**Pull request merged**
