### PR TITLE
Fix EOL violations introduced by commits that came into master via a pump

### PR DESCRIPTION
**Pull request by dilijev**
Fix EOL violations introduced by commits that came into master via a pump, or by otherwise bypassing validation.

Additionally exclude .man files from the check because there is a manifest file that may require CRLF.

### CODE REVIEW

**Comment by dilijev** [comment]
This PR is in response to violations discovered while investigating the cause of EOL Check that failed on https://github.com/Microsoft/ChakraCore/pull/5977

**Comment by batarmanrookie666** [comment]
Heee  what? Lolll it’s Always like that with the web bigshot they give you 3 or 4 softwares for take your big part of cake on users and after they notify you you crack de tom tom sattelite a good shot you just go on FUKIN google map... You know what i really dont think so whatsoever i have triing to do except continue to try desinfect my fukin enterprise system so C’mon Man just do your shit I DONT CARE YOU KNOW WHERE FIND M@!!! LOLLLL

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Doug Ilijev <notifications@github.com>
Envoyé : Wednesday, February 27, 2019 8:11:00 PM
À : Microsoft/ChakraCore
Cc : Subscribed
Objet : [Microsoft/ChakraCore] Fix EOL violations introduced by commits that came into master via a pump (#5980)


Fix EOL violations introduced by commits that came into master via a pump, or by otherwise bypassing validation.

Exclude .man from the check because there is a manifest file that may require CRLF.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Microsoft/ChakraCore/pull/5980<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130615993934&sdata=kBu99to1yxNxOXbifOnYYKI7e21ww2Ud9jcrpIxd%2B5Q%3D&reserved=0>

Commit Summary

  *   Fix EOL violations introduced by commits that came into master via a pump.

File Changes

  *   M jenkins/check_eol.sh<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-0&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616003939&sdata=0SMO6ffv6HF6TvtNMXVtmU0JCloQQiANyW9Y4FqGhk0%3D&reserved=0> (2)
  *   M lib/Runtime/Library/CMakeLists.txt<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-1&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616013944&sdata=Wp10thEEHiPn1bUQCuJs5rOD2EW8ZW0WjUD33ryaCE8%3D&reserved=0> (276)
  *   M lib/Runtime/Types/CMakeLists.txt<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-2&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616023955&sdata=aXCHa4NcppjVTHdAoZnABVWfyqnB2XMIKAJ6wwsBEAM%3D&reserved=0> (64)
  *   M test/GlobalFunctions/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-3&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616033960&sdata=NxGSEo6VsQjvNQJB14703W77%2BuAIU3Bvpp2BYM4tVB8%3D&reserved=0> (196)
  *   M test/InlineCaches/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-4&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616043971&sdata=sOFjseS6inuOl5XaN04hWEV0kfEaEzo7kLBbFV2XaWI%3D&reserved=0> (280)
  *   M test/JsBuiltIns/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-5&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616053976&sdata=JvE%2FO9sOLhZea50NYTjLoMfnOKlZOqyPVzpfy6v36gA%3D&reserved=0> (40)
  *   M test/Lib/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-6&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616063987&sdata=gNCnV5AkuLS9Pp4lK6ABnBoVSDQoEMLs57EW19g2J5E%3D&reserved=0> (270)
  *   M test/Miscellaneous/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-7&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616073992&sdata=M1k2%2Bpo4QurMs%2BlaLo4rPYes194p8PhAw8X%2FuMoPjXE%3D&reserved=0> (266)
  *   M test/Object/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-8&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616084003&sdata=TZA7E4B69RhuxiniRTpQIWkj3VpNoJGr3zUxdNVXkcg%3D&reserved=0> (1002)
  *   M test/Optimizer/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-9&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616094014&sdata=VyK%2FscWqF2jHjYYxLEnRWYRySmPBFmONThYGroeW2YY%3D&reserved=0> (3200)
  *   M test/PRE/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-10&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616104025&sdata=z3BV9fl7aBhb68C%2Fl6lnX7Hc%2BEkXaSSzXXW1nrNsTRU%3D&reserved=0> (34)
  *   M test/Prototypes/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-11&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616104025&sdata=BfbaHdp9V6ZFiqRBQ3ptEuTemBAEopRySleO9G8jxC8%3D&reserved=0> (108)
  *   M test/Regex/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-12&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616114036&sdata=06nCt9eyRgjzGRgELFaMZlNid0d%2Bri3BA0PEEoGIW48%3D&reserved=0> (500)
  *   M test/Strings/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-13&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616124035&sdata=o%2FcsYvPvfzE9J8L%2FxkRJpXYgZIYpTi7mOYwnzJZgH4s%3D&reserved=0> (532)
  *   M test/WasmSpec.MultiValue/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-14&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616134046&sdata=yvk97biu46lprPmvStW5eZ2ZO68hFkuYJsdj3AmyGkA%3D&reserved=0> (30)
  *   M test/es5/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-15&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616144057&sdata=f4XjKl1k0nmsCu6FCy%2FEpNU8sCSheakpOif6P7kLUsU%3D&reserved=0> (716)
  *   M test/inlining/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-16&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616154056&sdata=VIc22p4dddxyRcotXAxJlrXXnbubK7u%2FtRx9Bn58VDw%3D&reserved=0> (656)
  *   M test/strict/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-17&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616164067&sdata=OyuiEvl3hs%2F9c1GyEGUwH%2BJXS65LWURbzJjeSNillno%3D&reserved=0> (1450)
  *   M test/typedarray/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-18&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616174072&sdata=U31jnFoPz0pD4L6YLAsI0ZCRiepRhUDnS58fH2wdxUs%3D&reserved=0> (862)
  *   M test/utf8/rlexe.xml<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-19&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616184095&sdata=uXatvx3kuBntTrJJ3ne9Xs2mAEOSNAqsXiduJw6YPx8%3D&reserved=0> (114)
  *   M tools/RecyclerChecker/.gitignore<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980%2Ffiles%23diff-20&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616194106&sdata=cg%2ByPwCvdu3Nf%2BqjUE3%2BN7A9ObCXilcz2xGD%2Bc1JLis%3D&reserved=0> (2)

Patch Links:

  *   https://github.com/Microsoft/ChakraCore/pull/5980.patch<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980.patch&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616204105&sdata=L6DWXiVYaPmm9%2FOjmlGH5PpnikB1Be0zIDSRxO3d9ps%3D&reserved=0>
  *   https://github.com/Microsoft/ChakraCore/pull/5980.diff<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FChakraCore%2Fpull%2F5980.diff&data=02%7C01%7C%7Ce641204361fd46e6a70608d69d199a7b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636869130616214104&sdata=ttxlb9LH8BI7HMURhRyHXeolSCSCy6Z1pN84HySxqEM%3D&reserved=0>

**Comment by dilijev** [comment]
Closing this PR. Merged in https://github.com/Microsoft/ChakraCore/pull/5981

**Comment by dilijev** [comment]
cc @pleath @wyrichte

**Pull request closed without merging**
