### PR TITLE
ams.js simd.js : adding missing attirbutes to jit-related tests so they won't run w/ jit disabled, Fixes #964

### LINKED ISSUE #964: [Test failure] [Daily] [DisableJIT] [All Branches] testSimdManyVars.js b95.js b108.js failing in Daily DisableJIT builds.
See daily build statuses for all branches here:
https://github.com/Microsoft/ChakraCore/wiki/Build-Status#disablejit-builds
https://github.com/Microsoft/ChakraCore/wiki/Build-Status-%28release-1.2%29#disablejit-builds
https://github.com/Microsoft/ChakraCore/wiki/Build-Status-%28linux%29#disablejit-builds

See logs for example:
http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/daily_disablejit_x64_debug/58/console
http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/release_1.2/job/daily_disablejit_x64_debug/40/console
http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/linux/job/daily_disablejit_x64_debug/9/console

@Krovatkin I believe this is your bug because you're the only person who has touched these files. Please fix with high priority to unblock merging the linux branch into master.

FYI @digitalinfinity

### PR DESCRIPTION
**Pull request by Krovatkin**
excluding more jit tests in disablejit mode

Fixes #964

### CODE REVIEW

**Comment by Krovatkin** [comment]
fixes #964

**Comment by Krovatkin** [comment]
@dilijev please take a look at this PR when you have a mnt.
@arunetm could you please help me to merge this PR when its approved by MSFT
just fyi: @nmostafa

**Comment by arunetm** [comment]
@dilijev can you please review this PR. Thanks.

**Comment by dilijev** [comment]
@dotnet-bot test nojit tests please

**Comment by dilijev** [comment]
Fix LGTM but wait for the disablejit tests to pass to ensure the issue is resolved.

**Comment by dilijev** [comment]
FYI @digitalinfinity

**Comment by dilijev** [comment]
LGTM, all checks passed. Good to merge, @arunetm

**Comment by arunetm** [comment]
Merged. Thanks.

**Pull request merged**
