### PR TITLE
[wasm] Fix debugger test baseline

### PR DESCRIPTION
**Pull request by commonlisp**
Get the tests passing again after merge

### CODE REVIEW

**Comment by MikeHolman** [comment]
lgtm

**Comment by akroshg** [comment]
how it was broken before? was it due to bad merge job or some functionality go changed?

**Comment by commonlisp** [comment]
I think it was a little of both. Parts of a Jsrt object was changed and there was way too much time since the last merge so some things did break.

**Comment by commonlisp** [comment]
@Cellule So this is all covered with your commit, right? 
Closing

**Comment by Cellule** [comment]
It was partly a bad merge.
There were stuff changed in WscriptJsrt and I had to rewrite some things added for wasm.
Which made the baseline slightly different.
It is indeed fixed in 95ff95ff3b336615ff7a8776f34771714180fb37

**Pull request closed without merging**
