### PR TITLE
Issue#829: class extends null should bind this

### LINKED ISSUE #829: class extends null should bind this
See also: https://github.com/tc39/ecma262/issues/543

Spec has fixed a bug that was not allowing classes that extend null to use `this` in the constructor body. This has been fixed, and our implementation needs updates to conform!

### PR DESCRIPTION
**Pull request by suwc**
A class that extends null should have 'this' binding in its constructor same way as a base class. Add new function attribute 'BaseConstructorKind' to capture 'extends null' cases during class definition evaluation. Add new opcode for branching on 'extends null' scenario for 'this' binding.

Fixes #829

### CODE REVIEW

**Comment by suwc** [comment]
https://github.com/Microsoft/ChakraCore/issues/829

**Comment by suwc** [comment]
@boingoing @Microsoft/chakra-es @Microsoft/chakra-developers could you take a look please?

**Comment by tcare** [comment]
Looks good

**Comment by suwc** [comment]
@dotnet-bot test Windows ci_slow_x64_debug Windows 7 ci_dev12_x64_debug please

**Comment by suwc** [comment]
@dotnet-bot test Windows 7 ci_dev12_x64_debug please

**Comment by suwc** [comment]
@dotnet-bot
test Windows 7 ci_dev12_x64_debug please

**Comment by dilijev** [comment]
@mmitche Do you know why the checks I added in a separate branch (**release/1.4-ci**) (see #2326) have been created for this branch? I was hoping to stage that change but not have it applied to all branches yet.
/cc @rajatd 

I'll double check that I don't have a bug in my script.

**Comment by suwc** [comment]
@dilijev thanks. Good to know.

**Comment by dilijev** [comment]
You can now resolve the CI issues as described here: https://github.com/Microsoft/ChakraCore/pull/2332#issuecomment-271029950

**Comment by suwc** [comment]
Merged.
@tcare @dilijev thanks!

**Pull request merged**
