### PR TITLE
WASM.SIMD Use appropriate overloads (matching lane width) of CanonicalizeToBools

### PR DESCRIPTION
**Pull request by Krovatkin**
This should fix failures in SIMD.validation

### CODE REVIEW

**Comment by Krovatkin** [comment]
@Cellule I'll keep an eye on the builds and let you know when the tests pass 
fyi: @arunetm

**Comment by Cellule** [comment]
Curious, do you know why this was okay in ch.exe, but not in jshost.exe ?

**Comment by Krovatkin** [comment]
@Cellule there are no simd.js tests (only asm.js ones) for Bool8x16/Bool16x8.AllTrue in ChakraCore's test suite.

**Comment by Krovatkin** [comment]
@Cellule alright, we're all green here! :-) Could you please help us to merge this?

**Pull request merged**
