### PR TITLE
Simd.js: Refactoring Shuffle/Swizzle helper.

### PR DESCRIPTION
**Pull request by arunetm**
Refactoring the shuffle/swizzle helper methods in SIMDUtils
to avoid the run time issue by using Visual Studio 2013 compiler.

### CODE REVIEW

**Comment by arunetm** [comment]
@dotnet-bot 
test Windows 7 daily_dev12_x86_debug please
test Windows 7 daily_dev12_x86_test please
test Windows 7 daily_dev12_x86_release please
test Windows 7 daily_dev12_x64_test please
test Windows 7 daily_dev12_x64_release please

**Comment by arunetm** [comment]
@MikeHolman Please review this workaround to avoid the runtime issue when compiled with Visual studio 2013 x86test.

**Comment by arunetm** [comment]
@dotnet-bot 
test Windows 7 daily_dev12_x86_debug please

**Comment by arunetm** [comment]
The build "Windows 7 daily_dev12_x86_debug" is failing in the current master.

**Comment by arunetm** [comment]
@dotnet-bot 
test Windows 7 daily_dev12_x86_debug please

**Comment by arunetm** [comment]
@LouisLaf Please review.  This is a workaround for the Win7 daily test failures for build x86_test. Can we use this fix to get around the issue occurring when compiled with VS13?

**Comment by arunetm** [comment]
@dotnet-bot 
test Windows 7 daily_dev12_x86_test please

**Comment by arunetm** [comment]
@LouisLaf This is the workaround for VS2013 bug that we talked about in the meeting. 
Can you please have a look? Thanks..

**Comment by MikeHolman** [comment]
lgtm

**Comment by arunetm** [comment]
Thanks. Signed off again after rebasing before merge.

**Pull request merged**
