### PR TITLE
Fix xplat shared library builds with Intl enabled

### PR DESCRIPTION
**Pull request by jackhorton**

### CODE REVIEW

**Comment by MSLaguana** [comment]
Should this also only apply with using ICU for intl?

**Comment by jackhorton** [comment]
I dont think so, because the -fno-rtti was not conditional on ICU before.

**Comment by jackhorton** [comment]
@obastemur #4094 was supposed to address this ubuntu CI issue, no?

**Comment by obastemur** [comment]
@jackhorton it wasn't directly targeting CI though and what eventually fixed there was more likely a compile time problem.

I didn't want to doit at the first place.. but.. I will add a dummy `forceReset` kinda interface and use that for PAL. So CI will be happy..

**Comment by obastemur** [comment]
Coming in a minute..

**Comment by obastemur** [comment]
@jackhorton lazy init fall short. trying to repro

**Comment by obastemur** [comment]
try cherry-picking 8307ed6f6a5dcf49b5689d5d94e0cbbd2fb8da03

**Comment by obastemur** [comment]
@dotnet-bot test Ubuntu static_ubuntu_linux_test please

**Comment by obastemur** [comment]
Exprimenting on #4274

**Pull request closed without merging**
