### PR TITLE
Merging master to wasm.simd branch.

### PR DESCRIPTION
**Pull request by arunetm**

### CODE REVIEW

**Comment by arunetm** [comment]
@dotnet-bot test Windows x64_debug please

**Comment by arunetm** [comment]
@dotnet-bot test Windowsci_slow_ x64_debug please

**Comment by arunetm** [comment]
@Cellule fyi. Shall we refresh wasm.simd branch with this merge from today's master?

**Comment by Cellule** [comment]
Yeah, the closer the 2 branches are before we open the PR, the better

**Comment by arunetm** [comment]
@Cellule thanks! Can you help to sign off and merge this PR to the wasm.simd branch? I will create a new PR against master right after that.

**Pull request merged**
