### PR TITLE
Test release/1.4-ci (fix #962) (comparative test) [do not merge]

### LINKED ISSUE #962: Copyright Check takes a diff of the current branch versus master instead of the target branch.
It is still correct in the sense that it will get at least all of the files edited by a pull request, but it is checking a much larger set of files than necessary. Would be nice to clean this up.

### PR DESCRIPTION
**Pull request by dilijev**
Testing change to fix #962
Comparative test of PR against current release/1.4
Compare with #2896

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot 
test ci please
test this please

**Comment by dilijev** [comment]
@MSLaguana this PR shows some checks from the master branch. I think this should have been resolved by your commits resulting from #2887:

```
*   [ 4aa0dafa6 ] 2017-05-01 12:46 | jithomso.. | [2.0>master] [1.4>2.0] [1.3>1.4] [1.2>1.3] [MERGE #2887 @MSLaguana] Updating CI script
|\
| *   [ b90206c82 ] 2017-05-01 12:36 | jithomso.. | [1.4>2.0] [1.3>1.4] [1.2>1.3] [MERGE #2887 @MSLaguana] Updating CI script
| |\
| | *   [ 6267a5a77 ] 2017-05-01 12:24 | jithomso.. | [1.3>1.4] [1.2>1.3] [MERGE #2887 @MSLaguana] Updating CI script
| | |\
| | | *   [ e0f8e5ddf ] 2017-05-01 12:14 | jithomso.. | [1.2>1.3] [MERGE #2887 @MSLaguana] Updating CI script
| | | |\
| | | | *   [ 00c44f351 ] 2017-05-01 11:45 | jithomso.. | [MERGE #2887 @MSLaguana] Updating CI script
```

Specifically the merge to `release/1.4` (which should have been a no-op since #2887 backported the CI config from `release/1.4` to `release/1.2`:

```
[ 6267a5a77 ] 2017-05-01 12:24 | jithomso.. | [1.3>1.4] [1.2>1.3] [MERGE #2887 @MSLaguana] Updating CI script
```

And later specifically the merge to master:

```
[ 4aa0dafa6 ] 2017-05-01 12:46 | jithomso.. | [2.0>master] [1.4>2.0] [1.3>1.4] [1.2>1.3] [MERGE #2887 @MSLaguana] Updating CI script
```

**Comment by MSLaguana** [comment]
Yeah I noticed that. The strange thing is the job that I looked it did have the whitelist which should have limited it to PRs targeting master

**Comment by dilijev** [comment]
@MSLaguana my bad, here's the problem:

> dilijev changed the base branch to Microsoft:release/1.4 from Microsoft:master 41 minutes ago

**Pull request closed without merging**
