### PR TITLE
ARM64: Avoid inserting NOPs in function prologues

### PR DESCRIPTION
**Pull request by Penguinwizzard**

### CODE REVIEW

**Comment by aaronsgiles** [comment]
Why do we generate this in the first place?

**Comment by agarwal-sandeep** [comment]
GenerateStackProbe seems to be inserting NOPs by calling Security::InsertRandomFunctionPad

---
In reply to: [346188698](https://github.com/Microsoft/ChakraCore/pull/4296#issuecomment-346188698) [](ancestors = 346188698)

**Comment by agarwal-sandeep** [comment]
@Penguinwizzard if NOP is infact inserted in GenerateStackProbe then we can remove that code as it is not required for ARM64. Talked to Louis and he said it was needed for ARM32 for some kind of entryPoint alignment and won't be required for ARM64.

**Comment by Penguinwizzard** [comment]
I've updated the commit to now remove the line calling out to insert NOPs inside GenerateStackProbe.

**Pull request merged**
