### PR TITLE
refactor, avoid extra copying of ObjTypeSpecInfo

### PR DESCRIPTION
**Pull request by MikeHolman**
After OOP JIT change, we were doing extra copying for ObjTypeSpecInfo, but ObjTypeSpecInfo is only used for JIT and lifetime is that of the workitem, so we don't need to copy this and can lay it out such that RPC can directly marshal it..

This is giving me about 2% perf win in OOP JIT Typescript, everything else is within noise range.

### CODE REVIEW

**Comment by dilijev** [comment]
@MikeHolman Any update here?

**Comment by MikeHolman** [comment]
@dilijev I still want to merge this. But I never got a review.

**Comment by rajatd** [comment]
:shipit:

**Comment by MikeHolman** [comment]
@dotnet-bot test  Windows x64_release

**Pull request merged**
