### PR TITLE
MemCopy Native Float Arrays

### PR DESCRIPTION
**Pull request by Cellule**
Enable Native Float arrays for memcopy

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/794)

### CODE REVIEW

**Comment by Cellule** [comment]
@LouisLaf @pleath @rajatd Can on of you guys review this please ?

**Comment by rajatd** [comment]
Do you know if there were strong reasons to not have it enabled for float arrays?

**Comment by Cellule** [comment]
Simply that when I enabled it for memset, I hadn't done any testing for memcopy so I held off doing it for memcopy.
Apparently there was a bug with the check that prevented memcopy for native float arrays (it would produce memcopy then bailout because it wasn't supported).
I considered reinforcing the check to avoid this issue, but I decided it was actually easier to enable it. I tested it some more and determined it was ok to do a memcopy on native float arrays.

**Comment by rajatd** [comment]
:+1:

**Pull request merged**
