### PR TITLE
Bugfix in Intl

### PR DESCRIPTION
**Pull request by kunalspathak**
See [8267396](https://microsoft.visualstudio.com//defaultcollection/OS/_workItems?_a=edit&id=8267396&triage=true).

For certain APIs, Windows.globalization can return `nullptr` result for `HSTRING` . We wrap it in `AutoHSTRING` and when we retrieve the underlying value, we hit assert because the underlying value was `nullptr`. Modified to return error code if we get nullptr from windows.globalization.

### CODE REVIEW

**Comment by kunalspathak** [comment]
@digitalinfinity , can you help with the review?

**Comment by digitalinfinity** [comment]
:shipit:

**Comment by kunalspathak** [comment]
@dotnet-bot test osx_osx_debug_static please.

**Comment by kunalspathak** [comment]
@dotnet-bot test osx_osx_debug_static

**Comment by kunalspathak** [comment]
@dotnet-bot please test OSX osx_osx_debug_static

**Pull request merged**
