### PR TITLE
xplat: protect CC from un-reasonable stack limits

### PR DESCRIPTION
**Pull request by obastemur**

### CODE REVIEW

**Comment by kfarnung** [comment]
I'm testing this out on my Ubuntu 14.04 VM with GNU make 3.81.  I'll let you know.

**Comment by kfarnung** [comment]
@obastemur Are you planning to land this change in https://github.com/Microsoft/ChakraCore/tree/release/1.5?

**Comment by digitalinfinity** [comment]
@obastemur yes, please retarget this change from release/2.0 to release/1.5.

**Comment by obastemur** [comment]
@kfarnung @digitalinfinity Thanks for the review

**Comment by digitalinfinity** [comment]
@obastemur as we talked about offline- you can retarget this change to master instead of release/1.5

**Comment by obastemur** [comment]
Yep, I will re-target JsIdle PR to master.

**Comment by digitalinfinity** [comment]
Ah yeah, sorry, placed my comment on the wrong PR 😄

**Pull request merged**
