### PR TITLE
remove es7builtins flag from a test

### PR DESCRIPTION
**Pull request by akroshg**

### CODE REVIEW

**Comment by akroshg** [comment]
@dotnet-bot test slow tests please

**Comment by akroshg** [comment]
@dotnet-bot test dev12 tests please

**Comment by akroshg** [comment]
This should fix #1260

**Comment by akroshg** [comment]
@dotnet-bot test slow tests please

**Comment by akroshg** [comment]
@dotnet-bot test dev12 tests please

**Comment by akroshg** [comment]
Yay! everything is passing - I am going to merge this in.

**Comment by dilijev** [comment]
@akroshg Excellent, thanks!

**Pull request merged**
