### PR TITLE
Enable early reference errors for most assignments to invalid LHS

### PR DESCRIPTION
**Pull request by pleath**
Leave early reference error on assignment to function call result disabled because of compat concerns. That early error can be enabled separately via command line.

### CODE REVIEW

**Comment by pleath** [comment]
Fixes https://github.com/Microsoft/ChakraCore/issues/3242

**Comment by fatcerberus** [comment]
> Leave early reference error on assignment to function call result disabled because of compat concerns.

By this I assume you mean something like:
```js
func() = 812;
```

How is this a compat concern?  I didn't think this was ever a legal construct.

**Comment by Cellule** [comment]
@fatcerberus As per JavaScript spec, no I don't think it was ever legal, but we have been accepting such construct for a long time and I think some website actually relies on it for some reason.

**Comment by pleath** [comment]
IE supported this syntax for interacting with things like VBScript arrays. It’s still out there, and though Chakra will raise a runtime exception if it’s asked to execute such a statement, we can’t safely throw an early error without breaking pages that work on Edge today.

**Comment by pleath** [comment]
Added changes to deal with destructuring, not throwing on legal cases and continuing to throw early on assignment-to-call-result cases within patterns.

**Pull request merged**
