### PR TITLE
Fixes `DataView` toString

### PR DESCRIPTION
**Pull request by obastemur**
See https://github.com/Microsoft/ChakraCore/issues/656

### CODE REVIEW

**Comment by dilijev** [comment]
As @nicolo-ribaudo mentioned, these work correctly when -ES6ToStringTag is specified. I think this is redundant work.

**Comment by obastemur** [comment]
@dilijev  I would approach that a separate cleanup + change in global config PR (IMO there is a room for better perf. there)

Feel free to merge this or close.

**Comment by ianwjhalliday** [comment]
This is legit, we should take this.  Thanks @obastemur.

**Comment by dilijev** [comment]
@obastemur sorry for the confusion. Thanks :)

**Comment by ianwjhalliday** [comment]
Looks great, thanks @obastemur.  Merging.

**Comment by ianwjhalliday** [comment]
Oh whoops, @dilijev just reminded me that this PR is not targeting the release/1.2 branch.

@obastemur can you close this PR and reopen against release/1.2 please?

**Pull request closed without merging**
