### PR TITLE
Change version number to 1.10

### PR DESCRIPTION
**Pull request by boingoing**
Bump up the ChakraCore/master version number to 1.10 after cutting release/1.9 branch.

### CODE REVIEW

**Comment by fatcerberus** [comment]
I'm confused by the release branches - the latest release is apparently 1.7.6, but there are already 1.8 and 1.9 release branches?  Are the release branches considered stable, or...?

**Comment by jackhorton** [comment]
For the most part, even master is stable, in so far as its expected to Just Work for all scenarios. Our release branches are really just a convenience for us internally -- everything in 1.8 is going into the next release of windows, everything in 1.9 is going into node-chakracore but not windows, and master is everything going into the next-next release of those two main targets. The latest "stable release" is 1.7.6 because thats the last one we have created github release notes for. In a way, its almost like the latest stable release can be thought of as the oldest version of chakracore that has all security fixes applied. Its a confusing structure for sure, but thats how its been done for the last few release branches. Not sure who the right person is to ask about clarifying this situation.

**Comment by fatcerberus** [comment]
> For the most part, even master is stable, in so far as its expected to Just Work for all scenarios.

That makes sense; it's one of the benefits of having such a comprehensive CI suite.

That said, ChakraCore development is quite rapid and I find myself wanting to update to a newer master more often than I'd prefer, especially as I have to commit the binaries to my own repository (the NuGet build is too old and there is no official CC package in Ubuntu or other distros).  So it would be a great to have a more stable baseline, and unfortunately 1.7.x no longer has all the features I need. 🙁

**Comment by jackhorton** [comment]
> unfortunately 1.7.x no longer has all the features I need.

Just to confirm, did we regress the 1.7 branch somehow? Or do you simply need more features in your own application now than before?

@MSLaguana and @dilijev can probably speak more to the NuGet issue, but I find that odd since we are all doing our day to day work in VS 2017. With that being said, keep in mind that if we offered an apt package, it would likely be stuck to a specific version, short of offering our own feed like VS Code.

**Comment by fatcerberus** [comment]
No regression, 1.7 just doesn't have some more recent additions that I need, notably `JsModuleHostInfo_Url` (#4080) as well as a couple bug fixes for, e.g. dynamic import (#3934).  I'll also need #4551 once it's merged.

Regarding NuGet, I was wrong about it being very old (it's 1.7.6, not 1.4 like I thought), however it requires the v140 (VS 2015) toolchain, while my projects use the v141_xp toolchain.  The package is not compatible.  The response I got to #3786 was essentially that there were no plans to support other toolchains than v140 so I either switch my project to v140 or else build CC myself.  Looking at the issue again, it seems that PRs are welcome for #3786 however I have no experience with making NuGet packages.

**Comment by boingoing** [comment]
@dotnet-bot test OSX static_osx_osx_debug please

**Pull request merged**
