### PR TITLE
Merge Master to Linux

### PR DESCRIPTION
**Pull request by obastemur**

### CODE REVIEW

**Comment by obastemur** [comment]
Merging straight from `master` to `linux` with no change and Windows test fails ?

**Comment by jianchun** [comment]
@agarwal-sandeep  looks one test failure debugger related?

**Comment by agarwal-sandeep** [comment]
@jianchun @obastemur This test was moved from full to core repo. Seems to be passing in master. I will investigate.

**Comment by obastemur** [comment]
Sent #1526 also. We may not need to merge Master to Linux at all.

**Comment by obastemur** [comment]
Link for the previous fail http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/x64_debug_prtest/2197/console

**Comment by agarwal-sandeep** [comment]
@obastemur it seems "Platform" object is added on WScript in Linux branch and it shows up under debugger. Please update the test\DebuggerCommon\step_in_from_interpreted_function_attach.js.dbg.baseline from you merge branch.

**Comment by dilijev** [comment]
@obastemur Since master's build health checks are all green, I'd prefer merging master into linux before taking the linux into master merge. To keep the commit history sane, it's probably better if the master->linux merge is finished first and then the result is merged into master.

Following this merge, it might be a good time to start working on xplat changes directly in the master branch.

**Comment by obastemur** [comment]
> To keep the commit history sane, it's probably better if the master->linux merge is finished first and then the result is merged into master.

How it is different then separate branch `mmerge_10` is merging into master?

**Pull request closed without merging**
