### PR TITLE
Readme: Add link to wiki for pre-built binaries.

### PR DESCRIPTION
**Pull request by dilijev**

### CODE REVIEW

**Comment by liminzhu** [comment]
LGTM. Would link to a wiki for getting binaries instead once xplat binaries are online but it's fine for now.

https://github.com/Microsoft/ChakraCore-wiki/pull/34/files

**Comment by dilijev** [comment]
Maybe we should create a single Wiki page now, to refer to all sources of pre-built binaries, change this PR to point to that page, and update that page down the line to refer to new sources as they become officially available?

**Comment by liminzhu** [comment]
Sounds good. Let me change https://github.com/Microsoft/ChakraCore-wiki/pull/34 and we can merge that one first.

**Comment by dilijev** [comment]
@liminzhu Updated.

**Comment by liminzhu** [comment]
Minor nitpicking. This may read better.

> Alternatively, see [Getting ChakraCore binaries](https://github.com/Microsoft/ChakraCore/wiki/Getting-ChakraCore-binaries) for pre-built ChakraCore binaries.

**Comment by dilijev** [comment]
I agree, that does sound better.

**Pull request merged**
