### PR TITLE
LICENSE: Remove project name from line 1 to fix auto-detection of MIT License in GitHub.

### LINKED ISSUE #4340: MIT License no longer automatically detected
See https://github.com/Microsoft/vscode

image

We used to have the MIT License automatically detected in our repo, and now it is not.

image

It seems their automatic detection algorithm may have changed. It could be the case that our license differs enough from the basic MIT License template that it now cannot be detected.

Compare vscode's License with ours:

https://github.com/Microsoft/vscode/blob/master/LICENSE.txt

https://github.com/Microsoft/ChakraCore/blob/master/LICENSE.txt

Possible issues:

* name of project appears on [line 1](https://github.com/Microsoft/ChakraCore/blob/master/LICENSE.txt#L1) instead of `MIT License`.
* [Line 2](https://github.com/Microsoft/ChakraCore/blob/master/LICENSE.txt#L2) reads `The MIT License (MIT)` / compare with [vscode line 1](https://github.com/Microsoft/vscode/blob/master/LICENSE.txt#L1) `MIT License`
* [Line 4](https://github.com/Microsoft/ChakraCore/blob/master/LICENSE.txt#L4) does not include a copyright year.

### PR DESCRIPTION
**Pull request by dilijev**
Fixes #4340

### CODE REVIEW

**Comment by dilijev** [comment]
Demonstration of the fix: compare license files between ChakraCore and my repo:

https://github.com/Microsoft/ChakraCore/blob/master/LICENSE.txt
https://github.com/dilijev/ChakraCore/blob/master/LICENSE.txt

**Comment by dilijev** [comment]
This change is approved by legal ✔️

**Comment by MSLaguana** [comment]
@dotnet-bot test OSX static_osx_osx_debug please

**Comment by dilijev** [comment]
ChakraHub doesn't like source branches and target branches names to match. Replacing this PR with #4343

**Pull request closed without merging**
