### PR TITLE
Add dotnet-bot help job.

### PR DESCRIPTION
**Pull request by dilijev**

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by dilijev** [comment]
@mmitche FYI

**Comment by mmitche** [comment]
LGTM

**Comment by mmitche** [comment]
@dotnet-bot help

**Comment by mmitche** [comment]
Well that's interesting.  I wonder why it didn't register the rest of the jobs.

**Comment by mmitche** [comment]
Ahh because they're created in the master branch.  Okay i'll have to solve that issue next week.

**Comment by mmitche** [comment]
ANways, still LGTM

**Comment by dilijev** [comment]
@mmitche Okay so we'll see the full set in the help message in master but not in release/1.2 and release/1.3, etc.?

**Comment by dilijev** [comment]
@dotnet-bot test this please

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by dilijev** [comment]
@dotnet-bot help

**Comment by dilijev** [comment]
@dotnet-bot help

**Comment by dilijev** [comment]
@mmitche How does testing the help message work? Should it work after I triggered a CI test?

**Comment by mmitche** [comment]
@dilijev I just triggered it manually there.  It works like any other CI job (except all it does it post to GitHub) and will work once merged.

I'm working on a way to get the help message to display jobs that aren't defined in this netci.groovy

**Pull request merged**
