### PR TITLE
Implement stage 3 proposal globalThis

### PR DESCRIPTION
**Pull request by rhuanjl**
This PR implements the stage 3 proposal globalThis.

1. Actual implementation is 2 lines of code
2. I've added a default enabled flag so it can be flagged off if ever necessary
3. I've added a few tests which I think should be sufficient
4. The large size of the diff is only due to it needing a byte code regen

cc: @ljharb @pleath 

closes: #1658

### CODE REVIEW

**Comment by fatcerberus** [comment]
Hooray! :tada:

Going off on a tangent, I find the name of `globalThis` to be awkward; I understand why it was chosen (`global`, the best option, being dead in the water thanks to web compat), but a camelcased (pseudo)keyword is weird and it’s also somewhat ambiguous—as in strict mode (and modules), `this` is actually undefined when used in the global scope.

**Comment by fatcerberus** [comment]
Thanks, yeah, I understand the challenges around the proposal (I was very sad when `global` was ruled out), it’s mostly the ambiguity that gets to me in the end - since this is largely provided specifically so that strict-mode code can access the global easily (per the linked document), “global this” is a bit misleading - since the *actual* “global this” in strict mode is `undefined`.

**Comment by ljharb** [comment]
It'd be great to get this merged :-)

**Comment by boingoing** [comment]
Hi @rhuanjl, would you mind rebasing this one? I will help merge it.

**Comment by rhuanjl** [comment]
I've noticed that there is an agenda item for the TC39 meeting due to be held this week to discuss changing the name of globalThis, should we hold off on getting this merged until after that discussion?

https://github.com/tc39/agendas/pull/511/files

@ljharb

**Comment by rhuanjl** [comment]
@ljharb I can see (from it being crossed out on the agenda) that the name change discussion has taken place - can you tell us if the name is being changed/is likely to be?

**Comment by ljharb** [comment]
@rhuanjl there was not consensus for any change, no.

**Comment by boingoing** [comment]
@rhuanjl Yup, I'll run the change through our internal test suites and merge it when it's green.

**Comment by boingoing** [comment]
@rhuanjl Took the liberty of rebasing and adding a new bytecode GUID into your branch. Hope you don't mind. Landed via 5d83d3e81

Thanks very much for the submission. Always nice to see your contributions.

**Pull request merged**
