### PR TITLE
Fix some tabs and trailing whitespace that has creeped in; add Tab Check

### PR DESCRIPTION
**Pull request by dilijev**
Add a new Jenkins task to detect when tabs are introduced into the source code.

There are very few instances of tabs being introduced (always unintentionally in the case of C++ source) and it seems to bother enough people that it would be nice to detect it before it is checked in.

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by dilijev** [comment]
@tcare @digitalinfinity Thoughts?

**Comment by tcare** [comment]
Sounds good to me

**Comment by dilijev** [comment]
@mmitche is the feature that lets us try out new tests from a PR available yet, or should I just merge this?

**Comment by mmitche** [comment]
@dilijev Not yet.  The base that the implementation needs to be done on is in place, but beyond that not available.

You can manually enable and run the new jobs if you'd like.

**Pull request merged**
