### PR TITLE
Don't fail assertions on jumps to helpers that were inserted as airlocks

### PR DESCRIPTION
**Pull request by sethbrenith**

### CODE REVIEW

**Comment by sethbrenith** [comment]
@dotnet-bot 
test OSX _no_jit_shared_osx_osx_test please
test OSX static_osx_osx_debug please
test OSX static_osx_osx_release please

**Comment by sethbrenith** [comment]
@dotnet-bot test OSX static_osx_osx_debug please

**Comment by sethbrenith** [comment]
@dotnet-bot test OSX static_osx_osx_debug please

**Comment by rajatd** [comment]
@sethbrenith do you know why the fallthrough to helper block wasn't triggering op-helper asserts?

**Comment by sethbrenith** [comment]
I don't see any relevant check for that case. The label case in DbCheckPostLower only applies to non-helper labels, and the branch instructions pass their checks before the airlock is inserted: the JNE targets a helper, and the JMP-to-helper immediately follows a JNE.

---
In reply to: [378083746](https://github.com/Microsoft/ChakraCore/pull/4911#issuecomment-378083746) [](ancestors = 378083746)

**Comment by sethbrenith** [comment]
@rajatd Do you have suggestions of other changes I should make for that case?

---
In reply to: [378328214](https://github.com/Microsoft/ChakraCore/pull/4911#issuecomment-378328214) [](ancestors = 378328214,378083746)

**Comment by sethbrenith** [comment]
@LouisLaf Do you have advice for the right solution that deals with these CMOV instructions without creating ugly fallthrough-to-helper cases? Derek mentioned that we might want to move it into the helper or give it its own block when flipping a JE instruction.

**Pull request closed without merging**
