### PR TITLE
Put short flags first in help message so everything lines up better and they are easier to discover.

### PR DESCRIPTION
**Pull request by dilijev**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/993)

### CODE REVIEW

**Comment by Cellule** [comment]
:+1:

**Comment by dilijev** [comment]
@dotnet-bot test this please

**Comment by dilijev** [comment]
@jianchun @digitalinfinity FYI

**Comment by dilijev** [comment]
ping @jianchun @digitalinfinity

**Comment by digitalinfinity** [comment]
LGTM

**Comment by jianchun** [comment]
:shipit:

**Comment by dilijev** [comment]
Thanks @digitalinfinity @jianchun @Cellule. Merging

**Pull request merged**
