### PR TITLE
Cmake Automatic Configuration

### PR DESCRIPTION
**Pull request by kphillisjr**
This is a rework for the ChakraCore automatic configuration. This is two patches that will allow many developers to quickly start developing using ChakraCore. I will be pushing a rework of the patches to the ChakraCore examples later, however the general process for this is as follows:

An example of how to use this is as follows...
```CMake
# include Auto-Configure macro.
include("${CMAKE_SOURCE_DIR}/ChakraCore/ChakraAutoConfigure.cmake")
# Configure ChakraCore:
CHAKRACORE_AUTOCONFIGURE()
add_subdirectory(ChakraCore)
add_custom_target(CopyChakraHeaders ALL
	COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_BINARY_DIR}/include"
	COMMAND ${CMAKE_COMMAND} -E copy_if_different
		"${CMAKE_SOURCE_DIR}/ChakraCore/lib/Jsrt/ChakraCore.h"
		"${CMAKE_BINARY_DIR}/include"
	COMMAND ${CMAKE_COMMAND} -E copy_if_different
		"${CMAKE_SOURCE_DIR}/ChakraCore/lib/Jsrt/ChakraCommon.h"
		"${CMAKE_BINARY_DIR}/include"
	COMMAND ${CMAKE_COMMAND} -E copy_if_different
		"${CMAKE_SOURCE_DIR}/ChakraCore/lib/Jsrt/ChakraCommonWindows.h"
		"${CMAKE_BINARY_DIR}/include"
	COMMAND ${CMAKE_COMMAND} -E copy_if_different
		"${CMAKE_SOURCE_DIR}/ChakraCore/lib/Jsrt/ChakraDebug.h"
		"${CMAKE_BINARY_DIR}/include"
)
# enable C++11
add_executable(ChakraSample sample.cpp)
set_target_properties(ChakraSample PROPERTIES COMPILE_FLAGS "-std=c++11")
# link to ChakraCore.
target_link_libraries(ChakraSample ChakraCore)
# Make sure Chakra Core Headers are in a location that is easy to use.
add_dependencies(ChakraSample CopyChakraHeaders)
# Actually include the headers.
target_include_directories(ChakraSample PUBLIC "${CMAKE_BINARY_DIR}/include")
```

### CODE REVIEW

**Comment by kphillisjr** [comment]
@dilijev and @obastemur, This does not include the major commit that resolves direct linking only to the ChakraCore shared library. The next commit provides a usable solution to issue #1811, but it breaks the ch utility in the process. This change is the following patch ( https://github.com/kphillisjr/ChakraCore/commit/75182f3e50280ac154d9397ba381bd4272ecaee9 ), and to test this change on top of this pull request, run the following commands...
```sh
#Download and get the right ChakraCore Source Tree.
git clone https://github.com/kphillisjr/ChakraCore.git
cd ChakraCore
git checkout fix_issue_1811
cd ..

# Download and get the correct Chakra Samples tree.
git clone https://github.com/kphillisjr/Chakra-Samples.git
cd Chakra-Samples
git checkout samples_cmake_v3
ln -s ../ChakraCore .
# Use the build script... It's a copy of what is in ChakraCore anyways.
./build.sh
# This BuildLinux/Debug will contain ChakraHelloWorld  and ChakraOpenGLEngine 
# that link directly  to libChakraCore. Also both of these examples are
# functioning correctly.
```

**Comment by obastemur** [comment]
https://github.com/Microsoft/ChakraCore/issues/2575#issuecomment-283128713

**Pull request closed without merging**
