### PR TITLE
Merge from linux into master

### PR DESCRIPTION
**Pull request by digitalinfinity**
Payload:

Several enhancements to build.sh and runtests.py
Updates to CMakeLists
Update to jenkins CI to run unit tests as part of CI builds
Support for ch to be statically linked with ChakraCore libraries on Linux/OS X
Updates to JSRT APIs to support Utf8 (ch uses only the xplat API surface of Jsrt)
Props files for building ChakraCore with VC++ clang frontend on Windows
Cleanup of __declspec(noinline)
Protected some more code under #ifdef ENABLE_SIMDJS
Platform Agnostic implementation of DateTime related functions
Add support for "Baseline" mode while running unit tests to reduce noise in tests that have platform-specific offset outputs
Several bug fixes- unit tests are now clean!

### CODE REVIEW

**Comment by digitalinfinity** [comment]
This payload also has some commits from our external friends- thanks @xanlpz @tadeuzagallo for your contributions, we really appreciate it!

**Comment by dilijev** [comment]
@dotnet-bot test dev12 tests please

@digitalinfinity I'm asking for this because of the failure on https://github.com/Microsoft/ChakraCore/wiki/Build-Status-%28linux%29#legacy-builds -- it's possible this is fixed after the merge, but I'm just making sure there isn't something that needs to be fixed before merging this.

**Comment by dilijev** [comment]
@digitalinfinity tests look good. I guess you should take a merge from `master` to `linux` to unbreak the tests in `linux` now.

**Comment by digitalinfinity** [comment]
@dotnet-bot test dev12 tests please

**Comment by digitalinfinity** [comment]
@dotnet-bot test dev12 tests please

**Comment by digitalinfinity** [comment]
@dotnet-bot test Windows x86 debug please

**Comment by digitalinfinity** [comment]
@dotnet-bot test Windows x86_debug please

**Comment by dilijev** [comment]
@dotnet-bot test Windows x86_release please

**Comment by dilijev** [comment]
@digitalinfinity gogogo

**Pull request merged**
