### PR TITLE
SIMD.js - unpin 1-byte opnds to BL

### PR DESCRIPTION
**Pull request by nmostafa**
This change removes pinning of byte operands to R/EBX in Simd128 lowerer, and makes a copy of the original opnd in Opnd::UseWithNewType()

We initially had this:
```
IR::RegOpnd *reg2 = IR::RegOpnd::New(TyInt32, m_func);
        IR::RegOpnd * tmp = IR::RegOpnd::New(TyInt8, m_func);
        instr->InsertBefore(IR::Instr::New(Js::OpCode::MOV, tmp->UseWithNewType(TyInt32, m_func), reg2, m_func));

        instr->InsertBefore(IR::Instr::New(Js::OpCode::MOVSX, reg2, tmp, m_func));
```

One would expect tmp->UseWithNewType to create a copy of the opnd, but instead it checks if the opnd is in use by an instruction, and if not, it will use it and change its type (tmp will be TyInt32 afterwards). That makes the MOVSX use an TyInt32 copy of tmp causing the regAlloc to not restrict register assignment to byteable regs. 

@LouisLaf , can you take a look ?

### CODE REVIEW

**Comment by LouisLaf** [comment]
I never liked that API, but don't really like your modification either, as we will now create unnecessary copies for opnds that are not being used.
The common case usage for it is:
opnd = newOpnd(type1);
use(opnd);
opnd2 = opnd->UseWithNewType(type2);
use(opnd2);

So I think ideally, the API should be called CopyWithNewType(), and the API should assert that the opnd is not InUse().

This will require you change you code pattern in SYMD.

Nagy, do you mind making this API change?

Thanks.

**Comment by nmostafa** [comment]
I will take care of it. I suggested the assertion in #727.

**Comment by nmostafa** [comment]
@LouisLaf 
> So I think ideally, the API should be called CopyWithNewType(), and the API should assert that the opnd is not InUse().

I assume you mean assert that the opnd _is InUse()_ ? 
It seems existing uses of this API in the lowerer can call it on the first use of the operand. For example, see InsertMove below. It doesn't know if src is used.

The simplest fix here is to keep the API as-is, and I can fix the SIMD lowerer to not use the API (legalizing MOV TyInt8, TyInt32 should be sufficient). 

```C++
IR::Instr *Lowerer::InsertMove(IR::Opnd *dst, IR::Opnd *src, IR::Instr *const insertBeforeInstr, bool generateWriteBarrier)
{
...
    if(TySize[dst->GetType()] < TySize[src->GetType()])
    {
        src = src->UseWithNewType(dst->GetType(), func);
    }
```

**Comment by LouisLaf** [comment]
You're right.  This is probably the better choice.

**Comment by nmostafa** [comment]
@LouisLaf , if it looks good, please sign off. Thanks

**Comment by nmostafa** [comment]
@abchatra , I will merge this into release/1.2. There is no repro for this since this is just a more appropriate fix for a previous jshost bug.

**Comment by abchatra** [comment]
Sure go ahead.

**Pull request merged**
