### PR TITLE
Add RegExp.prototype.flags

### PR DESCRIPTION
**Pull request by goyakin**
This change adds the `flags` property to the RegExp prototype, but it doesn't complete all its uses. The missing pieces are:

  * RegExp constructor doesn't use the `flags` property at all since this depends on `Symbol.match`, which Chakra doesn't currently support.
  * `RegExp.prototype.toString` gets the `flags` property only if `this` is a RegExp object, but it should actually work with any `Object`. `toString` needs to also get the `source` property via its accessor, so I'll have another PR updating the `toString` implementation for both.
  * `RegExp.prototype[@@split]` which Chakra doesn't currently implement.

### CODE REVIEW

**Comment by goyakin** [comment]
@kunalspathak & @abchatra, could you take a look?

**Comment by ljharb** [comment]
Is there any reason you couldn't add constructor support for now for native RegExp objects, even without `Symbol.match` support?

**Comment by goyakin** [comment]
@ljharb, according to the Step 5 of the [RegExp constructor](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-regexp-pattern-flags), it isn't supposed to get the `flags` property, but it should instead use the `[[OriginalFlags]]` internal support.

I had an offline discussion with @bterlson about whether that step makes sense and our conclusion was that, yes, it does.

**Comment by ljharb** [comment]
Awesome :-) that way support will be complete for native RegExp objects, and support for `Symbol.match`-branded objects can come later with that symbol.

**Comment by kunalspathak** [comment]
LGTM.

**Pull request merged**
