### PR TITLE
cross-platform: xcode project support

### PR DESCRIPTION
**Pull request by obastemur**
disclaimer: xcode project support should be considered as a community feature.
At the moment, it is not officially supported.

Implements xcode project generation using ChakraCore's build script and fixes compile
time issues with xcode.

### CODE REVIEW

**Comment by digitalinfinity** [comment]
LGTM

**Comment by mattzeunert** [comment]
Could this be added to the `Building ChakraCore` page, even though it's not "officially supported"?
 This is awesome and would have saved me so much time if I had found out about it sooner!

**Comment by obastemur** [comment]
@liminzhu what do you think?

**Comment by liminzhu** [comment]
Why not :) Want to make a PR to [here](https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore#os-x)?

**Comment by mattzeunert** [comment]
Yeah will do next week. Are there any options I can leave out? I tried removing some but got a `libChakraCore.dylib` not found warning.

```./build.sh --xcode --icu=/usr/local/opt/icu4c/include --test-build --static```

**Comment by obastemur** [comment]
@mattzeunert strictly designed for `debug` `static` (most dev friendly xplat build of CC)

**Pull request merged**
