### PR TITLE
Set isInlined in InlineGetterSetter

### PR DESCRIPTION
**Pull request by rajatd**
InlineGetterSetter method was missing the set of boolean isInlined. Added that

### CODE REVIEW

**Comment by rajatd** [comment]
@satheeshravi , could you take a look?

**Comment by dilijev** [comment]
@rajatd Tab Check is now ported to release/1.3. When you rebase, the check will pass.

**Comment by dilijev** [comment]
I guess I triggered it. It's passing now.

**Comment by satheeshravi** [comment]
:shipit:

**Comment by rajatd** [comment]
Thanks, @satheeshravi , @dilijev

**Pull request merged**
