### PR TITLE
Added year to the license file

### PR DESCRIPTION
**Pull request by azkarmoulana**
Added 2018 as the year

### CODE REVIEW

**Comment by dilijev** [comment]
I believe this was a deliberate decision, advised by the Legal department for OSS projects. @liminzhu do you recall or can you follow up?

**Comment by liminzhu** [comment]
I will have to follow up on this. @digitalinfinity do you remember anything? Or I can check with Ed/G/lawyers.

**Comment by digitalinfinity** [comment]
I don't remember, sorry. Please check with our lawyers

**Comment by dilijev** [comment]
Guidance from the Legal department is to not put a copyright year on source code.

@azkarmoulana thanks for bringing this to our attention so we could double-check our policies.

**Pull request closed without merging**
