### PR TITLE
Update tests to use the new WebAssembly api and remove Wasm object from JavascriptLibrary

### LINKED ISSUE #1834: WASM - Remove old Wasm APIs
We should delete the Wasm object before release once we have switched testing to use new WebAssembly APIs

### PR DESCRIPTION
**Pull request by meg-gupta**
Closes #1834

### CODE REVIEW

**Comment by meg-gupta** [comment]
@Cellule Can you please review ?

**Comment by Cellule** [comment]
Also need to remove
```
// TODO: remove old Wasm object
ENTRY(Wasm)
ENTRY(instantiateModule)
ENTRY(experimentalVersion)
```
in 
`lib\Runtime\Base\JnDirectFields.h`

You will probably have to regenerate bytecode headers after that

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/microsoft/chakracore/1912#-KVgIFUexMI52jeeAB9N:-KVgIFUexMI52jeeAB9O:b-y3ji8o) (no related file):*
Make sure to do a build in ChakraFull to see if there are any baselines that needs updating.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1912#-:-KVgHDfrgLHeK4HuXOJ0:b91amzi)*

**Comment by Cellule** [comment]
You need to regenerate ByteCode Headers

**Comment by Cellule** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/microsoft/chakracore/1912#-KVgIFUexMI52jeeAB9N:-KVgZc2_hVb5j3_AocQ-:bntpkcg) (no related file):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Make sure to do a build in ChakraFull to see if there are any baselines that needs updating.
</details>
Oh I forgot, you also need to remove the relevant entry function in WasmLibrary.cpp which are
```cpp
        static Var instantiateModule(RecyclableObject* function, CallInfo callInfo, ...);
        static const unsigned int experimentalVersion;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1912)*

**Comment by Cellule** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1912#-:-KW-cFzPbi82hhNMjuje:bnfp4nl)*

**Comment by Cellule** [comment]
Reviewed 3 of 4 files at r5.
Review status: 24 of 25 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/WasmSpec/spec.js, line 127 at r5](https://reviewable.io:443/reviews/microsoft/chakracore/1912#-KW0mpQtih88llRVEFdO:-KW0mpQtih88llRVEFdP:biczyw2) ([raw file](https://github.com/microsoft/chakracore/blob/c37e3a75264410f40c6a720d172fad256d0318a1/test/WasmSpec/spec.js#L127)):*
> ```JavaScript
>   var memory = null;
>   var u8a = new Uint8Array(a);
>   var module = WebAssembly.instantiateModule(u8a, registry);
> ```

I suppose this was a merge conflict.
You should change it to
```js
  var mod = new WebAssembly.Module(u8a);
  var module = new WebAssembly.Instance(mod, registry);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1912)*

**Comment by meg-gupta** [comment]
Thanks, fixed and merged.

**Pull request merged**
