### PR TITLE
sequences for f32/f64_convert_u/s/i32/i64 on x86-x64 

### PR DESCRIPTION
**Pull request by Krovatkin**
This PR implements fastpath sequences for f32/f64_convert_u/s/i32/i64 on x86-x64

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1992)

### CODE REVIEW

**Comment by Krovatkin** [comment]
@Cellule @MikeHolman not sure if there's any time left for this one.

**Comment by Cellule** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/Backend/LowerMDShared.cpp, line 7972 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1992#-KWKcPoopjO8bBp42GDM:-KWKcPopJkskKtNdS8qL:baixfm4) ([raw file](https://github.com/microsoft/chakracore/blob/4176e534e5a1caf122bac83f1311e93d600cf304/lib/Backend/LowerMDShared.cpp#L7972)):*
> ```cpp
> {
>     EmitInt64toFloatRec(dst, src, instr, false);
>     instr->UnlinkDst();
> ```

I don't think it's necessary to unlink the source/dst knowing the instr will get removed

---

*[lib/Backend/LowerMDShared.cpp, line 8011 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1992#-KWKf0AHbWHF93OZpjHz:-KWKf0AHbWHF93OZpjI-:bey7cho) ([raw file](https://github.com/microsoft/chakracore/blob/4176e534e5a1caf122bac83f1311e93d600cf304/lib/Backend/LowerMDShared.cpp#L8011)):*
> ```cpp
>     if (src->IsUnsigned() && !recursive)
>     {
>         EmitInt64toFloatRec(dst, src, instr, true);
> ```

The recursion is not necessary
You can call `instr->InsertBefore(IR::Instr::New(Js::OpCode::CVTSI2SD, dst, src, this->m_func));` before the unsigned check and remove the else block.

---

*[lib/Backend/LowerMDShared.cpp, line 8013 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1992#-KWKhz7Dy9VjLeXVGSLX:-KWKhz7Dy9VjLeXVGSLY:bxflkz5) ([raw file](https://github.com/microsoft/chakracore/blob/4176e534e5a1caf122bac83f1311e93d600cf304/lib/Backend/LowerMDShared.cpp#L8013)):*
> ```cpp
>         EmitInt64toFloatRec(dst, src, instr, true);
>         IR::RegOpnd * highestBitOpnd = IR::RegOpnd::New(TyInt64, this->m_func);
>         IR::Instr* instrNew = IR::Instr::New(Js::OpCode::SHR, highestBitOpnd, src,
> ```

VC does
```asm
cvtsi2sd    xmm0,rax  
test        rax,rax  
jge         SFNotSet 
addsd       xmm0, 0x43f0000000000000
SFNotSet:
```
I don't think we should try to avoid the branch, with branch prediction the resulting code will be much simpler and probably faster

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1992)*

**Comment by Krovatkin** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/Backend/LowerMDShared.cpp, line 7972 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1992#-KWKcPoopjO8bBp42GDM:-KWKn9QWBG9KS9Ml-Sjy:b-f21hga) ([raw file](https://github.com/microsoft/chakracore/blob/5c551a8374bb3de03098175a05b038e13c541b00/lib/Backend/LowerMDShared.cpp#L7972)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> I don't think it's necessary to unlink the source/dst knowing the instr will get removed
</details>
yup, ur rite.

---

*[lib/Backend/LowerMDShared.cpp, line 8011 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1992#-KWKf0AHbWHF93OZpjHz:-KWKnobH7LbKx-Thz7UJ:bq7sali) ([raw file](https://github.com/microsoft/chakracore/blob/5c551a8374bb3de03098175a05b038e13c541b00/lib/Backend/LowerMDShared.cpp#L8011)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> The recursion is not necessary
> You can call `instr->InsertBefore(IR::Instr::New(Js::OpCode::CVTSI2SD, dst, src, this->m_func));` before the unsigned check and remove the else block.
</details>
:sleeping: 

---

*[lib/Backend/LowerMDShared.cpp, line 8013 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1992#-KWKhz7Dy9VjLeXVGSLX:-KWKnHU02jpInAltbt1J:bll2d7s) ([raw file](https://github.com/microsoft/chakracore/blob/5c551a8374bb3de03098175a05b038e13c541b00/lib/Backend/LowerMDShared.cpp#L8013)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> VC does
> ```asm
> cvtsi2sd    xmm0,rax  
> test        rax,rax  
> jge         SFNotSet 
> addsd       xmm0, 0x43f0000000000000
> SFNotSet:
> ```
> I don't think we should try to avoid the branch, with branch prediction the resulting code will be much simpler and probably faster
</details>
this is what we do for `LowererMDArch::EmitUIntToFloat`. Do you feel strongly about switching to jumps? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1992)*

**Comment by Cellule** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/Backend/LowerMDShared.cpp, line 8013 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/1992#-KWKhz7Dy9VjLeXVGSLX:-KWKpqpUlPUNEv4HTxc1:bsm2g9v) ([raw file](https://github.com/microsoft/chakracore/blob/5c551a8374bb3de03098175a05b038e13c541b00/lib/Backend/LowerMDShared.cpp#L8013)):*
<details><summary><i>Previously, Krovatkin (Nick Korovaiko) wrote…</i></summary>
> this is what we do for `LowererMDArch::EmitUIntToFloat`. Do you feel strongly about switching to jumps? 
</details>
Not at this time, I'll keep a note of it to check back on it in the future

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1992#-:-KWKq0HqvGkj-YOHjQzh:bnfp4nl)*

**Pull request merged**
