### PR TITLE
SIMD bugfix: Store, inliner

### LINKED ISSUE #708: SIMD.js - Store operations return NULL instead of passed value per spec
The current implementation of SIMD store ops erroneously returns NULL (instead of Undefined). This causes a crash when merging ValueTypes during profiled interpretation, if store is used in an assignment. The correct behavior is to return the passed value, instead of Undefined. 

Repro case:
[stDstBug.js.txt](https://github.com/Microsoft/ChakraCore/files/198396/stDstBug.js.txt)

**Repro case**
>
```javascript
function func1()
{
    var buffer = new ArrayBuffer(1000);
    var arr = new Float32Array(buffer);
    var x = SIMD.Float32x4(0,0,0,0);
    var y = x;
    var f = SIMD.Float32x4(1, 2, 3, 4);
    for (var i = 0; i < 100/4; i += 4)
    {
        y = SIMD.Float32x4.store(arr, i, f)
        x = SIMD.Float32x4.add(x, y);
    }    
    return x;
}
print(func1());
print(func1());
```

**Expected Output:**
>
SIMD.Float32x4(7, 14, 21, 28)
SIMD.Float32x4(7, 14, 21, 28)

**Actual Output**
>
ASSERTION 31060: (G:\arun\git\chakra-310\core\lib\Runtime\Language\ValueType.cpp, line 1206) var
 Failure: (var)
FATAL ERROR: ch.exe failed due to exception code c0000420

### PR DESCRIPTION
**Pull request by arunetm**
1. Updating simd store semantics to return the value being stored.
2. Fixing an inliner bug while replacing dst for store operations.

Fixes #708

### CODE REVIEW

**Comment by arunetm** [comment]
Fixes #708

**Comment by arunetm** [comment]
Instead of #621

**Comment by arunetm** [comment]
@dotnetbot test x64_test please

**Comment by arunetm** [comment]
@dotnetbot test x64_test please

**Comment by arunetm** [comment]
@dotnet-bot test this please

**Comment by arunetm** [comment]
@abchatra Please help to sign off this PR.

**Comment by abchatra** [comment]
:+1:

**Pull request merged**
