### PR TITLE
[optional] Improve OS14363556

### PR DESCRIPTION
**Pull request by obastemur**
Discussion is on VSO.

### CODE REVIEW

**Comment by LouisLaf** [comment]
Did you verify that this recovers the whole regression?  I had tried that change but only saw a partial recovery...

**Comment by obastemur** [comment]
@LouisLaf wasn't able to observe regression on xplat / Clang LTO build after this PR. This could be compiler specific. Taking an additional look on Windows.

**Comment by obastemur** [comment]
Added bench results to VSO item. Unable to measure any perf diff (before after) the related changes.

I would like to merge this in anyway and keep the TODO FNV1a mention for any necessary change in future.

?

**Comment by LouisLaf** [comment]
LGTM

**Pull request merged**
