### PR TITLE
Check return value for GetModuleFileName in ConfigParser::ParseConfig

### PR DESCRIPTION
**Pull request by xiaoyinl**
If `GetModuleFileName` failed and we ignore the return value, then `_wsplitpath_s` will read uninitialized stack buffer `modulename`.

### CODE REVIEW

**Comment by xiaoyinl** [comment]
@dilijev Could you review this patch? Thanks!

**Comment by dilijev** [comment]
@LouisLaf @boingoing

**Comment by xiaoyinl** [comment]
Hi @boingoing, any update on the review? Thanks!

**Comment by dilijev** [comment]
@xiaoyinl: @boingoing is on vacation, but I've added @suwc who is currently doing work in the area of modules. Maybe he can give a review.

**Comment by suwc** [comment]
@xiaoyinl: thanks! If you have a small test case, could you add it to the regression tests? Also, I saw there are a few other places where GetModuleFileName is called and [out] modulename is used without checking return value. Let us know if you would be so kind to help fix them too :-) (It will be totally fine if you shall decide to leave them to us)

**Comment by xiaoyinl** [comment]
Thank you @dilijev and @suwc! I'd like to fix all other places and add test cases. I will do them today or tomorrow.

**Comment by dilijev** [comment]
@xiaoyinl Any update here?

**Comment by xiaoyinl** [comment]
@dilijev I am very sorry for the delay! I will do it tomorrow for sure this time.

**Comment by dilijev** [comment]
@xiaoyinl No worries -- just wanted to check in. Take your time. :)

**Comment by xiaoyinl** [comment]
Sorry I messed up the changes. I rebased it before pushing. I will close this and open a new one PR. Sorry for the long delay again!

**Comment by suwc** [comment]
@xiaoyinl, maybe you don't need to create a new PR. You might be able to just rebase and push -f to `xiaoyinl:modulefilename`.

**Comment by xiaoyinl** [comment]
@suwc Thank you! I did it. But now this PR can't be reopened. "The modulefilename branch was force-pushed or recreated". I should have forced push earlier. Anyway, now it seems I have to recreate a PR.

**Pull request closed without merging**
