### PR TITLE
xplat: fix embed-icu with intl option for static builds and cleanup

### PR DESCRIPTION
**Pull request by obastemur**
- icutools weren't part of the final binary (it supposed to be icutu instead!)
- linker force load i18n references to prevent some of them being optimized away

### CODE REVIEW

**Comment by obastemur** [comment]
2 successful checks? what happened to rest?

**Comment by obastemur** [comment]
Did we enabled CI for release/1.8?

**Comment by jackhorton** [comment]
Jenkins is down until 3pm today because they're working on the ci2.dot.net VMs

**Comment by obastemur** [comment]
> Jenkins is down until 3pm today because they're working on the ci2.dot.net VMs

I wish CI would just stall instead of showing all green. We may end up merging bad PRs by mistake

**Pull request merged**
