### PR TITLE
OS#14101048: For all built-in functions, func.hasOwnProperty('caller'|'arguments') === false

### PR DESCRIPTION
**Pull request by dilijev**
Fixes OS#14101048
Partial fix for #249

### CODE REVIEW

**Comment by boingoing** [comment]
Can't user code define a property named 'caller' or 'arguments' on a library function?

`Object.defineProperty(Boolean, 'caller', { value: 123 });` appears to work in Chrome.

Is that only in sloppy mode?

**Comment by dilijev** [comment]
@boingoing yes, that is supposed to be allowed. I'm trying to figure out a way to detect that a caller/arguments property has been overwritten or otherwise decide that this regression is worth the fix.

**Comment by dilijev** [comment]
I'm working on a more complete fix for this. Will update soon.

**Comment by dilijev** [comment]
Closing in favor of a new PR with a more complete fix.

**Comment by dilijev** [comment]
See #4651

**Pull request closed without merging**
