### PR TITLE
OS#13894912 WASM: Yielding in unreachable code

### PR DESCRIPTION
**Pull request by Cellule**
Allow the eval stack to be empty when yielding values in Unreachable state.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/3805)

### CODE REVIEW

**Comment by Cellule** [comment]
ping

**Comment by Cellule** [comment]
ping

**Comment by MikeHolman** [comment]
>         EmitInfo retExprInfo = explicitRetInfo ? *explicitRetInfo : PopEvalStack();

I believe this also needs to be changed

---
Refers to: lib/WasmReader/WasmByteCodeGenerator.cpp:1376 in 4987bb4. [](commit_id = 4987bb48f604a002daaa2fd79dbcfe291b09b8f1, deletion_comment = False)

**Comment by Cellule** [comment]
> I believe this also needs to be changed

I don't think we should change it. Since `return` is an explicit operator, I believe it needs to always have a value to pop. I think the rule applies only to implicit pop (ie yields)

**Comment by Cellule** [comment]
@MikeHolman Can you take a look at the last fix ?

**Pull request merged**
