### PR TITLE
#2510: Fixing compile error when building the same sample project as embedding ChakraCore shows.

### PR DESCRIPTION
**Pull request by r12f**
The issue is here: https://github.com/Microsoft/ChakraCore/issues/2510.

### CODE REVIEW

**Comment by obastemur** [comment]
LGTM. @r12f Thanks

**Comment by dilijev** [comment]
I keep seeing this `exit code: -11` issue (for reference -11 = 0xFFFFFFF5, but I haven't gone looking for the error code). Otherwise the test outputs look correct. Re-running tests:

@dotnet-bot 
test OSX osx_osx_debug_static
test Ubuntu ubuntu_linux_debug
test Ubuntu ubuntu_linux_test_static

**Comment by r12f** [comment]
Same error as #2517.
> 18:46:53 
> 18:46:53 Output:
> 18:46:53 ----------------------------
> 18:46:53 2395/2395 tests passed.
> 18:46:53 
> 18:46:53 ----------------------------
> 18:46:53 
> exit code: -11

@dotnet-bot
test OSX osx_osx_debug_static

**Comment by ThomsonTan** [comment]
:shipit:

**Comment by r12f** [comment]
@dotnet-bot
test OSX osx_osx_debug_static

**Comment by r12f** [comment]
Thanks @obastemur @dilijev @ThomsonTan for code for code reviewing the change!

**Comment by ThomsonTan** [comment]
@r12f , seems there are merge changes. Could you `git rebase` your change to the latest mater to make the merge clean?

**Comment by r12f** [comment]
@ThomsonTan sure thing, rebased to the latest version. looks like the "update branch" provided by github is actually doing a merge, which creates unexpected commits in the history... next time i will just do rebase instead.

**Comment by dilijev** [comment]
@r12f Also note, it's not necessary to frequently update your PR, unless git says there are merge conflicts. "Out of date" is usually okay for a codebase our size (not much chance of conflicting behavior on a small time scale).

**Comment by r12f** [comment]
@dilijev ah, great! Thanks for the note!

**Pull request merged**
