### PR TITLE
Don't unwrap a with object outside of a with scope.

### LINKED ISSUE #6237: assertion failure in Js::VarTo<Js::UnscopablesWrapperObject>
````
function foo() {
	function boo() { 
		print(typeof a); 
	}
	eval("function a(){} boo(a);");
}

for (let i=0; i<1000;i++){
	print(i);
	foo();
}
````

### PR DESCRIPTION
**Pull request by zenparsing**
Fixes #6237

### CODE REVIEW

**Comment by zenparsing** [comment]
@pleath I think this opcode may have crept in with #6215.

**Comment by pleath** [comment]
Yes, it did. My current PR fixes it, but go ahead and fix it here.

**Comment by zenparsing** [comment]
@pleath Sorry for the redundant fix - which PR?

**Comment by pleath** [comment]
This guy: https://github.com/microsoft/ChakraCore/pull/6232, which is a pretty chunky feature change. Let's go ahead with this fix, and I'll rebase the other PR.

**Pull request merged**
