### PR TITLE
Eliminate mentions of the unused "JD_PRIVATE" conditional compilation macro

### LINKED ISSUE #3024: Unused "JD_PRIVATE" conditional compilation macro is mentioned in the sources
It is never defined and should be eliminated.

### PR DESCRIPTION
**Pull request by ddv239**
Unused "JD_PRIVATE" conditional compilation macro is mentioned in the sources

Fixes #3024

### CODE REVIEW

**Comment by dilijev** [comment]
Used by internal build configurations.

**Comment by dilijev** [comment]
@ddv239 no need to constantly merge master, it unnecessarily loads up extra builds in the CI queue for no benefit. Additionally, if there's a merge conflict with the target branch, we prefer rebasing: https://github.com/Microsoft/ChakraCore/blob/master/CONTRIBUTING.md#housekeeping "Your pull request should ... Be a child commit of a reasonably recent commit"

**Comment by ddv239** [comment]
I didn't know I should not update; it suggested so.

**Comment by dilijev** [comment]
Unfortunately, we can't tell GitHub not to show that message. It's an understandable action to take. In our case, there is usually no benefit to doing so.

**Pull request merged**
