### PR TITLE
Remove all code dealing with the unused CallPut

### PR DESCRIPTION
**Pull request by curtisman**

### CODE REVIEW

**Comment by pleath** [comment]
What will happen if someone writes f() = 1?

**Comment by curtisman** [comment]
@pleath You already made it an early error in TH2 :)

**Comment by pleath** [comment]
That change had to be reverted for compat reasons. f() = 1 is a runtime error today. Not as I would have it, but there it is.

**Comment by curtisman** [comment]
I believe it always emitted as a runtime error and all the code that support the actually "CallPut" is never emitted any more.

**Comment by curtisman** [comment]
@pleath gave the green light offline.

**Pull request merged**
