### PR TITLE
Files changed on merge commit

### PR DESCRIPTION
**Pull request by Cellule**
Change the git log command to list the file changed on a merge commit using the first parent.
The file changed can be useful when consumed by tools trying to understand the nature of the change on that build.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1477)

### CODE REVIEW

**Comment by Cellule** [comment]
@dilijev Can you review please?

**Comment by dilijev** [comment]
LGTM, thanks!

**Comment by Cellule** [comment]
@dotnet-bot please test Windows arm_test

**Comment by dilijev** [comment]
@dotnet-bot test Windows arm_release please

**Pull request merged**
