### PR TITLE
OS11907290 InitPorperty inside eval code should have configurable true

### PR DESCRIPTION
**Pull request by akroshg**
As per EvalDeclarationInstantiation CreateGlobalFunctionBinding will make sure to have global function to be configurable. But we didn't set that which breaks a web-page
 https://spb.tele2.ru/mobile/internet/skylink, where we throw error for such scenario. Fixed that.

### CODE REVIEW

**Comment by akroshg** [comment]
@tcare @pleath - please have a look

**Comment by pleath** [comment]
This is only for indirect eval, right? The base eval case still works the way it always has?

**Comment by tcare** [comment]
Please make sure to have the bug number look like OS: 123456 otherwise automation will not pick it up.

---
In reply to: [329299188](https://github.com/Microsoft/ChakraCore/pull/3722#issuecomment-329299188) [](ancestors = 329299188)

**Comment by tcare** [comment]
I believe base eval already had the correct behavior. Akrosh, how does the base eval work for this case?

---
In reply to: [329303273](https://github.com/Microsoft/ChakraCore/pull/3722#issuecomment-329303273) [](ancestors = 329303273)

**Comment by pleath** [comment]
It uses ScopedInitFld instead of normal InitFld, because it has to access the scope chain instead of going straight to the global object.

**Comment by akroshg** [comment]
@pleath yes this is for indirect eval (the test case mentions the scenario)

**Comment by tcare** [comment]
Does the normal eval case explicitly set the correct configurability?

**Comment by akroshg** [comment]
@tcare yes

**Comment by tcare** [comment]
Cool, good to know.

**Pull request merged**
