### PR TITLE
Simd.js library support

### PR DESCRIPTION
**Pull request by arunetm**
Change description:

1. Implemented support for the following new SIMD types. This adds to the existing SIMD types (Int32x4 and Float32x4) and meets the SIMD.js specification. [SIMD.Bool32x4, SIMD.Bool16x8, SIMD.Bool8x16, SIMD.Int16x8, SIMD.Int8x16, SIMD.Uint32x4, SIMD.Uint16x8, SIMD.Uint8x16]
2. Adding new builtin functions for all SIMD types to be consistent with the SIMD.js specification and the polyfill.
3. Updating the syntax and behavior of the existing builtin functions and removing builtins to be consistent with the SIMD.js specification and the polyfill.
4. Clean up of existing SIMD unittests to avoid printing SIMD values for validation. Tests prints only PASS/FAIL while verification and uses utility methods for comparing the values to the right precision. 
5. Code refactoring to reduce code size/complexity of the SIMDjs code.

### CODE REVIEW

**Comment by arunetm** [comment]
Change description:
1.Implemented support for the following new SIMD types. This adds to the existing SIMD types (Int32x4 and Float32x4) and meets the SIMD.js specification. [SIMD.Bool32x4, SIMD.Bool16x8, SIMD.Bool8x16, SIMD.Int16x8, SIMD.Int8x16, SIMD.Uint32x4, SIMD.Uint16x8, SIMD.Uint8x16]
2.Adding new builtin functions for all SIMD types to be consistent with the SIMD.js specification and the polyfill.
3.Updating the syntax and behavior of the existing builtin functions and removing builtins to be consistent with the SIMD.js specification and the polyfill.
4.Clean up of existing SIMD unittests to avoid printing SIMD values for validation. Tests prints only PASS/FAIL while verification and uses utility methods for comparing the values to the right precision. 
5.Code refactoring to reduce code size/complexity of the SIMDjs code.

**Comment by dilijev** [comment]
Updated description of the issue so the text will show up in the merge commit message.

**Comment by dilijev** [comment]
@arunetm It looks like some of your copyright headers are incorrect or missing.

In the generated Promise.js.bc.*.h:

```
$ head lib/Runtime/Library/InJavascript/Promise.js.bc.32b.h
// Copyright (C) Microsoft. All rights reserved.
#if 0
//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------
```

Compare with:

```
$ head lib/Runtime/Library/InJavascript/intl.js.bc.32b.h
//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------
#if 0
//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------
```

Although I believe we recently noted that there is no use for these Promise bytecodes in ChakraCore so we moved them back to Chakra. Can you confirm whether they are needed in ChakraCore for your change, and if not, remove them?

**Comment by dilijev** [comment]
Full list of files missing or wrong copyright from the failed check:

```
11:54:31 --------------
11:54:31 --- ERRORS ---
11:54:31 lib/Runtime/Library/InJavascript/Promise.js.bc.32b.h ... does not contain a correct Microsoft copyright notice.
11:54:31 lib/Runtime/Library/InJavascript/Promise.js.bc.64b.h ... does not contain a correct Microsoft copyright notice.
11:54:31 test/SIMD.int32x4/testLoad.js ... does not contain a correct Microsoft copyright notice.
11:54:31 test/SIMD.int32x4/testMinMax.js ... does not contain a correct Microsoft copyright notice.
11:54:31 test/SIMD.int32x4/testStore.js ... does not contain a correct Microsoft copyright notice.
11:54:31 --------------
```

**Comment by arunetm** [comment]
Thanks @dilijev. Updated the PR by removing unused bytecode headers and adding missing copyright header for the test files.

**Comment by tcare** [comment]
Were these generated by the header script? We might need to update some more of that with the license header changes. @akroshg will have more context (but is away for a few more weeks)

**Comment by arunetm** [comment]
@tcare, We might not need any script updates for this. The Promise.js.bc.*.h files were generated by the Genbytecode script a while back. However the latest script does not create these files anymore.

**Comment by tcare** [comment]
Ah, okay. Thanks for the clarification.

**Comment by abchatra** [comment]
Does all the [kangax es7](http://kangax.github.io/compat-table/es7/) test cases pass after this change?

**Comment by abchatra** [comment]
Why doesn't this change remove SIMDFloat64x2

**Comment by arunetm** [comment]
@abchatra,We have not verified this feature against the 'kangax es7' tests. We do pass the SIMD validation tests from the SIMDjs polyfill (link below).
https://github.com/tc39/ecmascript_simd/blob/master/src/ecmascript_simd_tests.js
These tests are consistent with the latest SIMD spec and we pass all of them.

**Comment by arunetm** [comment]
@abchatra There is a possibility for the Float64x2 SIMD type to be re introduced to the SIMD spec based on some of the on going discussions(https://github.com/tc39/ecmascript_simd/issues/304). 
We are planning to have a clean up PR after performing multiple cleanups including this type (in case Float64x2 is decided again to be omitted from the specification).

**Comment by arunetm** [comment]
Using telemetry for SIMD library builtins: 
The ideal use cases for SIMD builtin functions will follow the optimized versions of their implementation. The current library implementation is meant for spec coverage and they will be used only in rare cases. Collecting the telemetry for the optimized builtins might be more useful than capturing the information for the library implementations. 

Testing: 
The  SIMD builtins has been verified against the polyfill validation tests https://github.com/tc39/ecmascript_simd/blob/master/src/ecmascript_simd_tests.js, to ensure consistency with the latest SIMD specification. The implementation passes all of these polyfill tests.

We have not tried testing against "kangax es7" tests so far. Planning to verigy against the kangax es7 tests as the next step.

**Comment by abchatra** [comment]
@arunetm  Do you have a new commit which I review and signoff?

**Comment by arunetm** [comment]
@abchatra The commit 2af6118 is ready for review. Thanks.

**Comment by abchatra** [comment]
:+1: Great job!

**Comment by arunetm** [comment]
@abchatra  Thanks for the feedback. 
I have an authorization issue for the code sign off. The tool complains that my account is not authorized. Can you please help to sign off this PR.

**Comment by abchatra** [comment]
@arunetm Done.

**Comment by dilijev** [comment]
@dotnet-bot test EOL Check please

**Pull request merged**
