### PR TITLE
Refactor common functions to EngineInterfaceObject

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@dotnet-bot test  OSX static_osx_osx_release 

@dotnet-bot

**Comment by meg-gupta** [comment]
@dotnet-bot test OSX _no_jit_shared_osx_osx_test

**Comment by meg-gupta** [comment]
@dotnet-bot test  OSX static_osx_osx_release

**Comment by jackhorton** [comment]
I have been letting OS X fail until everything else passes and then triggering the OS X builds and force-merging in ChakraHub before they fail again, since ChakraHub doesn't allow force merges when anything is in a failure state

**Comment by meg-gupta** [comment]
That's useful, thanks!

**Comment by meg-gupta** [comment]
@dotnet-bot test OSX static_osx_osx_release

**Pull request merged**
