### PR TITLE
Bug10436738: Missing lower bounds check

### PR DESCRIPTION
**Pull request by Cellule**
Add lower bounds check on enum to AsmJsJITInfo::GetTypedSlotInfo

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/2362)

### CODE REVIEW

**Comment by Cellule** [comment]
@Microsoft/chakra-developers Can someone review this please ?

**Comment by dilijev** [comment]
Change looks good but lots of tests are failing

**Comment by Cellule** [comment]
*facepalm* `type` **>=** `0`

**Comment by dilijev** [comment]
facepalm for me, too. Should have caught that.

**Pull request merged**
