### PR TITLE
WebAssembly 0xD

### PR DESCRIPTION
**Pull request by Cellule**
Implement changes for WebAssembly 0xD format and update tests

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1822)

### CODE REVIEW

**Comment by Cellule** [comment]
Just FYI guys, if you want to start using 0xD Wabt, you need to update some of the opcodes in it because of a change that was made after the initial opcode ordering.
See https://github.com/WebAssembly/wabt/issues/185
I'll try to make a PR for Wabt so you don't have to worry about this once 0xD is merged

**Comment by Cellule** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_test_static please

**Comment by Cellule** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug please

**Comment by Cellule** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_release please

**Comment by MikeHolman** [comment]
lgtm

**Pull request merged**
