### PR TITLE
Disable switch opts upon loop body rejit

### PR DESCRIPTION
**Pull request by rajatd**
Disable switch opts when we rejit a loop body owing to a switch opts bailout (We already do this for function rejits).

Also, rename RejitRatioLimit to the more accurate CallsToBailoutsRatioForRejit

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/895)

### CODE REVIEW

**Comment by rajatd** [comment]
@satheeshravi , please take a look

**Comment by rajatd** [comment]
@dotnet-bot test this please

**Comment by rajatd** [comment]
@dotnet-bot test this please

**Comment by satheeshravi** [comment]
:+1:

**Pull request merged**
