### PR TITLE
fix BuildJIT=false build break on WIN32

### PR DESCRIPTION
**Pull request by jianchun**
On WIN32 BuildJIT=false build type we still build JITClient which needs
real JITManager declaration.

### CODE REVIEW

**Comment by jianchun** [comment]
@Penguinwizzard Thanks for letting me know of the break. Could you please help review the fix?

**Comment by dilijev** [comment]
@dotnet-bot test nojit tests please

**Comment by dilijev** [comment]
@jianchun The majority of test failures look like they just need specialized baselines for the NoJIT case, although there are some assertion failures as well.

**Comment by jianchun** [comment]
@dotnet-bot test nojit tests please

**Comment by jianchun** [comment]
@dilijev Updated and all passed. Could you please take a quick look at my change in GenByteCode.cmd?
@Penguinwizzard @leirocks Could one of you please take a look at my fix?

**Comment by jianchun** [comment]
Thanks @leirocks @Penguinwizzard @dilijev!

**Pull request merged**
