### PR TITLE
CAS:FaultInjection: ASSERT:  Ensure var is actually a 'JavascriptFunction'

### PR DESCRIPTION
**Pull request by suwc**
chakra!Js::JavascriptFunction::FromVar+7f [d:\th\inetcore\jscript\lib\runtime\library\javascriptfunction.inl @ 50]
Need to change the type of the new typehandler before changing type handler of an instance.

### CODE REVIEW

**Comment by suwc** [comment]
@akroshg @abchatra could you take a look pls?

**Comment by rajatd** [comment]
Change itself looks good. Although, I'm curious to know what issue is this fixing.

**Comment by suwc** [comment]
The issue is captured in OS2127188.

**Comment by ianwjhalliday** [comment]
External to Microsoft GitHub users cannot see our internal bug database.  It would be neighborly to provide more details on this issue for all to see.

**Comment by ianwjhalliday** [comment]
Also makes historical research easier in the future if we ever look back at this.

**Comment by abchatra** [comment]
:+1:

**Pull request merged**
