### PR TITLE
 GetProcAdress -> GetProcAddress

### PR DESCRIPTION
**Pull request by github-john-doe**

### CODE REVIEW

**Comment by kfarnung** [comment]
Hey @github-john-doe, the change looks good, but in the future you'll want to rebase your branches against upstream/master rather than merge:

```
git rebase upstream/master
```

That command should also be able to fix up the current state of this PR.  Let me know if you need help doing that.

**Comment by kfarnung** [comment]
Hey @github-john-doe, thanks for taking a look.  It seems like you ended up with a merge conflict in your current commit.  You'll also need to force push (`git push -f`) the branch to overwrite the bad history.

The easiest way to fix this specific issue is probably to backup the current state of the branch, reset your master branch to match upstream, then cherry-pick your change and push it:
```console
$ git checkout -b backup
$ git checkout master
$ git reset --hard upstream/master
$ git cherry-pick e591be2c33aa0a89f89a1a642be3fb3ef54fc3f6
$ git push -f
```

For future contributions I recommend creating a new branch based on upstream/master:
```console
$ git fetch upstream master
$ git checkout -b my-pr-branch upstream/master --no-track
$ git commit -a
$ git push origin my-pr-branch --set-upstream
```

Then you can open your PR on GitHub using that PR branch.

**Comment by kfarnung** [comment]
Thanks @github-john-doe!  I'll get this landed today.

**Comment by github-john-doe** [comment]
Thank you @kfarnung. Now I know how to rebase my forks.

**Comment by kfarnung** [comment]
Glad to help!  Thanks for your contribution!

**Pull request merged**
