### PR TITLE
Fix error message per issue #424

### PR DESCRIPTION
**Pull request by mwksl**
This should fix the error messages when changing [[Writable]] as mentioned in #424.

### CODE REVIEW

**Comment by rajatd** [comment]
Hi @mwksl , thanks for your pull request. I looked at your changes and it seems that it would while it would fix the issue #424 , it would give wrong error message for `obj.x = 1` where `x` was non-writable. We should detect the case when we are changing [[Writable]] to true from false for non-configurable properties, and change the error message for that case.

**Comment by abchatra** [comment]
Thank you for your contribution. Can you please sign the cla?

**Comment by abchatra** [comment]
@mwksl  any update on signing the cla and this PR? If not we will close the PR this week.

**Comment by abchatra** [comment]
No update here, hence closing the PR

**Pull request closed without merging**
