### PR TITLE
ch: use copy instead of direct sourmap cache

### PR DESCRIPTION
**Pull request by obastemur**
In case we load the same cached source file twice, ch won't track that and free the buffer twice.

Originally reported by OSS-FUZZ OS#15921043

### CODE REVIEW

**Comment by jianchun** [comment]
LGTM, but I have no context what/how SourceMap is used, maybe @jackhorton can take a look?

**Comment by jackhorton** [comment]
I cant say I have a ton of context either, but it looks reasonable to me?

**Comment by obastemur** [comment]
@dotnet-bot test OSX static_osx_osx_debug please

**Comment by obastemur** [comment]
@jianchun @jackhorton Thanks for the review!

**Pull request merged**
