### PR TITLE
Fix a missing unconditional branch, remove an unnecessary branch chain.

### PR DESCRIPTION
**Pull request by Penguinwizzard**

### CODE REVIEW

**Comment by Penguinwizzard** [comment]
@rajatd please review

**Comment by rajatd** [comment]
Looks good. Can you add unit tests for this?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by Penguinwizzard** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_release_static please

**Pull request merged**
