### PR TITLE
MicroBuild v2: Fix string formatting in change.txt.

### PR DESCRIPTION
**Pull request by dilijev**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1132)

### CODE REVIEW

**Comment by dilijev** [comment]
@Cellule Review please?

**Comment by dilijev** [comment]
@Cellule was this infra-blocking or just cosmetic? (How hard should I try to get this change into all branches?)

**Comment by Cellule** [comment]
It's not infra blocking, but reporting tool will miss the commit description which is annoying

**Comment by Cellule** [comment]
lgtm

**Comment by dilijev** [comment]
@Cellule, okay, merging this into release/1.2 will eventually propagate to most branches. I think I won't worry about backporting this to release/1.1 unless we have some activity there or another round of breaking Microbuild v2 changes. @ianwjhalliday does that sound okay?

**Pull request merged**
