### PR TITLE
osx: fix ASM files are being compiled with later OS SDK

### PR DESCRIPTION
**Pull request by obastemur**
Minor fix for inconsistent linker target. This also shows up on embedding 3rd party.

### CODE REVIEW

**Comment by digitalinfinity** [comment]
:shipit:

**Comment by obastemur** [comment]
@dotnet-bot test  Ubuntu ubuntu_linux_debug_static

**Comment by obastemur** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_release

**Comment by obastemur** [comment]
@dotnet-bot test OSX osx_osx_debug_static

**Comment by obastemur** [comment]
@dotnet-bot test OSX osx_osx_test_static

**Comment by obastemur** [comment]
@dotnet-bot test OSX osx_osx_release_static

**Comment by obastemur** [comment]
@digitalinfinity Thanks for the review

**Pull request merged**
