### PR TITLE
MSFT: 8158180 CAS:EdgeCrawler: ASSERT:  isFinalized (Chakra!Js::ScriptContext::~ScriptContext+97 [d:\a\_work\19\s\core\lib\runtime\base\scriptcontext.cpp @ 378])

### PR DESCRIPTION
**Pull request by Yongqu**
Fix an assert. ScriptContext dtor can be called if we failed half way during the intialization.
Some perf improvement for ExternalFunctionThunk as it is the main entrypoint for external function calls.
Get rid of unused ETW code, and move out DefaultEntryPoint check for DOM constructors that cannot be new'ed.

### CODE REVIEW

**Comment by Yongqu** [comment]
@agarwal-sandeep can you take a look? related to ExternalFunction perf as well.

**Comment by agarwal-sandeep** [comment]
LGTM

**Comment by Yongqu** [comment]
@dotnet-bot test this please

**Comment by Yongqu** [comment]
@dotnet-bot test this please

**Pull request merged**
