### PR TITLE
Added conditions for project.json

### LINKED ISSUE #3431: Nuget package Microsoft.ChakraCore doesn't work with solution that uses project.json
From ``Microsoft.ChakraCore.props``, before copying the dorrect dll to the build output, it seems that the it checks if a `packages.config` exists, which is not the case if your project is using a `project.json` file.

### PR DESCRIPTION
**Pull request by DZuz14**
Not sure if this is what was meant by issue #3431. I do not touch XML very much, but regardless, the issue seems like it can be taken care of pretty simply. Will the conditionals I put in work? 

Fixes #3431

### CODE REVIEW

**Comment by liminzhu** [comment]
@dilijev who would be a good person to review this?

**Comment by dilijev** [comment]
Looks reasonable to me.

@pre10der89 submitted f27560ffc which added this file, so he's probably a good choice to review.

**Comment by DZuz14** [comment]
No problem guys. Just beginning to explore open source. Not going to lie, I have no idea if that's what you were asking for. Still a good way to see how contributing would work.

**Comment by dilijev** [comment]
It sounds like this fits. I haven't given it a try yet.
Let's find out from @benjaminpetit if this resolves his concern.

**Comment by dilijev** [comment]
Oh btw does anyone know if the pattern `project.$(MSBuildProjectName).json` is even supported by NuGet?

**Comment by dilijev** [comment]
There's some concern about this change [on Gitter](https://gitter.im/Microsoft/ChakraCore?at=5996847cbc4647297496c83e) -- want to investigate and resolve that before merging.

**Comment by MikeHolman** [comment]
@dilijev What is the resolution? Can you follow up if there are still concerns?

**Comment by dilijev** [comment]
I'll reach out to various parties and see if we can come to a resolution.

**Comment by dilijev** [comment]
Despite some effort, I haven't gotten a clear answer about this nor a clear reason why adding support is particularly a bad thing, so I'm going to merge this.

**Comment by dilijev** [comment]
@DZuz14 Apologies for letting this take so long and that your contribution experience here was not very smooth.

**Pull request merged**
