### PR TITLE
use [reg+reg+offset] addressing mode for wasm memory indexes

### PR DESCRIPTION
**Pull request by MikeHolman**
Change how we index wasm memory to use addressing mode for constant offsets instead of having separate add instructions.

Also, disable constant encoding for IndirOpnds that are used for wasm mem access.
````
unity                  Left score        Right score       ∆ Score  ∆ Score %  Comment
---------------------  ----------------  ----------------  -------  ---------  --------
Overall                 90531.50 ±0.06%   96132.00 ±0.18%  5600.50      6.19%  Improved
Mandelbrot Script       81022.00 ±0.00%   81395.50 ±0.46%   373.50      0.46%
Instantiate & Destroy   26301.00 ±0.67%   27729.50 ±0.83%  1428.50      5.43%  Improved
CryptoHash Script      169851.50 ±0.18%  178607.00 ±0.37%  8755.50      5.15%  Improved
Animation & Skinning      546.50 ±0.09%     580.00 ±0.00%    33.50      6.13%  Improved
Asteroid Field          24582.50 ±0.32%   26391.00 ±0.10%  1808.50      7.36%  Improved
Physics Spheres          1657.00 ±0.18%    1764.00 ±0.00%   107.00      6.46%  Improved
Physics Spheres          1657.00 ±0.18%    1764.00 ±0.00%   107.00      6.46%  Improved
2D Physics Boxes         2117.00 ±1.04%    2213.50 ±0.47%    96.50      4.56%  Improved
---------------------  ----------------  ----------------  -------  ---------  --------
Total                   11100.34 ±0.30%   11692.81 ±0.27%   592.47      5.34%  Improved
````

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/2560)

### CODE REVIEW

**Comment by MikeHolman** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug_static

**Comment by Cellule** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/Backend/IRBuilderAsmJs.cpp, line 1524 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/2560#-KdY2TPDeRmLratecJy0:-KdY2TPDeRmLratecJy1:b-vkkhzw) ([raw file](https://github.com/microsoft/chakracore/blob/e5b739570338c14e5c93636ca7483b3fe366355f/lib/Backend/IRBuilderAsmJs.cpp#L1524)):*
> ```cpp
>     Js::RegSlot indexRegSlot = GetRegSlotFromIntReg(slotIndex);
>     IR::RegOpnd * indexOpnd = BuildSrcOpnd(indexRegSlot, TyUint32);
>     // don't support encoding in case of 
> ```

nit: unfinished comment

---

*[lib/Backend/LowerMDShared.cpp, line 1172 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/2560#-KdY7ygT6UiIZ9MmFi7B:-KdY7ygT6UiIZ9MmFi7C:b-oaxra7) ([raw file](https://github.com/microsoft/chakracore/blob/e5b739570338c14e5c93636ca7483b3fe366355f/lib/Backend/LowerMDShared.cpp#L1172)):*
> ```cpp
>     MakeDstEquSrc1(instr);
> 
>     if (!needFlags)
> ```

I don't fully understand why this is needed

---

*[lib/Runtime/ByteCode/OpLayoutsAsmJs.h, line 97 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/2560#-KdXuUoBfm5zrdwoyeoE:-KdXuUoCK8dXDewHMENj:b-wsbnrx) ([raw file](https://github.com/microsoft/chakracore/blob/e5b739570338c14e5c93636ca7483b3fe366355f/lib/Runtime/ByteCode/OpLayoutsAsmJs.h#L97)):*
> ```objc
>     {
>         // force encode 4 bytes because it can be a value
>         uint32                               SlotIndex;
> ```

`SlotIndex` is now always a register thus should have type `typename SizePolicy::RegSlotType`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/2560)*

**Comment by MikeHolman** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/Backend/IRBuilderAsmJs.cpp, line 1524 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/2560#-KdY2TPDeRmLratecJy0:-Ke1BOgCZzghW9G8mZV9:b-hfpv0l) ([raw file](https://github.com/microsoft/chakracore/blob/e5b739570338c14e5c93636ca7483b3fe366355f/lib/Backend/IRBuilderAsmJs.cpp#L1524)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

nit: unfinished comment
</blockquote></details>

removed

---

*[lib/Backend/LowerMDShared.cpp, line 1172 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/2560#-KdY7ygT6UiIZ9MmFi7B:-Ke19js3sMT18RvlM8_A:b-vzgk40) ([raw file](https://github.com/microsoft/chakracore/blob/e5b739570338c14e5c93636ca7483b3fe366355f/lib/Backend/LowerMDShared.cpp#L1172)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

I don't fully understand why this is needed
</blockquote></details>

Unlike ADD, INC will not set CF flag on unsigned overflow

---

*[lib/Runtime/ByteCode/OpLayoutsAsmJs.h, line 97 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/2560#-KdXuUoBfm5zrdwoyeoE:-Ke1BS9E_OCtcEbrpxqu:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/e5b739570338c14e5c93636ca7483b3fe366355f/lib/Runtime/ByteCode/OpLayoutsAsmJs.h#L97)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

`SlotIndex` is now always a register thus should have type `typename SizePolicy::RegSlotType`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/2560)*

**Comment by Cellule** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/2560#-:-Ke5BD4oA2og6hgr_LId:bnfp4nl)*

**Pull request merged**
