### PR TITLE
xplat: re-enable GetThreadId assert in Recycler.cpp

### PR DESCRIPTION
**Pull request by xanlpz**
The method is implemented for Linux and POSIX/pthread now.

### CODE REVIEW

**Comment by xanlpz** [comment]
So obviously need to somehow include thread.hpp from PAL here. What's the best way to do that?

**Comment by digitalinfinity** [comment]
@xanlpz It looks like GetCurrentThreadId is already implemented in pal/src/thread/thread.cpp (the one in thread.hpp that you mention implements CPalThread::GetCurrentThreadId). I'm not sure which implementation is better, I think the one in thread.cpp is slower. What do you think? If you decide to go with the one in thread.cpp, it's sufficient to just declare the API in ChakraPal.h.

**Comment by xanlpz** [comment]
Unless I'm really confused the function in thread.cpp just calls one of the implementations in thread.hpp, so it's all just one thing. I'll declare it in ChakraPal.h then.

**Comment by obastemur** [comment]
LGTM

**Comment by digitalinfinity** [comment]
LGTM too- thanks @xanlpz!

**Pull request merged**
