### PR TITLE
Cross Platform: Compiles on OSX

### PR DESCRIPTION
**Pull request by jkrems**
Mostly wanted to document how to compile it on OSX without [a VM](http://ariya.ofilabs.com/2016/01/playing-with-chakracore-on-linux.html).

I didn't do any testing on this, this is purely an "it compiles". But maybe it could be helpful to others.

### CODE REVIEW

**Comment by dilijev** [comment]
@jkrems Thanks for the contribution! I assume you mean it compiles now on OS X for the parts we've gotten to compile on Linux? (I got really excited for a minute thinking you had done a ton of work to get the whole thing to compile on OS X.) :P

**Comment by dilijev** [comment]
@tcare would you mind giving this a test run?

**Comment by jkrems** [comment]
@dilijev Hehe, exactly. I didn't too anything more but make `cmake . && make` exit with code 0. :)

**Comment by jianchun** [comment]
@jkrems Thank you for your contribution! I have merged this PR and apologize for the delay. As on the [roadmap](https://github.com/Microsoft/ChakraCore/wiki/Roadmap#enhancing-host--platform-support), our initial effort is targeting x64 Ubuntu 15.10. It is difficult for us to find resources validating PRs targeting OSX. We'd appreciate if you could align your effort to x64 Linux.

**Comment by jkrems** [comment]
@jianchun Totally fair. I would have fully understood if you would have just closed the PR to not create the wrong impression that OSX support is official (yet). :)

**Comment by jianchun** [comment]
@jkrems Thank you for understanding! As you described it may be helpful for others to try it. Longer term we will work on it, just no resources right now.

**Pull request merged**
