### PR TITLE
Fixes `Error.stack` is being `undefined` when `Error.stackTraceLimit==0`

### LINKED ISSUE #589: Error.stack undefined when Error.stackTraceLimit == 0
Small compatibility issue.

```
Error.stackTraceLimit = 0
new Error('abc').stack
```

Chrome: ```"Error: abc"```
Edge: ```undefined```

### PR DESCRIPTION
**Pull request by obastemur**
Fixes #589 See https://github.com/Microsoft/ChakraCore/pull/655

### CODE REVIEW

**Comment by obastemur** [comment]
@jianchun tests are failed after editing `Dump(TrimStackTracePath(e.stack) || e);`

Is there a test case for throwing non Error object ? That could be the reason. In that case, no point updating that line ?

**Comment by jianchun** [comment]
Yes, test fails because one case the getter throws a String. Just need to update the baseline:

```
--Throw in getter
** Custom stackTraceLimit getter Called, throw
My error in custom stackTraceLimit getter
```

Replace the last line with `undefined`. Now the tests cover both `throw new Error` and `throw 'String'` cases, and the later case `e.stack === undefined` (same as V8).

The `|| e` part in `TrimStackTracePath(e.stack) || e` was to work around `e.stack === undefined` case. Removing `|| e` makes the test to cover your fix.

**Comment by obastemur** [comment]
@jianchun thanks for the details. PR is updated accordingly.

**Comment by jianchun** [comment]
Thank you @obastemur!

**Pull request merged**
