### PR TITLE
fix line ending after merge

### PR DESCRIPTION
**Pull request by leirocks**

### CODE REVIEW

**Comment by obastemur** [comment]
:shipit:

**Comment by obastemur** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug please

**Comment by obastemur** [comment]
Interesting error on CI

```
12:32:03 
[1m/mnt/j/workspace/Microsoft_ChakraCore/release_2.0/ubuntu_linux_debug_prtest/lib/Runtime/./Library/ArrayBuffer.h:87:9: [0m[0;1;31merror: [0m[1mUnbarriered field, see https://github.com/microsoft/ChakraCore/wiki/Software-Write-Barrier#coding-rules[0m
12:32:03         bool isDetached;
```

/cc @jianchun

**Comment by obastemur** [comment]
Started to get the same memory barrier issue on somewhere else. -> https://github.com/Microsoft/ChakraCore/pull/2874

**Comment by leirocks** [comment]
@dilijev yes, the barrier annotation is in 2.0 only, there's new field which should be annotated but the merge tool cant find this, the build checker is designed to find it out

**Pull request merged**
