### PR TITLE
Minor fix while dumping AddrOpnd while in oopjit

### PR DESCRIPTION
**Pull request by meg-gupta**

### CODE REVIEW

**Comment by meg-gupta** [comment]
@dotnet-bot Test Ubuntu ubuntu_linux_test_static

**Comment by meg-gupta** [comment]
@dotnet-bot Test OSX osx_osx_debug_static

**Comment by meg-gupta** [comment]
@dotnet-bot test OSX osx_osx_debug_static

**Comment by dilijev** [comment]
Failure is #2517 -- retrying:
@dotnet-bot test OSX osx_osx_debug_static please

**Comment by meg-gupta** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_release_static

**Comment by meg-gupta** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug

**Pull request merged**
