### PR TITLE
Add the -oopjit- flag for pogo builds

### PR DESCRIPTION
**Pull request by boingoing**

### CODE REVIEW

**Comment by Cellule** [comment]
:shipit:

**Comment by abodalevsky** [comment]
Hi @boingoing 
For now instead of execution script it produces the following output, is it expected?

```
Running & "C:\projects\blue-rnw-net46\ChakraCore\Build\scripts\pgo\pogo_training.ps1" -arch x64 -flavor Release -subtype pogo -binary .\ChakraCore\Build\VcBuild\bin\x64_release_pogo\ch.exe -scenarios .\pogo_artifacts\test.js
.\ChakraCore\Build\VcBuild\bin\x64_release_pogo\ch.exe -oopjit- .\pogo_artifacts\test.js
.\ChakraCore\Build\VcBuild\bin\x64_release_pogo\ch.exe : Error in opening file '-oopjit-' : The system cannot find the file specified.
At line:1 char:1
+ .\ChakraCore\Build\VcBuild\bin\x64_release_pogo\ch.exe -oopjit- .\pog ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error in openin...file specified.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

```

**Comment by Cellule** [comment]
@abodalevsky Pogo training is currently targeted at test builds. On release builds, flags are not available and I guess we don't even parse them which is why it thinks `-oopjit-` is the file.
@dilijev are we doing pgo build on test or release builds for chakracore releases ?
@ThomsonTan Can we investigate the possibility of running pgo scenarios with oopjit and with release builds ?

**Comment by ThomsonTan** [comment]
@Cellule I'll take a look at running PGO for release builds with OOP. But wondering why we didn't enable it before, is it lacking of build resource (it creates a new build flavor for all builds)?

**Comment by Cellule** [comment]
@ThomsonTan I think there was a problem with how the run ends. The jitserver didn't exit cleanly and it corrupted .pgc files if I remember correctly

**Comment by dilijev** [comment]
@Cellule We do PGO builds for Release builds of ChakraCore. But, you're correct that Release builds don't understand test flags, so training scenarios need to work without requiring any flags. If you try training with just a JS file, it will work.

**Comment by dilijev** [comment]
@boingoing you should try this change on our NuGet/POGO configuration for ChakraCore in VSO and see if it works correctly -- I'd expect not.

**Comment by dilijev** [comment]
@Cellule @boingoing I see what happened here. In ChakraFull we POGO Test builds for testing purposes, and the pogo_training.ps1 script is used to do the training there as well. In that case, the test parameters work just fine. We never noticed the ChakraCore problem because we have not yet made a release of ChakraCore since flags were added (not present in release/1.3, but the flag (currently `-oopjit-`) was added for release/1.4.

I'll do a test NuGet/POGO build of ChakraCore now to confirm the error.

**Comment by dilijev** [comment]
Confirmed the issue in ChakraCore.

**Comment by dilijev** [comment]
@matthargett I'd say we're probably going to get this fixed in time for release ChakraCore 1.4.0, which is coming soon. Added issue @2213 to track this. Thanks for bringing this up.

**Pull request merged**
