### PR TITLE
Update netci.groovy to produce daily and push build tasks for other branches for which netci.groovy is evaluated.

### PR DESCRIPTION
**Pull request by dilijev**
This is specifically targeted at adding support for daily and rolling (push) build tasks for the release/1.2 branch but it will also apply for adding this same support for other branches in the future when they are added to the list found at:

https://github.com/dotnet/dotnet-ci/blob/master/jobs/data/repolist.txt

With these changes the following will occur:
* When netci.groovy is modified in the master branch
  * All of the existing daily tasks targeting master will be updated according to the new contents of the netci.groovy script. At present there are no changes as far as master is concerned.
  * PR tasks will be created which will be triggered for Pull Requests targeting any branch.
*  When netci.groovy is modified in any other branch (in particular release/1.2)
  * Versions of the daily tasks which previously applied only to master will also be created for that branch.
  * PR tasks will not be generated because they would be redundant with the tasks generated by the change to netci.groovy in master.

### CODE REVIEW

**Comment by dilijev** [comment]
@mmitche How does this look?

@abchatra This will enable daily builds for release/1.2, so it's not Milestone 1.2 per se, but it should be merged into release/1.2 soon. It will be merged back into master but as far as master is concerned these changes are just a refactor with no semantic change.

**Comment by dilijev** [comment]
@digitalinfinity FYI

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
Ahh test ci won't work till the release 1.2 branch is added to tracking in dotnet-ci.  You can still commit this and then tweak later if necessary

**Comment by dilijev** [comment]
@mmitche I verified the change locally using your test script so I'm fairly confident it works as expected :)

**Pull request merged**
