### PR TITLE
Fix Intl built-in function names

### LINKED ISSUE #351: Intl built-in functions have wrong names
[Test262 PR](https://github.com/tc39/test262/pull/505)

### PR DESCRIPTION
**Pull request by goyakin**
Fixes #351.

Changes:

  * Assigned the correct names to getter functions
  * Removed the "bound" prefix from some functions
  * Removed names of returned bound functions

### CODE REVIEW

**Comment by goyakin** [comment]
@akroshg Could you take a look?

**Comment by goyakin** [comment]
Ping...

**Comment by abchatra** [comment]
:+1:

**Comment by goyakin** [comment]
Regenerated the Intl bytecode since it has changed on the `release/1.2` branch.

**Pull request merged**
