### PR TITLE
Enable Linux checks in the master branch.

### PR DESCRIPTION
**Pull request by dilijev**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1060)

### CODE REVIEW

**Comment by dilijev** [comment]
@digitalinfinity @rajatd This fix, once merged in, should add Linux checks to PRs against the master branch such as #1052

**Comment by digitalinfinity** [comment]
LGTM- but why aren't Ubuntu tasks running against this PR?

**Comment by dilijev** [comment]
@digitalinfinity because the change needs to be merged-in before they will run on any PRs. Same frustrating workflow as always. :P

**Comment by digitalinfinity** [comment]
Gah, keep forgetting about that

**Pull request merged**
