### PR TITLE
Merge branch 'release/1.11'

### PR DESCRIPTION
**Pull request by zenparsing**

### CODE REVIEW

**Comment by zenparsing** [comment]
@boingoing The change to `Parse.cpp` is resulting in an test AV.

```
1>ERROR: Test failed to run correctly: non-zero (C0000420) return value from test command ():
1>    ch.exe    -DumpOnCrash -WERExceptionSupport -ExtendedErrorStackForTestHost -BaselineMode -forceNative -off:simpleJit -bgJitDelay:0 -dynamicprofileinput:profile.dpl.UnnamedTest1933  -force:deferparse -args summary -endargs D:\a\1\s\test\es6\default-splitscope.js >D:\a\1\s\test\es6\testout1581 2>&1
1>ERROR: name of output file: D:\a\1\s\test\es6\testout1581; size: 304; creation: Wed Jun 12 19:49:12 2019, last access: Wed Jun 12 19:49:12 2019, now: Wed Jun 12 19:49:15 2019
1>ERROR: bad output file follows ============
1>ASSERTION 4736: (d:\a\1\s\lib\runtime\base\functionbody.cpp, line 4143) this->GetStackNestedFuncParent() != nullptr
1> Failure: (this->GetStackNestedFuncParent() != nullptr)
```

Could this be related to #6157 ?

**Comment by boingoing** [comment]
That does look suspicious. I suppose it also could be a change to stack nested function logic. I'll try and take a look.

**Comment by pleath** [comment]
I'm looking into the merge. I'll let you know if the UT failure persists.

**Comment by pleath** [comment]
Note that the same UT is already failing in unreleased/future.

**Pull request closed without merging**
