### PR TITLE
ToStringTagHelper: Make sure CompoundString has enough capacity

### PR DESCRIPTION
**Pull request by obastemur**
Resize / Grow is expensive. Initialize CompoundString with correct capacity.

### CODE REVIEW

**Comment by digitalinfinity** [comment]
Not sure what's going on with the CI but modulo that, LGTM

**Comment by MSLaguana** [comment]
@dotnet-bot test please

**Comment by MSLaguana** [comment]
@dotnet-bot test this please

**Comment by MSLaguana** [comment]
I suspect the CI isn't fully up and listening to comments yet; However there are legitimate failures here, e.g. https://ci2.dot.net/job/Microsoft_ChakraCore/job/release_1.7/job/_no_jit_shared_osx_osx_test_prtest/67/console:

```
08:18:37 *** Running test #3 (2): Default @@toStringTag built ins
08:18:37 Test threw exception: assert.areEqual failed: expected: [object Math] actual: [object 
08:18:37 FAILED
08:18:37 *** Running test #4 (3): Proxy forwarding behavior
08:18:37 Test threw exception: assert.areEqual failed: expected: [object Math] actual: [object 
08:18:37 FAILED
08:18:37 *** Running test #5 (4): Subclass @@toStringTag override of internal slot based default tag
08:18:37 Test threw exception: assert.areEqual failed: expected: [object StringOverride] actual: [object 
08:18:37 FAILED
08:18:37 *** Running test #7 (6): Invalid @@toStringtag (non-String coercible)
08:18:37 Test threw exception: assert.areEqual failed: expected: [object Map] actual: [object 
08:18:37 FAILED
08:18:37 *** Running test #8 (7): @@toStringTag lookup does not use HasProperty
08:18:37 Test threw exception: assert.areEqual failed: expected: [object Proxied] actual: [object 
08:18:37 FAILED
08:18:37 *** Running test #10 (9): VSO OS Bug 1160433: embedded null characters in toStringTag property value
08:18:37 Test threw exception: assert.areEqual failed: expected: [object before
08:18:37 FAILED
```

**Comment by obastemur** [comment]
@digitalinfinity @MSLaguana Thanks for the review

**Comment by akroshg** [comment]
:shipit:

**Pull request merged**
