### PR TITLE
Use RecyclerRootPtr to make sure we have right sequence of RootAddRef and field assignment in case of RootAddRef throwing OOM

### PR DESCRIPTION
**Pull request by curtisman**

### CODE REVIEW

**Comment by curtisman** [comment]
@mrkmarron Please review.

**Comment by curtisman** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug_static

**Comment by curtisman** [comment]
@dotnet-bot test ubuntu_linux_test_static

**Comment by curtisman** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_test_static

**Comment by mrkmarron** [comment]
LGTM. I am updating the pin logic in TTRuntmeInfoTracker as part of another change so I will make sure to use RecyclerRootPtr in this change as well.

**Pull request merged**
