### PR TITLE
Fix DisableJIT build break with OOPJIT

### PR DESCRIPTION
**Pull request by tcare**
Brings master in line with release/1.4

### CODE REVIEW

**Comment by tcare** [comment]
@dotnet-bot test disablejit tests please

**Comment by tcare** [comment]
@aneeshdk @MikeHolman @leirocks

**Comment by dilijev** [comment]
Doesn't https://github.com/Microsoft/ChakraCore/pull/2331 contain this fix?

**Comment by tcare** [comment]
Beat me to it, nevermind then :)

**Pull request closed without merging**
