### PR TITLE
Make `for (var x = 0 in ...` a syntax error in strict mode

### LINKED ISSUE #1340: For-in initializer should be a syntax error in strict mode
```js
'use strict';
for(var x = 0 in {}) { }
```

Expected: syntax error
Actual: x is initialized to 0

(This should remain working in sloppy mode. See also: https://github.com/tc39/ecma262/pull/614).

### PR DESCRIPTION
**Pull request by ianwjhalliday**
Fixes #1340

### CODE REVIEW

**Comment by ianwjhalliday** [comment]
@bterlson fyi
@Microsoft/chakra-es could some give this a quick review please

**Comment by suwc** [comment]
:shipit:

**Comment by tcare** [comment]
Looks good.

**Comment by akroshg** [comment]
I didn't confirm with the spec. But assume that this is not valid of ```for (let x = 0``` or ```for (const x = 0```. Also ```for (x = 0 in ``` ?

**Comment by ianwjhalliday** [comment]
@akroshg `let` and `const` are already invalid in this case.  I used the existing mechanism to handle `var` + `strict mode`.  `for (x = 0` form without the `var` is to remain unchanged.

**Comment by akroshg** [comment]
@ianwjhalliday - alright, sounds good.

**Comment by bterlson** [comment]
Yay, good stuff!

**Comment by ianwjhalliday** [comment]
Thanks folks!

**Pull request merged**
