### PR TITLE
wasm.simd new binary format  + load/store + constants

### PR DESCRIPTION
**Pull request by Krovatkin**
This PR contains
* updates to `WasmBinaryReader` to decode simd ops in the current spec format 
* regenerated tests for load/store and constants 
* load and store ops
* extract_lane ops 
* ops for generating simd128 constants

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/3185)

### CODE REVIEW

**Comment by Krovatkin** [comment]
@MikeHolman @Cellule 
Please ignore this PR until it clears x-plat tests! Thanks!

**Comment by Krovatkin** [comment]
@Cellule  @MikeHolman Looks like the tests are passing. Could you guys please take a look when you have a moment?

**Comment by Cellule** [comment]
Reviewed 33 of 33 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[lib/Backend/amd64/LowererMDArch.cpp, line 1125 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6qH7f88AR3VQlRDSc:-Kn6qH7f88AR3VQlRDSd:b5d5j4t) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Backend/amd64/LowererMDArch.cpp#L1125)):*
> ```cpp
>     if (CONFIG_FLAG(WasmFastArray) && m_func->GetJITFunctionBody()->IsWasmFunction())
>     {
>         return instr;
> ```

Have you wrote any out of bounds read/writes tests ? I don't remember seeing any

---

*[lib/Backend/amd64/LowererMDArch.cpp, line 1173 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6shj3sCa7kw4KL3Ht:-Kn6shj3sCa7kw4KL3Hu:b-nwi8w1) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Backend/amd64/LowererMDArch.cpp#L1173)):*
> ```cpp
>                 Lowerer::InsertMove(tmp, cmpOpnd, helperLabel);
>                 // ADD tmp, offset
>                 Lowerer::InsertAdd(true, tmp, tmp, IR::IntConstOpnd::New((uint32)src1->AsIndirOpnd()->GetOffset(), tmp->GetType(), m_func, true), helperLabel);
> ```

Remove the `, true` to the `IntConstOpnd` it isn't safe to leave this constant as-is

---

*[lib/Backend/amd64/LowererMDArch.cpp, line 1173 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6sry87wBobbWOtea3:-Kn6sry87wBobbWOtea4:bgje581) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Backend/amd64/LowererMDArch.cpp#L1173)):*
> ```cpp
>                 Lowerer::InsertMove(tmp, cmpOpnd, helperLabel);
>                 // ADD tmp, offset
>                 Lowerer::InsertAdd(true, tmp, tmp, IR::IntConstOpnd::New((uint32)src1->AsIndirOpnd()->GetOffset(), tmp->GetType(), m_func, true), helperLabel);
> ```

What happens if this addition overflows ?

---

*[lib/Backend/amd64/LowererMDArch.cpp, line 1267 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6suv6DHColw-SA7Su:-Kn6suv6DHColw-SA7Sv:bnrydjb) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Backend/amd64/LowererMDArch.cpp#L1267)):*
> ```cpp
>                 Lowerer::InsertMove(tmp, cmpOpnd, helperLabel);
>                 // ADD tmp, offset
>                 Lowerer::InsertAdd(true, tmp, tmp, IR::IntConstOpnd::New((uint32)dst->AsIndirOpnd()->GetOffset(), tmp->GetType(), m_func, true), helperLabel);
> ```

Same concerns as above

---

*[lib/Backend/i386/LowererMDArch.cpp, line 995 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6rfcO7pJw55YBI0MG:-Kn6rfcO7pJw55YBI0MH:b-9mnn47) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Backend/i386/LowererMDArch.cpp#L995)):*
> ```cpp
>             Lowerer::InsertMove(tmp, cmpOpnd, helperLabel);
>             // ADD tmp, offset
>             Lowerer::InsertAdd(true, tmp, tmp, IR::IntConstOpnd::New((uint32)src1->AsIndirOpnd()->GetOffset(), tmp->GetType(), m_func, true), helperLabel);
> ```

remove the `, true` when creating the `IntConstOpnd` this value is controllable by the use and thus must be encoded if needed

---

*[lib/Backend/i386/LowererMDArch.cpp, line 995 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6sbjy0KQk7dHcg90a:-Kn6sbjy0KQk7dHcg90b:baq6eqg) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Backend/i386/LowererMDArch.cpp#L995)):*
> ```cpp
>             Lowerer::InsertMove(tmp, cmpOpnd, helperLabel);
>             // ADD tmp, offset
>             Lowerer::InsertAdd(true, tmp, tmp, IR::IntConstOpnd::New((uint32)src1->AsIndirOpnd()->GetOffset(), tmp->GetType(), m_func, true), helperLabel);
> ```

What happens if the addition overflows ?

---

*[lib/Backend/i386/LowererMDArch.cpp, line 1072 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6seLGJOBoMZ9Fkg9E:-Kn6seLGJOBoMZ9Fkg9F:bnrydjb) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Backend/i386/LowererMDArch.cpp#L1072)):*
> ```cpp
>             Lowerer::InsertMove(tmp, cmpOpnd, helperLabel);
>             // ADD tmp, offset
>             Lowerer::InsertAdd(true, tmp, tmp, IR::IntConstOpnd::New((uint32)dst->AsIndirOpnd()->GetOffset(), tmp->GetType(), m_func, true), helperLabel);
> ```

Same concerns as above

---

*[lib/Runtime/Language/InterpreterStackFrame.cpp, line 7855 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6ofdB5tNgK48nyPHu:-Kn6ofdB5tNgK48nyPHv:b5ttvqg) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Runtime/Language/InterpreterStackFrame.cpp#L7855)):*
> ```cpp
>     {
>         Assert(playout->ViewType < Js::ArrayBufferView::TYPE_COUNT);
>         const uint64 index = ((uint32) GetRegRawInt(playout->SlotIndex) + playout->Offset /* WASM only */) & ArrayBufferView::ViewMask[playout->ViewType];
> ```

we could overflow the index with this math
you should add a cast to `((uint64)(uint32) GetRegRawInt(playout->SlotIndex))` 

---

*[lib/Runtime/Language/InterpreterStackFrame.cpp, line 7897 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6osrAKl6ZO9SyPfgq:-Kn6osrAKl6ZO9SyPfgr:b-ya81ng) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Runtime/Language/InterpreterStackFrame.cpp#L7897)):*
> ```cpp
>     {
>         Assert(playout->ViewType < Js::ArrayBufferView::TYPE_COUNT);
>         const uint64 index = ((uint32)GetRegRawInt(playout->SlotIndex) + playout->Offset /* WASM only */) & ArrayBufferView::ViewMask[playout->ViewType];
> ```

Same as above

---

*[lib/WasmReader/WasmBinaryReader.cpp, line 438 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6ljEj736Qe4QbnQR9:-Kn6ljEj736Qe4QbnQRA:b-oceyy1) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/WasmReader/WasmBinaryReader.cpp#L438)):*
> ```cpp
>         }
> 
>         UINT len;
> ```

nit: please use `uint32` (trying to standardize the types in this file)

---

*[lib/WasmReader/WasmBinaryReader.cpp, line 441 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6o1aZU3UMDZKzbLwD:-Kn6o1aZU3UMDZKzbLwE:b8ri7za) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/WasmReader/WasmBinaryReader.cpp#L441)):*
> ```cpp
>         UINT32 extOpCode = LEB128(len);
>         Assert((WasmOp)(extOpCode) == extOpCode);
>         op = (WasmOp)extOpCode;
> ```

On the proposal the opcodes range from [0, 0x8B]. Why is the value we're reading here matching the range [0x100, 0x18B] ?

---

*[lib/WasmReader/WasmByteCodeGenerator.h, line 153 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6mu6WUXupVtVOsN8i:-Kn6mu6WUXupVtVOsN8j:b-e68fv8) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/WasmReader/WasmByteCodeGenerator.h#L153)):*
> ```objc
>         EmitInfo EmitUnaryExpr(Js::OpCodeAsmJs op, const WasmTypes::WasmType* signature);
>         EmitInfo EmitExtractLane(Js::OpCodeAsmJs op, const WasmTypes::WasmType* signature);
>         
> ```

nit: trailing whitespaces

---

*[lib/WasmReader/WasmParseTree.h, line 101 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6mk1ZrF2l0iPJwinU:-Kn6mk1ZrF2l0iPJwinV:b5jxrks) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/WasmReader/WasmParseTree.h#L101)):*
> ```objc
>     struct WasmLaneNode
>     {
>         uint lane_index;
> ```

nit: This is already a `LaneNode` I feel the `lane` in `lane_index` is redundant. I would just call this `index`

---

*[test/wasm.simd/constTests.js, line 22 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6pTQMB33KpSgWU88Y:-Kn6pTQMB33KpSgWU88Z:b-hr5jun) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/test/wasm.simd/constTests.js#L22)):*
> ```JavaScript
> const instance = new WebAssembly.Instance(module, { "dummy" : { "memory" : memObj } }).exports;
> 
> function moveArgsIntoArray(args, offset, arr) {
> ```

This function is unused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3185)*

**Comment by Cellule** [comment]
Could you write some more test when reading/writing out of bounds or with negative indexes.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-:-Kn6tArdq3br2MoMwj3Q:bv71rno)*

**Comment by Krovatkin** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[lib/Backend/amd64/LowererMDArch.cpp, line 1125 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6qH7f88AR3VQlRDSc:-KnAMTBd4mLDp6jHeFpe:bjzljt8) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Backend/amd64/LowererMDArch.cpp#L1125)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

Have you wrote any out of bounds read/writes tests ? I don't remember seeing any
</blockquote></details>

Yes, both l`oadTests.js` and `storeTests.js` have out-of-bounds tests. For example, https://github.com/Krovatkin/ChakraCore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/test/wasm.simd/loadTests.js#L64

---

*[lib/Backend/amd64/LowererMDArch.cpp, line 1173 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6sry87wBobbWOtea3:-KnAMjWzDrbT2Nu_baZK:b-tln2x4) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Backend/amd64/LowererMDArch.cpp#L1173)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

What happens if this addition overflows ?
</blockquote></details>

The carry bit is set and the very next `JB` is taken. 

---

*[lib/Backend/i386/LowererMDArch.cpp, line 995 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6sbjy0KQk7dHcg90a:-KnAN-SaH8GCuIx6vGll:b-tln2x4) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Backend/i386/LowererMDArch.cpp#L995)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

What happens if the addition overflows ?
</blockquote></details>

The carry bit is set and the very next `JB` is taken. 

---

*[lib/Runtime/Language/InterpreterStackFrame.cpp, line 7855 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6ofdB5tNgK48nyPHu:-KnAN8J9zLMY31w3tSxL:bymou3g) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Runtime/Language/InterpreterStackFrame.cpp#L7855)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

we could overflow the index with this math
you should add a cast to `((uint64)(uint32) GetRegRawInt(playout->SlotIndex))` 
</blockquote></details>

A good catch

---

*[lib/WasmReader/WasmBinaryReader.cpp, line 441 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6o1aZU3UMDZKzbLwD:-KnANULb6PJqwVkl0-rb:b-pjg9ha) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/WasmReader/WasmBinaryReader.cpp#L441)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

On the proposal the opcodes range from [0, 0x8B]. Why is the value we're reading here matching the range [0x100, 0x18B] ?
</blockquote></details>

Ah, my bad, I seem to have misread the spec. A good catch! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3185)*

**Comment by Krovatkin** [comment]
@Cellule I added a few tests to test a **wraparound** behaviour (**in addition** to the existing out-of-bounds ones). Hopefully, we have a good coverage now.

**Comment by Krovatkin** [comment]
@Cellule ping :-)

**Comment by Cellule** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[lib/Runtime/Language/InterpreterStackFrame.cpp, line 7855 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6ofdB5tNgK48nyPHu:-KnLUAP2oktGtCWi6g1r:b-27nkaa) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Runtime/Language/InterpreterStackFrame.cpp#L7855)):*
<details><summary><i>Previously, Krovatkin (Nick Korovaiko) wrote…</i></summary><blockquote>

A good catch
</blockquote></details>

Why use signed type for the ViewMask ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3185)*

**Comment by Krovatkin** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[lib/Runtime/Language/InterpreterStackFrame.cpp, line 7855 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6ofdB5tNgK48nyPHu:-KnLZ4oJxhgtmAO9eygt:bcako0v) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/Runtime/Language/InterpreterStackFrame.cpp#L7855)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

Why use signed type for the ViewMask ?
</blockquote></details>

masks are `uint32`, but indices can now be greater than `ULONG_MAX`. If we don't sign-extend the mask w/ `(int64)(int32)`, the mask will mask out the higher 32-bit of the index.  We could switch to 64-bit masks, but it might be unnecessary since 4GB alignments are unlikely.  This seems to be a variation of the overflow problem you pointed out. I added a few tests to test for this masking/wraparound behaviour.  

---

*[lib/WasmReader/WasmByteCodeGenerator.h, line 153 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6mu6WUXupVtVOsN8i:-KnL_ptpN287OgCCWRGK:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/WasmReader/WasmByteCodeGenerator.h#L153)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

nit: trailing whitespaces
</blockquote></details>

Done.

---

*[lib/WasmReader/WasmParseTree.h, line 101 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-Kn6mk1ZrF2l0iPJwinU:-KnL_oxEsDsOz-PGupeO:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/bbe308824d9cfdc50b00214a0db7b35f0239bf43/lib/WasmReader/WasmParseTree.h#L101)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

nit: This is already a `LaneNode` I feel the `lane` in `lane_index` is redundant. I would just call this `index`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3185)*

**Comment by Cellule** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3185#-:-KnLdQ33-x15ysp0SlVX:bnfp4nl)*

**Comment by Krovatkin** [comment]
@arunetm Can you please help to merge this PR whenever you have a mnt? Thanks!

**Comment by Krovatkin** [comment]
Per Arun's recommendation squashed the last commit.

**Comment by Krovatkin** [comment]
@dotnet-bot test Windows ci_disablejit_x64_debug please

**Comment by Krovatkin** [comment]
@arunetm fyi the tests passed

**Comment by arunetm** [comment]
@Cellule  can you please help to merge this change to the WASM.Simd branch? 
I am running into access issues with ChakraHub and we needed to merge this change sooner to prepare the remaining wasm.simd PR's.

**Comment by Krovatkin** [comment]
@Cellule thank you very much for your help!

**Pull request merged**
