### PR TITLE
Change toolset version for VS2017 and minor cleanup

### PR DESCRIPTION
**Pull request by curtisman**

### CODE REVIEW

**Comment by tcare** [comment]
Looks good - I'm not sure why the others failed though. Transient issue?

**Comment by jianchun** [comment]
> Looks good - I'm not sure why the others failed though. Transient issue?

"process.h" unavailable xplat

**Comment by tcare** [comment]
Oh interesting, the OSX Jenkins builds say they don't know why the build failed. E.g. https://ci.dot.net/job/Microsoft_ChakraCore/job/master/job/osx_osx_debug_static_prtest/993/

**Comment by jianchun** [comment]
> Oh interesting, the OSX Jenkins builds say they don't know why the build failed. E.g. https://ci.dot.net/job/Microsoft_ChakraCore/job/master/job/osx_osx_debug_static_prtest/993/

I always go read "Console Output", didn't note what's on that page...

**Pull request merged**
