### PR TITLE
Moved propertyIs{Enumarable_2 -> Enumerable}.baseline to match correction in #227. Fixes failing slow test.

### PR DESCRIPTION
**Pull request by dilijev**

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test slow please

**Comment by ianwjhalliday** [comment]
I just took a look at this test and on the surface it looks like a pretty garbage test.  I'm inclined to replace it with something small and reasonable.  Hold up while I take a moment to investigate further.

**Comment by dilijev** [comment]
OK, I'll wait.

**Comment by dilijev** [comment]
Now that you mention it the _2 suffix could be removed at a minimum.

**Comment by ianwjhalliday** [comment]
Yeah that'd be great, removing the _2.

The test is lazy but I'm not inclined to fix it up at this moment.  If I have some spare time later today I'll take a stab at it, but otherwise it will be fine if forgotten.

**Comment by dilijev** [comment]
OK I've renamed the test and updated the corresponding rlexe.xml with the new filename.

**Comment by dilijev** [comment]
@dotnet-bot test slow please

**Comment by ianwjhalliday** [comment]
:+1:

**Pull request merged**
