### PR TITLE
OS#16092623: When we have an accessor cache hit on a setter, we still need to check for exception conditions such as undefined setter in strict mode

### PR DESCRIPTION
**Pull request by pleath**

### CODE REVIEW

**Comment by MikeHolman** [comment]
How are these even getting in the cache? Do cache hits from JIT already handle this?

**Comment by pleath** [comment]
You can execute a given store with different objects that share a type. Since the type doesn’t tell you anything about the value of the setter, we can populate the cache when we execute a valid setter, then hit the cache when we come back with a null or default setter. We could try to use different types based on the setter value, but that’s a pretty wrinkly change, and I doubt it’s worth it.

**Comment by rhuanjl** [comment]
Could it be possible instead to make the null/default setter be a function that throws if in strict mode? Then the strict mode check only occurs once the setter is called and only if it is the default/null setter rather than needing to check a) is this the default/null setter AND b) are we in strict mode before calling any setter.

This may be impracticable - I haven't looked at how you handle getters/setters - but just a thought I had looking at this.

**Comment by akroshg** [comment]
is there a way to add the test for this?

**Comment by pleath** [comment]
@MikeHolman I never answered the part of your question about how jitted code handles cache hits currently. Since this StFld will call a setter, we don't generate an inline cache check. We just generate a call the helper, which checks the cache and calls the setter. If we inline the setter, then the inlining checks will fail.

**Comment by pleath** [comment]
@dotnet-bot please test Windows 10 ci_slow_x64_debug

**Pull request merged**
