### PR TITLE
Fix VS2013 build break

### LINKED ISSUE #2026: [Legacy] Illegal argument to sizeof
https://github.com/Microsoft/ChakraCore/wiki/Build-Status#legacy-builds

`
lib\Runtime\Library\WebAssemblyTable.cpp(124): error C2070: 'unknown': illegal sizeof operand [lib\Runtime\Library\Chakra.Runtime.Library.vcxproj]
`
`
lib\Runtime\Library\WebAssemblyTable.cpp(124): error C2338: sizeof(m_maxLength) == sizeof(uint32) [lib\Runtime\Library\Chakra.Runtime.Library.vcxproj]
`

### PR DESCRIPTION
**Pull request by MikeHolman**
Fixes #2026

### CODE REVIEW

**Comment by MikeHolman** [comment]
@dotnet-bot test dev12 tests

**Comment by digitalinfinity** [comment]
:shipit:

**Comment by MikeHolman** [comment]
@dotnet-bot test legacy tests

**Comment by MikeHolman** [comment]
@dotnet-bot test legacy

**Comment by MikeHolman** [comment]
@dotnet-bot test legacy tests

**Comment by dilijev** [comment]
Looks like you fixed #2026 but revealed another issue...?

**Comment by dilijev** [comment]
@MikeHolman You'll want to retarget this PR to release/1.4 so that the fix makes it into all affected branches.

**Comment by MikeHolman** [comment]
Unfortunately this doesn't fix all the build issues, only the wasm ones. Someone will still need to fix the remaining issues. Is it even worth merging without the other half?

**Comment by dilijev** [comment]
@MikeHolman I'd say any fix is worth merging but we can wait until we fix the remaining issues. If you merge yours without the other fixes it will be easier because you don't need to coordinate the remaining fixes.

**Comment by dilijev** [comment]
Included in https://github.com/Microsoft/ChakraCore/pull/2207

**Pull request closed without merging**
