### PR TITLE
Branchify the Chakra repo

### PR DESCRIPTION
**Pull request by mmitche**
Also mark the Windows images as using 'latest-or-auto' to pick up dynamic pooling

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dilijev Merge at your leisure.  We can then update the home page badges.

**Comment by dilijev** [comment]
@mmitche Thanks, merging.

**Pull request merged**
