### PR TITLE
fix modFunctionIndex is missing on copy

### PR DESCRIPTION
**Pull request by obastemur**
OS14289876 credit goes to @jianchun

### CODE REVIEW

**Comment by jianchun** [comment]
>                 bucketCount = 0;

If `other.Count() == 0` (because `count == freeCount` but `bucketCount != 0`), this could result in bad modFunctionIndex.

---
Refers to: lib/Common/DataStructures/BaseDictionary.h:153 in 1339070. [](commit_id = 1339070d172f6dc7da9aa3e1d5a2a21a6bc43e90, deletion_comment = False)

**Comment by jianchun** [comment]
>             this->freeCount = 0;

Here modFunctionIndex missing update.

---
Refers to: lib/Common/DataStructures/BaseDictionary.h:302 in 1339070. [](commit_id = 1339070d172f6dc7da9aa3e1d5a2a21a6bc43e90, deletion_comment = False)

**Comment by jianchun** [comment]
>                 bucketCount = 0;

Missing modFunctionIndex update.

---
Refers to: lib/Common/DataStructures/BaseDictionary.h:311 in 1339070. [](commit_id = 1339070d172f6dc7da9aa3e1d5a2a21a6bc43e90, deletion_comment = False)

**Comment by jianchun** [comment]
>             uint newBucketCount = SizePolicy::GetBucketSize(newSize, &modFunctionIndex);

In theory this is not safe. `this->modFunctionIndex` is changed while other variables are not (`newSize`, `newBucketCount` are using temporaries). If anything below failed in the middle we'd end up with bad `modFunctionIndex`. To be consistent and safer, consider also use a temporary "newModFunctionIndex" and be sure use it during rehash.

---
Refers to: lib/Common/DataStructures/BaseDictionary.h:1021 in 1339070. [](commit_id = 1339070d172f6dc7da9aa3e1d5a2a21a6bc43e90, deletion_comment = False)

**Comment by jianchun** [comment]
Please also fix `WeaklyReferencedKeyDictionary::Resize() and Initialize()`, both have the same unsafe pattern of changing `modFunctionIndex` before everything succeeds.

**Comment by obastemur** [comment]
@jianchun please consider that the mod index set by previous dictionary was working for that dictionary.

**Comment by jianchun** [comment]
> @jianchun please consider that the mod index set by previous dictionary was working for that dictionary.

Yes it is a bug. But that's not the only problem. Several from my comments are apparent bugs too. The observation is that we have similar amount of failures in `WeaklyReferencedKeyDictionary`, which was not covered by current change. Why not do a thorough review and fix?

**Comment by obastemur** [comment]
Well, it wasn’t a through review but your comments on vso with a credit on description.

**Comment by obastemur** [comment]
@jianchun Thank you for the review and pointers. Is it good to go?

**Pull request merged**
