### PR TITLE
fix assert in ObjTypeSpecFldInfo::GetFixedFieldIfAvailableAsFixedFunction

### PR DESCRIPTION
**Pull request by MikeHolman**
Assert isn't valid, as there isn't always a guarantee about equivalence. Instead, we should do a check in the API.

### CODE REVIEW

**Comment by rajatd** [comment]
Do you have a test case for this?

**Comment by MikeHolman** [comment]
Sure, I've added one.

**Comment by rajatd** [comment]
1. We dont have polymorphic inlining for apply targets.
2. We collect fixed field info at workitem creation for polymorphic inlining only if the method properties are at equivalent slots in their owner object types.

By (2), the assert makes sense. We should, however, not call TryOptimizeCallInstrWithFixedMethod from InlineApplyWithoutArrayArgument if applyTargetInfo is null.

**Comment by MikeHolman** [comment]
Makes sense. I'll make that change.

**Pull request merged**
