### PR TITLE
Merge remote-tracking branch 'origin/master' into linux

### PR DESCRIPTION
**Pull request by jianchun**
Merge remote-tracking branch 'origin/master' into linux

### CODE REVIEW

**Comment by dilijev** [comment]
@jianchun Are you trying to merge master into linux again, or are you trying to bring changes from the linux branch back to master?

In any case, it might be good to have a more descriptive commit message and PR title.

**Comment by jianchun** [comment]
> Are you trying to merge master into linux again, or are you trying to bring changes from the linux branch back to master?

@dilijev I thought the title is clear enough? ```Merge ... into linux```. The other direction would be ```Merge linux into master```.

**Comment by jianchun** [comment]
@dilijev Thanks for your warning, now I noticed something is wrong! This PR is incorrect. I meant to target ```linux``` branch, but this PR incorrectly targets ```master``` branch.

**Comment by jianchun** [comment]
Replacing this with #210.

**Pull request closed without merging**
