### PR TITLE
Moving RS4 changes to master

### PR DESCRIPTION
**Pull request by aneeshdk**
This change includes the following fixes
-	Added a new mechanism to mark reentrancy. When a helper calls into user code we will have to explicitly either set the implicit call flags or mark that call as reentrancy safe
-	Added checks in lowerer to confirm that we emit an implicit call bailout check after a helper call
-	Added failfasts, under a config flag, to validate the int range assumptions made in Globopt
-	Added check to make sure an opcode that can't have implicit call do not lower a helper call that can have implicit calls
-	Moved the reentrancy lock assert to Recycler right before dispose
-	Fixed an issue where during expression evaluation we were not restoring the updated block id in case of a parenthesis in destructed params
-	Along with ignoring null valuetype bit, also ignore undefined bit in the IsSimilar function as ToDefinite() strips out the undefined bit
-	Assert that we don't have a reentrancy lock when calling Dispose in a deterministic way.

### CODE REVIEW

**Comment by MSLaguana** [comment]
Is there a reason you didn't merge this to 1.8?

**Comment by sigatrev** [comment]
The following files have some bad formatting changes:
    lib/Backend/GlobOpt.cpp
    lib/Backend/Lower.cpp
    lib/Backend/LowerMDShared.cpp
    lib/Common/Memory/Recycler.cpp
    lib/Parser/Parse.cpp
    lib/Runtime/Language/InterpreterStackFrame.cpp
    lib/Runtime/Language/JavascriptOperators.cpp

otherwise LGTM

**Comment by boingoing** [comment]
Looks good to me

**Comment by aneeshdk** [comment]
@MSLaguana As these are not security fixes we don't have to service them on release/1.8. Putting them in master and letting it flow seems the best thing to do.

**Comment by tcare** [comment]
That's how we've done previous ones as well. Previous release changes go into the active working branch.

**Comment by MSLaguana** [comment]
@aneeshdk ok. I thought it might have been simpler to take them to the 'closer' branch to where they came from.

**Comment by Penguinwizzard** [comment]
@tcare For RS3, at least, we merged the changes into release/1.6. I'm in favor of doing the merge to release/1.8 as well, as that would make the branches identical (modulo whitespace), and as release/1.8 is the current serviced public branch, we'd be able to avoid having to potentially make separate fixes for RS4 and GitHub.

**Comment by tcare** [comment]
@curtisman opinion on merging to a release branch?

**Comment by curtisman** [comment]
master is fine as these are not security fixes.   We can reconsider it next time.

**Pull request merged**
