### PR TITLE
WASM - Encode int64 constants

### LINKED ISSUE #2776: WASM - Int64 Constant encoding (3d)
Check int64 constant security encoding

### PR DESCRIPTION
**Pull request by Cellule**
Fixes #2776

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/2817)

### CODE REVIEW

**Comment by Cellule** [comment]
@dotnet-bot test OSX static_osx_osx_debug please

**Comment by Cellule** [comment]
@MikeHolman can you take a look at this please ?

**Comment by Cellule** [comment]
@LouisLaf @rajatd Can you take a look at this please ?

**Comment by rajatd** [comment]
:shipit:

**Pull request merged**
