### PR TITLE
Update Jsrt Utf8 types and naming

### LINKED ISSUE #1918: JSRT: uint8_t vs char for Utf8 interface
Some JSRT API accept `char` for Utf8 named functions while others `uint8_t`.

We had a small discussion on this. Shared my opinion below;

 - `char` is more developer friendly and all C / IO comes with `char`.
     If a developer has nothing to do with utf8 encoding / flags etc.
     there is no reason for her/him to use `unsigned`. At least I can’t think of any.
 
 - No matter what we choose for external type, internally we will continue using `unsigned`.

 - Having `char` argument may make ASCII based string interface obsolete.

/cc @agarwal-sandeep  @curtisman @jianchun @liminzhu

### PR DESCRIPTION
**Pull request by obastemur**
Fixes #1918

### CODE REVIEW

**Comment by obastemur** [comment]
Updated native tests to match with new API. Will send a separate PR to Chakra-Samples accordingly.

**Comment by dilijev** [comment]
/cc @liminzhu @digitalinfinity @Cellule 

This change is supposed to target `release/1.4` so that these changes are contained in ChakraCore 1.4.0, right?

**Comment by dilijev** [comment]
@dotnet-bot test Windows 7 daily_dev12_x64_release please

That legacy test should be enough to tell if there are any issues.

Also:
@dotnet-bot test nojit tests please

Changes LGTM but wait for tests and another person to sign off.

**Comment by obastemur** [comment]
@dilijev Windows 7 test fails are unrelated to this PR. IIRC there was another PR targeting those?

**Comment by dilijev** [comment]
@obastemur if this is targeting release/1.4, those tests should pass now as that fix was merged in last week. I'll try again:

@dotnet-bot test nojit please

It appears there are nojit failures unique to master, however. I'll open an issue to track that.

**Comment by dilijev** [comment]
In order to target release/1.4 you would probably need to cherry-pick your change to a new branch and push that to the PR branch `jsrt_utf8`

**Comment by dilijev** [comment]
@dotnet-bot test nojit tests please

**Comment by obastemur** [comment]
> In order to target release/1.4 you would probably need to cherry-pick your change to a new branch and push that to the PR branch jsrt_utf8

I could also target straight release/1.4 with a single commit but what we have on master will be a different story.

**Comment by dilijev** [comment]
As per the offline discussion, keep this PR targeted to master. We can always cherry-pick the changes back to release/1.4 if we decide we need to but that looks unlikely at this point.

You *could* fix the nojit issues here if you want to -- but if it's a nontrivial change, you can make a separate PR for that or leave the fixes for later since in general it's not hurting dev productivity.

**Comment by dilijev** [comment]
I keep hoping that close/reopen will remove the extra checks that failed. You can force the CI to reset by adding a new commit (or rebase, etc.)

**Comment by dilijev** [comment]
@obastemur I added #2244 to track the disablejit breaks.

**Pull request closed without merging**
