### PR TITLE
Change build and test scripts to exit without failure if the expected toolchain does not exist.

### PR DESCRIPTION
**Pull request by dilijev**

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug please

**Comment by dilijev** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug please

**Comment by dilijev** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug please

**Comment by dilijev** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug please

**Comment by dilijev** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug please

**Comment by dilijev** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_release please

**Comment by dilijev** [comment]
@digitalinfinity @jianchun @obastemur After the Jenkins tasks regenerate I'll want to merge this in first to unblock the other PRs. Do the changes look okay to you?

**Comment by dilijev** [comment]
Since we still have a dependency on bash in any case, I'm reverting any changes related to removing the dependency on bash. The set of changes is now intended just to make the builds pass in the case that the expected toolchain (clang 3.8) does not exist on the build machine.

**Comment by obastemur** [comment]
can we have this done on other branch ? See https://github.com/Microsoft/ChakraCore/issues/937

**Comment by dilijev** [comment]
Yes, I'm sorry about the disruption on this branch. I'll work with @mmitche to have a better way but it's not too straighforward.

For the moment, we need to unblock the branch so these changes should be merged directly in.

**Pull request merged**
