### PR TITLE
Fix ARM nojit build.

### PR DESCRIPTION
**Pull request by curtisman**
Need to disable interpreter dynamic thunks

Fixes https://github.com/Microsoft/ChakraCore/issues/169

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test nojit please

**Comment by dilijev** [comment]
@curtisman Almost! (Fixed the disablejit arm_* builds but broke the normal arm_* builds.)

**Comment by curtisman** [comment]
@dotnet-bot test nojit please

**Comment by dilijev** [comment]
LGTM, all tests passed. Signing off.

**Pull request merged**
