### PR TITLE
wasm: Add sqrt_flt

### PR DESCRIPTION
**Pull request by commonlisp**

### CODE REVIEW

**Comment by commonlisp** [comment]
This opcode is needed for AngryBots. It should rebase cleanly with @MikeHolman #532.

**Comment by naturaltransformation** [comment]
@dotnet-bot  test this please

**Comment by commonlisp** [comment]
@dotnet-bot test this please

**Comment by commonlisp** [comment]
@dotnet-bot test this please

**Comment by MikeHolman** [comment]
lgtm

**Comment by Cellule** [comment]
I cherry-picked this commit and merged it to WebAssembly branch

**Pull request closed without merging**
