### PR TITLE
Statically link C++ Runtime into ChakraCore.dll.

### PR DESCRIPTION
**Pull request by dilijev**
(Request from TypeScript team.)

This enables us to support running applications developed against
ChakraCore.dll even if the C++ Runtime is not installed on the machine.

Add this to Build/Chakra.Build.Default.props to set the flag for the entire
build. If the user wishes to dynamically link the C++ Runtime, build with e.g.

msbuild ... "/p:RuntimeLib=dynamic_library"

(or any other value for RuntimeLib) to disable the static linking.

Confirmed that ch.exe is now able to run a hello.js file on a machine without
the C++ Runtime installed. (Dynamically linked ChakraCore.dll fails on the same
machine complaining of missing DLLs.)

Note:
* Increases x64_debug ChakraCore.dll size by about 1MB.
* Increases x64_release ChakraCore.dll size by about 100KB.
* Increases x64_release_pogo ChakraCore.dll size by about 150KB.

### CODE REVIEW

**Comment by dilijev** [comment]
@curtisman @paulvanbrenk Review please?

**Comment by paulvanbrenk** [comment]
LGTM

**Comment by dilijev** [comment]
(Note: Increases ChakraCore.dll size by about 1MB.)

**Comment by dilijev** [comment]
@MikeHolman Any idea why compiling the C++ Runtime statically into ChakraCore would cause a test failure in asm.js?

http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/x64_debug_prtest/1761/console
```
15:12:19 1>ERROR: Test failed to run correctly: diffs from baseline (D:\j\workspace\x64_debug_prtest4a3ea965\test\AsmJs\invalidIntLiteral.baseline):
15:12:19 1>    ch.exe    -DumpOnCrash -WERExceptionSupport -ExtendedErrorStackForTestHost -forceNative -off:simpleJit -bgJitDelay:0 -dynamicprofileinput:profile.dpl.UnnamedTest1886  -testtrace:asmjs -simdjs -force:deferparse D:\j\workspace\x64_debug_prtest4a3ea965\test\AsmJs\invalidIntLiteral.js >testout1443 2>&1
15:12:19 1>ERROR: name of output file: D:\j\workspace\x64_debug_prtest4a3ea965\test\AsmJs\testout1443; size: 278; creation: Tue Jul 26 15:13:04 2016, last access: Tue Jul 26 15:13:04 2016, now: Tue Jul 26 15:13:04 2016
15:12:19 1>ERROR: bad output file follows ============
15:12:19 1>Var declaration with integer literal outside range [-2^31, 2^32)
15:12:19 1>Asm.js compilation failed.
15:12:19 1>
15:12:19 1>invalidIntLiteral.js(25, 3)
15:12:19 1>	Asm.js Compilation Error function : None::f
15:12:19 1>	Int literal must be in the range [-2^31, 2^32)
15:12:19 1>
15:12:19 1>Asm.js compilation failed.
15:12:19 1>-2147483649
15:12:19 1>-137438953473
15:12:19 1>ERROR: end of bad output file  ============
15:12:19 3>Summary: AsmJs had 76 tests; 1 failures
```

**Comment by MikeHolman** [comment]
No idea. Possibly some timing issue with flushing output? Possibly -force:deferparse isn't being respected for some reason?

**Comment by dilijev** [comment]
@dotnet-bot
test Windows arm_debug please
test Windows x64_debug please

**Pull request merged**
