### PR TITLE
stack/error: disable it partially for xplat CI

### PR DESCRIPTION
**Pull request by obastemur**
reduces test run time to 1/3

I've got bunch of CI failures due to this test is timing out (xplat). disabling a part of it helps to save it from whole run is going timeout.

I did look into the details and saw `interlocked_increment` was playing a big role on the timeout. CH loses its' share from OS scheduler.. If CI machine is busy, it takes UNKNOWN amount of time for VM to get back the share needed.. well it loses again very soon because of the same reason.

So, I won't add (todo, enable this) or open an issue to track this.  Also, see the comments on the test file.

### CODE REVIEW

**Comment by jackhorton** [comment]
Is it worth commenting somewhere that interlocked_increment could improve such that we don't spend as much time waiting on locks?

**Comment by obastemur** [comment]
> Is it worth commenting somewhere that interlocked_increment could improve such that we don't spend as much time waiting on locks?

that would be a bit vague?

**Comment by jianchun** [comment]
LGTM

**Comment by obastemur** [comment]
@jianchun Thanks for the review

**Pull request merged**
