### PR TITLE
[Preview][Archive] Enable WScript.RegisterModuleSource() in ch.exe

### PR DESCRIPTION
**Pull request by suwc**
Disclaimer: this is just to archive one way to do it in case it is useful. Not intended for merge as is.

### CODE REVIEW

**Comment by suwc** [comment]
@boingoing, FYI, feel free to own it or ditch it. Thanks!

**Comment by dilijev** [comment]
@boingoing do you think we should merge this?

**Comment by boingoing** [comment]
@dilijev Yeah, we should probably clean it up and get it checked-in. We need this if we want to run exprgen with ch and test module code. We could also move all the full module tests into core. Not a high priority, but this should get us most of the way there.

**Comment by rhuanjl** [comment]
@dilijev  @boingoing this is now a duplicate the feature has already been added by obastemur in #4582

**Pull request closed without merging**
