### PR TITLE
[WASM SIMD] Release registers in shuffle

### PR DESCRIPTION
**Pull request by penzn**
Release bytecode locations for WASM SIMD shuffle instruction. Use
correct order of operands in `IRBuilderAsmJs` as it expects processing
of uses before processing of defs.

For #5898

### CODE REVIEW

**Comment by penzn** [comment]
@MikeHolman this fixes the order in which args are processed in for some operations in IRBuilderAsmJs, which led to the crash when releasing bytecode registers for shuffle.

**Comment by arunetm** [comment]
@MikeHolman ping :)

**Comment by penzn** [comment]
@MikeHolman branch is updated,, should be good to merge after CI passes.

**Comment by MikeHolman** [comment]
I already merged it. Looks like GitHub got confused about me merging and you updating the branch at the same time. It's in, so I'll close the PR.

**Pull request closed without merging**
