### PR TITLE
Add WebAssembly.Table support

### LINKED ISSUE #1874: WASM - Import table
Support importing a table to the wasm module
depends on new Js API
https://github.com/WebAssembly/design/blob/binary_0xc/BinaryEncoding.md#import-entry

### LINKED ISSUE #1876: WASM - Export Table
Support exporting the table our of the wasm module
https://github.com/WebAssembly/design/blob/binary_0xc/BinaryEncoding.md#export-entry

### LINKED ISSUE #1879: WASM - Indirect call trap
Trap on invalid indirect call (out of bounds and invalid signature)

### PR DESCRIPTION
**Pull request by MikeHolman**
Closes #1874 
Closes #1876 
Closes #1879 
Closes #1879

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1959)

### CODE REVIEW

**Comment by Cellule** [comment]
Could you do one round of rebase to resolve the conflicts ?

**Comment by Cellule** [comment]
Reviewed 27 of 46 files at r1, 9 of 9 files at r2.
Review status: 36 of 46 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWA6dlCxL9tX_Cmweuk:-KWA6dlCxL9tX_Cmweul:bf221ui) (no related file):*
> WASM_SECTION(Element              , "element"            , fSectNone  , IndirectFunctionTable)

In WasmSections.h the precedence for the Element section is no longer true.
Since you can import a table, you might not have an `IndirectFunctionTable` section.
Same for DataSegment with Memory.

Actually, I am looking at the WasmSections and I'm starting to think we could remove the precedence altogether, there 
is very little use for it anymore

---

*[lib/Backend/IRBuilderAsmJs.cpp, line 1252 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWABXcac6_gIEzW-9iZ:-KWABXcac6_gIEzW-9i_:b-pntkyh) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Backend/IRBuilderAsmJs.cpp#L1252)):*
> ```cpp
>         IR::RegOpnd * baseOpnd = BuildSrcOpnd(GetRegSlotFromVarReg(instance), TyVar);
>         IR::RegOpnd * indexOpnd = BuildSrcOpnd(GetRegSlotFromIntReg(slotIndex), TyUint32);
>         
> ```

nit: trailing whitespace

---

*[lib/Backend/Lower.cpp, line 8219 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAEM-jurZ6rLtPkDQf:-KWAEM-k75fUjnMWcyOq:bmhk7w2) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Backend/Lower.cpp#L8219)):*
> ```cpp
> 
>         IR::Opnd* errReg = IR::RegOpnd::New(TyInt32, m_func);
>         InsertMove(errReg, IR::IntConstOpnd::NewFromType(SCODE_CODE(WASMERR_TableIndexOutOfRange), TyInt32, m_func), instr);
> ```

Do you need to move the const to a reg? Can't you just pass the IntConstOpnd to GenerateThrow ?

---

*[lib/Backend/Lower.cpp, line 8268 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAGe6QuPbxoxTXt0kA:-KWAGe6QuPbxoxTXt0kB:b2nregs) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Backend/Lower.cpp#L8268)):*
> ```cpp
> 
>     IR::Opnd* errReg = IR::RegOpnd::New(TyInt32, m_func);
>     InsertMove(errReg, IR::IntConstOpnd::NewFromType(SCODE_CODE(WASMERR_SignatureMismatch), TyInt32, m_func), instr);
> ```

Same as above 

---

*[lib/Backend/Lower.cpp, line 8268 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAInq00GPQgmOPgBm-:-KWAInq00GPQgmOPgBm0:b-qlrvxr) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Backend/Lower.cpp#L8268)):*
> ```cpp
> 
>     IR::Opnd* errReg = IR::RegOpnd::New(TyInt32, m_func);
>     InsertMove(errReg, IR::IntConstOpnd::NewFromType(SCODE_CODE(WASMERR_SignatureMismatch), TyInt32, m_func), instr);
> ```

In interpreter we throw `WASMERR_TableIndexOutOfRange` when out of range and `JSERR_Property_NeedFunction` if nullptr
Here we throw `WASMERR_SignatureMismatch`, could throw the right error message.

---

*[lib/Backend/Lower.h, line 419 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAGjnpPpHnNJGAVL4a:-KWAGjnpPpHnNJGAVL4b:b-psfaw) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Backend/Lower.h#L419)):*
> ```objc
>     IR::Instr *     LowerBailOnException(IR::Instr* instr);
>     IR::Instr *     LowerReinterpretPrimitive(IR::Instr* instr);
>     IR::Instr *     LowerLdAsmJsFunc(IR::Instr* instr);
> ```

Not implemented function

---

*[lib/Parser/rterrors.h, line 380 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAGpDsNqpXlZ_7YtXX:-KWAGpDsNqpXlZ_7YtXY:b1fhxo) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Parser/rterrors.h#L380)):*
> ```objc
> RT_ERROR_MSG(WASMERR_NeedTableObject, 5678, "%s is not a WebAssembly.Table", "WebAssembly.Table object expected", kjstTypeError, 0)
> RT_ERROR_MSG(WASMERR_NeedWebAssemblyFunc, 5679, "%s is not a WebAssembly exported function", "WebAssembly exported function expected", kjstTypeError, 0)
> RT_ERROR_MSG(WASMERR_SignatureMismatch, 5680, "%s called with unexpected signature", "Function called with unexpected signature", kjstWebAssemblyRuntimeError, 0)
> ```

I would say `called with invalid signature`

---

*[lib/Runtime/Language/AsmJsTypes.h, line 896 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAHxceKkAgH8Sh6bvJ:-KWAHxcfn_TJYZe_CHAg:b9ow9bf) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Language/AsmJsTypes.h#L896)):*
> ```objc
>                               mSignature(nullptr),
> #endif
>                               mWasmModule(nullptr){}
> ```

This is only get/set in Wasm, should move inside the `#ifdef ENABLE_WASM`

---

*[lib/Runtime/Library/WebAssemblyInstance.cpp, line 324 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAKfhJIjZNIsQqRmsE:-KWAKfhJIjZNIsQqRmsF:bvno5ue) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyInstance.cpp#L324)):*
> ```cpp
>         if (!JavascriptFunction::Is(prop))
>         {
>             JavascriptError::ThrowTypeError(ctx, WASMERR_InvalidImport);
> ```

Could we make that `JSERR_Property_NeedFunction`

---

*[lib/Runtime/Library/WebAssemblyInstance.cpp, line 339 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAKrmyukuSpfEYUV8J:-KWAKrmyukuSpfEYUV8K:bwws1my) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyInstance.cpp#L339)):*
> ```cpp
>         if (!WebAssemblyMemory::Is(prop))
>         {
>             JavascriptError::ThrowTypeError(ctx, WASMERR_InvalidImport);
> ```

Use `WASMERR_NeedMemoryObject`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1959)*

**Comment by MikeHolman** [comment]
Review status: 36 of 46 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWA6dlCxL9tX_Cmweuk:-KWA_TuHmgiK-JgGjRxp:bsl8e4s) (no related file):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> > WASM_SECTION(Element              , "element"            , fSectNone  , IndirectFunctionTable)
> 
> In WasmSections.h the precedence for the Element section is no longer true.
> Since you can import a table, you might not have an `IndirectFunctionTable` section.
> Same for DataSegment with Memory.
> 
> Actually, I am looking at the WasmSections and I'm starting to think we could remove the precedence altogether, there 
> is very little use for it anymore
</details>
Yeah, I agree. For now I'll just remove the precedence that is relevant to this PR

---

*[lib/Backend/IRBuilderAsmJs.cpp, line 1252 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWABXcac6_gIEzW-9iZ:-KWAaGAZjvEaaCeQTkTt:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Backend/IRBuilderAsmJs.cpp#L1252)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> nit: trailing whitespace
</details>
Done.

---

*[lib/Backend/Lower.cpp, line 8268 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAInq00GPQgmOPgBm-:-KWAb9fiWUPz1TdBSiy-:b195lza) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Backend/Lower.cpp#L8268)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> In interpreter we throw `WASMERR_TableIndexOutOfRange` when out of range and `JSERR_Property_NeedFunction` if nullptr
> Here we throw `WASMERR_SignatureMismatch`, could throw the right error message.
</details>
Oops, looks like I mixed up the error messages between the 2 functions. I think I'll stick to just generating WASMERR_TableIndexOutOfRange here, and have the interpreter also generate that for nullptr.

---

*[lib/Backend/Lower.h, line 419 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAGjnpPpHnNJGAVL4a:-KWAbcqHx-KyKE2MJGzD:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Backend/Lower.h#L419)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Not implemented function
</details>
Done.

---

*[lib/Runtime/Language/AsmJsTypes.h, line 896 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAHxceKkAgH8Sh6bvJ:-KWAcgGxa2w0DPWQWLET:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Language/AsmJsTypes.h#L896)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> This is only get/set in Wasm, should move inside the `#ifdef ENABLE_WASM`
</details>
Done.

---

*[lib/Runtime/Library/WebAssemblyInstance.cpp, line 324 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAKfhJIjZNIsQqRmsE:-KWAd1USXSquNDATOSGq:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyInstance.cpp#L324)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Could we make that `JSERR_Property_NeedFunction`
</details>
Done.

---

*[lib/Runtime/Library/WebAssemblyInstance.cpp, line 339 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAKrmyukuSpfEYUV8J:-KWAd142F7aCKoJGpwuS:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyInstance.cpp#L339)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Use `WASMERR_NeedMemoryObject`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1959)*

**Comment by Cellule** [comment]
Reviewed 10 of 46 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[lib/Runtime/Library/WebAssemblyInstance.cpp, line 491 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAhvKhLVcdaNqLGJSF:-KWAhvKhLVcdaNqLGJSG:b-b27zwo) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyInstance.cpp#L491)):*
> ```cpp
>             Assert(elems != nullptr);
>             uint offset = eSeg->GetDestAddr(wasmModule);
>             // REVIEW: should we check against min?
> ```

Checked against spec this is correct as it is. Remove comment

---

*[lib/Runtime/Library/WebAssemblyTable.cpp, line 126 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAiEafZR00y93n5NYO:-KWAiEafZR00y93n5NYP:b2ijizs) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyTable.cpp#L126)):*
> table->m_maxLength

Should probably cast this to uint64 as well

---

*[lib/Runtime/Library/WebAssemblyTable.cpp, line 203 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAiTsKWslAhQWUFY1b:-KWAiTsKWslAhQWUFY1c:b5p4jba) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyTable.cpp#L203)):*
> ```cpp
>         value = nullptr;
>     }
>     else if (!AsmJsScriptFunction::Is(args[2]) || !AsmJsScriptFunction::FromVar(args[2])->GetFunctionBody()->IsWasmFunction())
> ```

you can do 
`else if (!AsmJsScriptFunction::IsWasmScriptFunction(args[2])`

---

*[lib/Runtime/Library/WebAssemblyTable.cpp, line 222 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAiwfRS7rhh6biUrCr:-KWAiwfRS7rhh6biUrCs:bdgo6qu) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyTable.cpp#L222)):*
> SHOULD clause

What exactly do you mean that ?

---

*[lib/WasmReader/WasmBinaryReader.cpp, line 626 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAdovIxlPh3KLCiDVb:-KWAdovIxlPh3KLCiDVc:b7hcjvv) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/WasmReader/WasmBinaryReader.cpp#L626)):*
> ```cpp
>         uint32 flags = LEB128(length);
>         uint32 minPage = LEB128(length);
>         uint32 maxPage = minPage;
> ```

change to `maxPage = UINT_MAX`

---

*[lib/WasmReader/WasmByteCodeGenerator.cpp, line 908 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAe-_ivtsgwscRv5n7:-KWAe-_ivtsgwscRv5n8:b-bnjq6w) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/WasmReader/WasmByteCodeGenerator.cpp#L908)):*
> ```cpp
>             throw WasmCompilationException(_u("Indirect call index must be int type"));
>         }
>         // todo:: Add bounds check. Asm.js doesn't need it because there has to be an & operator
> ```

Remove that todo

---

*[lib/WasmReader/WasmElementSegment.h, line 18 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAefj9WfdZkEAWXDTK:-KWAefj9WfdZkEAWXDTL:bgvsom4) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/WasmReader/WasmElementSegment.h#L18)):*
> ```objc
>         UINT32 GetElement(const UINT32 tableIndex) const;
>         UINT32 GetNumElements() const { return m_numElem; }
>         UINT32* GetElements() const { return m_elems; }
> ```

That getter is used only for an Assert, can we remove it and put the Assert in GetElement instead ?

---

*[lib/WasmReader/WasmSignature.cpp, line 149 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAjHYVBRgCSC6I-ieF:-KWAjHYVBRgCSC6I-ieG:bp8p0r6) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/WasmReader/WasmSignature.cpp#L149)):*
> ```cpp
>     // 3 bits for result type, 2 for each arg
>     int sigSize = 3 + 2 * GetParamCount();
>     if (sigSize <= sizeof(m_shortSig))
> ```

`sizeof(m_shortSig) << 3`
Also, should use `<` instead of `<=` to show we should never set the left most bit (ie: make it imposible for short sig to be 0xFFFFFFFF)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1959)*

**Comment by Cellule** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1959)*

**Comment by Cellule** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1959)*

**Comment by MikeHolman** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[lib/Backend/Lower.cpp, line 8219 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAEM-jurZ6rLtPkDQf:-KWAm1kF4K_3eizApk9n:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Backend/Lower.cpp#L8219)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Do you need to move the const to a reg? Can't you just pass the IntConstOpnd to GenerateThrow ?
</details>
Done.

---

*[lib/Backend/Lower.cpp, line 8268 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAGe6QuPbxoxTXt0kA:-KWAm1CY1X9cQON6tM-4:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Backend/Lower.cpp#L8268)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Same as above 
</details>
Done.

---

*[lib/Parser/rterrors.h, line 380 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAGpDsNqpXlZ_7YtXX:-KWAm31tnsvOpvh72wcq:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Parser/rterrors.h#L380)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> I would say `called with invalid signature`
</details>
Done.

---

*[lib/Runtime/Library/WebAssemblyInstance.cpp, line 491 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAhvKhLVcdaNqLGJSF:-KWAm4hNu5LN-STozLfQ:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyInstance.cpp#L491)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Checked against spec this is correct as it is. Remove comment
</details>
Done.

---

*[lib/Runtime/Library/WebAssemblyTable.cpp, line 126 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAiEafZR00y93n5NYO:-KWAmasa3K6UlSpJVnfr:bhm57l4) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyTable.cpp#L126)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> > table->m_maxLength
> 
> Should probably cast this to uint64 as well
</details>
It will automatically be promoted, but I can make explicit.

---

*[lib/Runtime/Library/WebAssemblyTable.cpp, line 203 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAiTsKWslAhQWUFY1b:-KWAmVmglbxgZmi42W9Y:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyTable.cpp#L203)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> you can do 
> `else if (!AsmJsScriptFunction::IsWasmScriptFunction(args[2])`
</details>
Done.

---

*[lib/Runtime/Library/WebAssemblyTable.cpp, line 222 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAiwfRS7rhh6biUrCr:-KWAnlz_JiJqtF7_Phkn:b-bibw92) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/Runtime/Library/WebAssemblyTable.cpp#L222)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> > SHOULD clause
> 
> What exactly do you mean that ?
</details>
There was a clause in the spec that says we should attempt to reserve maximum length... but looks like it was removed, so I'll remove this comment.

---

*[lib/WasmReader/WasmBinaryReader.cpp, line 626 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAdovIxlPh3KLCiDVb:-KWAoGEZ4RMZnWsg17TP:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/WasmReader/WasmBinaryReader.cpp#L626)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> change to `maxPage = UINT_MAX`
</details>
Done.

---

*[lib/WasmReader/WasmByteCodeGenerator.cpp, line 908 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAe-_ivtsgwscRv5n7:-KWAoNyDESMu4SHzBuRi:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/WasmReader/WasmByteCodeGenerator.cpp#L908)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Remove that todo
</details>
Done.

---

*[lib/WasmReader/WasmElementSegment.h, line 18 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAefj9WfdZkEAWXDTK:-KWAoiVk6uzquyLCozui:bhzj02e) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/WasmReader/WasmElementSegment.h#L18)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> That getter is used only for an Assert, can we remove it and put the Assert in GetElement instead ?
</details>
Which getter are you talking about?

---

*[lib/WasmReader/WasmSignature.cpp, line 149 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAjHYVBRgCSC6I-ieF:-KWAp14WDgCuLonT2HN7:b5iswbh) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/WasmReader/WasmSignature.cpp#L149)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> `sizeof(m_shortSig) << 3`
> Also, should use `<` instead of `<=` to show we should never set the left most bit (ie: make it imposible for short sig to be 0xFFFFFFFF)
</details>
I thought about that, but it can never happen because there is no return type 7. I'll add a comment though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1959)*

**Comment by Cellule** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/WasmReader/WasmElementSegment.h, line 18 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAefj9WfdZkEAWXDTK:-KWB3y5_hALky3r2k4PC:b-wfmyas) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/WasmReader/WasmElementSegment.h#L18)):*
<details><summary><i>Previously, MikeHolman (Michael Holman) wrote…</i></summary>
> Which getter are you talking about?
</details>
`GetElements` but its not a big deal if this is the last thing left

---

*[lib/WasmReader/WasmSignature.cpp, line 149 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-KWAjHYVBRgCSC6I-ieF:-KWB4AdIPsjB5AKWxhmh:b-a2kk7l) ([raw file](https://github.com/microsoft/chakracore/blob/eb873fe77413ba8f7aff4abecba86650cc02ca09/lib/WasmReader/WasmSignature.cpp#L149)):*
<details><summary><i>Previously, MikeHolman (Michael Holman) wrote…</i></summary>
> I thought about that, but it can never happen because there is no return type 7. I'll add a comment though
</details>
Still need to do `if (sigSize <= sizeof(m_shortSig) << 3)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1959)*

**Comment by Cellule** [comment]
:lgtm:

---

Reviewed 17 of 18 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1959#-:-KWBvwmaw9hah9fNjYrK:bnfp4nl)*

**Pull request merged**
