### PR TITLE
Adding more async function test cases

### PR DESCRIPTION
**Pull request by aneeshdk**
Missed updating the stack walker to treat async functions also similar to
generator functions. Added more test cases. Removed the catch class from
the functionality tests as they are not relevant for async functions.

### CODE REVIEW

**Comment by aneeshdk** [comment]
@ianwjhalliday Can you please take a look?

**Comment by akroshg** [comment]
curious, why are we dumping the validation to the baseline file?

**Comment by aneeshdk** [comment]
The way our test framework executes does not account for any pending promise activity. Due to the async nature a sequential check for test success does not work for us.

**Comment by ianwjhalliday** [comment]
👍

**Pull request merged**
