### PR TITLE
cross platform: ICU static linking option

### PR DESCRIPTION
**Pull request by obastemur**
New `--embed-icu` build time flag
 - download ICU source codes [if it wasn't already downloaded]
 - compile [if it wasn't already compiled]
 - statically link into CH

### CODE REVIEW

**Comment by dilijev** [comment]
@obastemur Anything blocking this PR besides a code review?

**Comment by obastemur** [comment]
We are waiting on legal confirmation

**Comment by dilijev** [comment]
@obastemur Thanks

**Comment by obastemur** [comment]
We do not use Linux branch anymore.
Closing this one an going to send it again to master

**Pull request closed without merging**
