### PR TITLE
Disabling bytecode verification tests for lite ci build

### PR DESCRIPTION
**Pull request by MSLaguana**

### CODE REVIEW

**Comment by jackhorton** [comment]
Don't JsBuiltIns need this too?

**Comment by MSLaguana** [comment]
Yes it does, but they don't exist in 1.7

**Comment by Cellule** [comment]
Does the Lite build even exist in 1.7 ?
I don't see a CI run to test a Lite build on this PR (which is why I missed it initially).

**Comment by MSLaguana** [comment]
Probably not actually, but I thought I'd make the change here so it'll travel everywhere necessary.

**Pull request merged**
