### PR TITLE
Logical & TruncConv Ops + Tests

### PR DESCRIPTION
**Pull request by Krovatkin**
This PR includes 

* logical operations + tests
* truncation & conversion operations for 32x4 types + tests

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/3288)

### CODE REVIEW

**Comment by Krovatkin** [comment]
@Cellule @MikeHolman I'll ping you guys later about this PR when all the tests pass
fyi @arunetm

**Comment by Krovatkin** [comment]
Please test Ubuntu shared_ubuntu_linux_debug

**Comment by Krovatkin** [comment]
@Cellule Could you please take a look when you have a moment?

**Comment by MikeHolman** [comment]
I think nonstandard true values will be broken. Currently, if a lane is non-zero it is considered true. Lowering code uses `PMOVMSKB`, which only looks at the most significant bit of each byte.

https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#boolean-horizontal-reductions

**Comment by Krovatkin** [comment]
@MikeHolman absolutely! will fix!

**Comment by Krovatkin** [comment]
@chakrabot Please test Windows ci_slow_x64_debug

**Comment by arunetm** [comment]
Hey Nick, Can we do an internal code review when you add the 64bit types?

**Comment by Krovatkin** [comment]
@arunetm okay

**Comment by Krovatkin** [comment]
@MikeHolman Looks like we should be able to handle non-canonical boolean values now.

**Comment by Krovatkin** [comment]
@MikeHolman @Cellule Hey guys! Could  you please take another look? I'd like to push this one and 2 more then I'll rebase `wasm.simd` as @Cellule suggested.

**Comment by Cellule** [comment]
Reviewed 9 of 11 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/Backend/LowerMDShared.h, line 374 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3288#-KosIgXUAU9DfBItlcLI:-KosIgXVTPjAGTsZLkFj:b-90dytk) ([raw file](https://github.com/microsoft/chakracore/blob/1853d779edd8360d9b4f5a685bb34b9b64dd95df/lib/Backend/LowerMDShared.h#L374)):*
> ```objc
>     IR::Instr*          Simd128LowerAnyTrue(IR::Instr* instr);
>     IR::Instr*          Simd128LowerAllTrue(IR::Instr* instr);
> #ifdef ENABLE_WASM
> ```

Could we start using a different `#define` for wasm.simd ? Just so we can more easily organize what's what.
Something like `ENABLE_WASM_SIMD`. I thin that will also help the transition to remove simd.js and keep what we need for wasm.

---

*[lib/Backend/LowerMDSharedSimd128.cpp, line 2273 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3288#-KosUlttjiNyesHsAmZ2:-KosUltuxz_YA338NWrl:b-x3q9t4) ([raw file](https://github.com/microsoft/chakracore/blob/1853d779edd8360d9b4f5a685bb34b9b64dd95df/lib/Backend/LowerMDSharedSimd128.cpp#L2273)):*
> ```cpp
>     if (m_func->GetJITFunctionBody()->IsWasmFunction())
>     {
>         Js::OpCode spreadOpCode = Js::OpCode::InvalidOpCode;
> ```

nit: could we name this cmpOpcode to match how we use it

---

*[lib/Runtime/Language/SimdBool32x4Operation.cpp, line 45 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3288#-KoshyGFPElizqn3RZ0N:-KoshyGFPElizqn3RZ0O:b-x1ie4a) ([raw file](https://github.com/microsoft/chakracore/blob/1853d779edd8360d9b4f5a685bb34b9b64dd95df/lib/Runtime/Language/SimdBool32x4Operation.cpp#L45)):*
> ```cpp
>     }
> 
>     template bool SIMDBool32x4Operation::OpAllTrue<int>(const SIMDValue& val);
> ```

nit: I would prefer use `int32, int16, int8` instead of `int, short, char`

---

*[lib/Runtime/Language/SimdUtils.h, line 335 at r2](https://reviewable.io:443/reviews/microsoft/chakracore/3288#-Kosj-wosrVtEi--yWG9:-Kosj-wosrVtEi--yWGA:b-wjxo4p) ([raw file](https://github.com/microsoft/chakracore/blob/1853d779edd8360d9b4f5a685bb34b9b64dd95df/lib/Runtime/Language/SimdUtils.h#L335)):*
> ```objc
>         {
> #ifdef ENABLE_WASM
>             T* cursor = (T*)val.i8;
> ```

I would add some CompileAssert here
```cpp
            CompileAssert(sizeof(T) <= sizeof(SIMDValue));
            CompileAssert(sizeof(SIMDValue) % sizeof(T) == 0);
            T* cursor = (T*)val.i8;
            uint size = sizeof(SIMDValue) / sizeof(T);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3288)*

**Comment by Cellule** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3288#-:-KotITxz6QmQg44UEqTX:bnfp4nl)*

**Comment by Krovatkin** [comment]
@Cellule Could you please approve this PR if it looks good now?
fyi : @arunetm

**Comment by Krovatkin** [comment]
@arunetm Could you please merge this PR?

**Comment by Krovatkin** [comment]
@Cellule ,  Thanks a lot for your help!

**Pull request merged**
