### PR TITLE
adding boolean types and comparison operators

### PR DESCRIPTION
**Pull request by Krovatkin**
This includes
 * adding boolean types to `m128`
 * enabling comparison operators
 * adding tests

### CODE REVIEW

**Comment by Krovatkin** [comment]
@MikeHolman @Cellule Please ignore this PR for now. I'd like to make sure it passes all the CI tests. Thanks!

fyi: @arunetm

**Comment by Krovatkin** [comment]
@MikeHolman @Cellule Guys could you please take a quick look when you have a mnt? Thanks!

fyi @arunetm

**Comment by MikeHolman** [comment]
After discussions at the CG meeting, the current proposal has removed boolean types.

**Comment by arunetm** [comment]
Thanks @MikeHolman for pointing this out. Was there a consensus for dropping bools during the CG meeting? Unfortunately we couldn't attend this time and I am trying to understand if there is a chance that the bool type get re-introduced in the future.

@Krovatkin https://github.com/WebAssembly/simd/commits/master has the recent updates reflecting the CG meeting discussions. I suggest we close this PR without merging for now. Lets keep the changes in a private branch just in case. These might come back at a later point :)

**Comment by Krovatkin** [comment]
@arunetm 

Thanks, I was polling the updates weekly (on Mondays). All these updates were introduced within the last 3 days, so I missed them.

@MikeHolman I'm closing this one. We'll go through all our changes to make sure they are compliant w/ the latest version of the spec.

**Comment by MikeHolman** [comment]
There was not a consensus. The room was divided, so it's possible they come back with new evidence for their usefulness.

**Pull request closed without merging**
