### PR TITLE
Deprecate unused telemetry code

### PR DESCRIPTION
**Pull request by curtisman**

### CODE REVIEW

**Comment by agarwal-sandeep** [comment]
> FLAGNR(Boolean, DateParseTel, "Print Date.parse telemetry output.", false)

Why only GCPauseTel is removed?

---
Refers to: lib/Common/ConfigFlagsList.h:1458 in 785e912. [](commit_id = 785e912099e454585ad6ddbcb360b1b5c5a684d5, deletion_comment = False)

**Comment by curtisman** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug

**Comment by curtisman** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_release

**Comment by curtisman** [comment]
> FLAGNR(Boolean, DateParseTel, "Print Date.parse telemetry output.", false)

The language one remain in use.

---
In reply to: [252970394](https://github.com/Microsoft/ChakraCore/pull/1724#issuecomment-252970394) [](ancestors = 252970394)

---
Refers to: lib/Common/ConfigFlagsList.h:1458 in 785e912. [](commit_id = 785e912099e454585ad6ddbcb360b1b5c5a684d5, deletion_comment = False)

**Pull request merged**
