### PR TITLE
Make HashTbl and Scanner an inline instance of the Parser or a stack instance instead of allocating it in the heap

### PR DESCRIPTION
**Pull request by curtisman**
Parser will never have a NULL HashTbl or Scanner.

### CODE REVIEW

**Comment by curtisman** [comment]
@dotnet-bot test 
OSX static_osx_osx_release

**Comment by MSLaguana** [comment]
@dotnet-bot test OSX static_osx_osx_test please

**Comment by curtisman** [comment]
@dotnet-bot test OSX static_osx_osx_test

**Comment by curtisman** [comment]
@dotnet-bot test OSX static_osx_osx_test

**Pull request merged**
