### PR TITLE
Fix Legacy-Link and NDK-Compile errors

### LINKED ISSUE #2317: [DisableJIT] Link Error (branch: master)
https://github.com/Microsoft/ChakraCore/wiki/Build-Status#disablejit-builds

For example:
https://ci.dot.net/job/Microsoft_ChakraCore/job/master/job/daily_disablejit_x64_debug/
Broken since build 41

Changes between a successful build and the broken build:
https://ci.dot.net/job/Microsoft_ChakraCore/job/master/job/daily_disablejit_x64_debug/changes

```
#41 (Dec 22, 2016 9:10:11 AM)

android: ChakraCore compiles to Android ARMv7 (commit: 6811584) — ogbastem / githubweb
silence failures for connecting to jit process (commit: 1f87d7e) — Michael Holman / githubweb
Resolves #1896. Modified Array.prototype.toLocaleString to use the (commit: 1410874) — akatti / githubweb
Update Jsrt Utf8 types and naming (commit: adbea39) — ogbastem / githubweb
```

@obastemur @MikeHolman @atulkatti

### PR DESCRIPTION
**Pull request by obastemur**
Fixes #2317

### CODE REVIEW

**Comment by dilijev** [comment]
You can now resolve the CI issues as described here: https://github.com/Microsoft/ChakraCore/pull/2332#issuecomment-271029950

**Comment by dilijev** [comment]
@dotnet-bot test legacy tests please

**Comment by dilijev** [comment]
@obastemur My mistake, that test was about DisableJIT

**Comment by dilijev** [comment]
@dotnet-bot test nojit tests please

**Comment by dilijev** [comment]
DisableJIT tests look good. You can clear the failed `*dev12*` tests by pushing a new ref (which unfortunately will force a re-run).

**Comment by jianchun** [comment]
:shipit:

**Comment by obastemur** [comment]
@curtisman Thanks for the review! @dilijev Thanks for double-checking it!

**Pull request merged**
