### PR TITLE
Class extends clause has different source locations between defer/non-defer parse modes

### PR DESCRIPTION
**Pull request by tcare**
Tracked in OS 7030846.

When emitting a class statement with an extends clause, we made the assumption that the start and end of the bytecode for that statement happened in the same place in defer and non-defer parse modes. In fact, it is possible to have the load happen in different locations, e.g. if we cache a previous load's register location in non-defer parse mode and have to load from a local slot in defer parse mode.

The fix is to set the statement location to the InitClass bytecode.

### CODE REVIEW

**Comment by tcare** [comment]
@akroshg @boingoing please review.

I considered adding a test for this, but the differences in the bytecode would be fragile.

**Comment by akroshg** [comment]
Change looks good to me.
There are some cases added for line and column difference under `test\error\validate_line_column.js`
There is one test for `extends `already.

**Comment by boingoing** [comment]
Looks good to me, what's the symptom of this bug? Can you add a unit test that throws an exception and checks the column number?

**Comment by tcare** [comment]
We would get a different line number and offset in defer and non-defer parse mode.

As we discussed offline, the test mentioned by Akrosh will cover this.

**Pull request merged**
