### PR TITLE
Updating the copyright notice.

### PR DESCRIPTION
**Pull request by siddharthasharma**
Mentioning the year is must when declaring copyright issues.

### CODE REVIEW

**Comment by MikeHolman** [comment]
IANAL, so I don't know about the requirement for copyright notice having a year... but presumably if we did need this notice, we should do find/replace for it on all files, not just a small handful.

**Comment by siddharthasharma** [comment]
Hey @MikeHolman, will update all files. Was getting my CLA done tonight, will have all files updated here. Patience, a little longer.

**Comment by EdMaurer** [comment]
We've used the header that Microsoft OSS guidelines specify. I don't want to move away from that.

**Comment by siddharthasharma** [comment]
@EdMaurer, totally understood. Not moving away from the specifications given by Microsoft OSS guidelines. Read them, then checked out the stuffs here. I am law guy learning to code. ;)

**Comment by dilijev** [comment]
Additionally if we decide to make this change we need to decide on what it will look like. For example, some of these sources are older than 2016, as you might imagine. We have the Copyright Check looking for this sort of thing. Unless legal says otherwise, we're not especially interested in constantly updating the year on each file. We will look into it and get back to you.

**Comment by abchatra** [comment]
Any update here?

**Comment by dilijev** [comment]
@abchatra I'm discussing with our legal rep and @edmaurer

**Comment by dilijev** [comment]
@siddharthasharma We double-checked with legal and the copyright notice we are using is what they have advised for us. Thanks for bringing this to our attention so we could make sure!

**Pull request closed without merging**
