### PR TITLE
Adding do..while trick on the assert code so that missing semicolon error will be caught during debug mode.

### PR DESCRIPTION
**Pull request by akroshg**
Adding do..while trick on the assert code so that missing semicolon error will be caught during debug mode.

### CODE REVIEW

**Comment by akroshg** [comment]
@ianwjhalliday @tcare - could you review pls?

**Comment by tcare** [comment]
Looks good - awaiting Ian's signoff

**Comment by dilijev** [comment]
Cool. LGTM

**Comment by ianwjhalliday** [comment]
:+1:

**Pull request merged**
