### PR TITLE
SIMD.js - Changed conversion from/to X86SIMDValue to use unaligned MOVs

### PR DESCRIPTION
**Pull request by nmostafa**
Changed conversion from/to X86SIMDValue to use unaligned MOVs

### CODE REVIEW

**Comment by nmostafa** [comment]
Fixes test failures with Dev12, that I thought got fixed with  [#417](https://github.com/Microsoft/ChakraCore/pull/417). Refer to the PR for more details. 

This change introduces explicit MOVUPS when converting from/to IA specific value, avoiding optimizing away the value copy code that cause aligned access to unaligned value. 

@MikeHolman @dilijev

**Comment by nmostafa** [comment]
@dotnet-bot 
test Windows 7 daily_dev12_x86_debug please
test Windows 7 daily_dev12_x86_test please
test Windows 7 daily_dev12_x86_release please
test Windows 7 daily_dev12_x64_test please
test Windows 7 daily_dev12_x64_release please

**Comment by dilijev** [comment]
Nice. LGTM.

**Comment by MikeHolman** [comment]
Again, lgtm. Did you talk to VC team about this?

**Comment by dilijev** [comment]
@nmostafa I signed off. You're good to merge. Was there any follow-up you needed to do re: VC team that @MikeHolman mentioned?

**Pull request merged**
