### PR TITLE
replace wchar_t/L"..." with char16/_u("...")

### PR DESCRIPTION
**Pull request by jianchun**
Replace wchar_t/L"..." with char16/_u("...") in all sources (except public
JSRT APIs. Will revisit later.)

[Review on Reviewable](https://reviewable.io/reviews/microsoft/chakracore/460)

### CODE REVIEW

**Comment by ianwjhalliday** [comment]
I took a sampling of the changed files.  Looks great

**Comment by dilijev** [comment]
Reviewed 48 of 443 files at r1.
Review status: 48 of 443 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[lib/Runtime/Library/UriHelper.cpp, line 147 \[r1\]](https://reviewable.io:443/reviews/microsoft/chakracore/460#-KCIGZpQn0GWxmCpBLlB:-KCIGZpQn0GWxmCpBLlC:545224580) ([raw file](https://github.com/microsoft/chakracore/blob/b68a796ed7f9efa983269451a9aa77c7872891d6/lib/Runtime/Library/UriHelper.cpp#L147)):*
This is silly, but harmless.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/chakracore/460)*

**Comment by dilijev** [comment]
I looked at a few files and it looks good. I assume this was more or less a find-and-replace operation and since it compiles, I'd say LGTM

**Comment by jianchun** [comment]
Thanks guys! Will merge this.

**Pull request merged**
