### PR TITLE
Remove timestamp printing from LeakReport

### PR DESCRIPTION
**Pull request by digitalinfinity**

### CODE REVIEW

**Comment by digitalinfinity** [comment]
@curtisman @tcare @aneeshdk please review?

**Comment by curtisman** [comment]
LGTM

**Comment by aneeshdk** [comment]
LGTM

**Comment by tcare** [comment]
LGTM. Seems unlikely, but could any automation be affected by this?

**Comment by digitalinfinity** [comment]
Don't think so but we'll find out :) AFAIK, no automation or human relies on this data

**Comment by tcare** [comment]
'Human'. :D

**Pull request merged**
