### PR TITLE
Use intrinsic to get double as int, instead of taking address which challenges the compiler.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by MikeHolman** [comment]
Can you give a bit more info on the motivation? I looked at the codegen, and it seems surprising that there would be any perf benefit.

This is what I see for our code:
````
        vmovsd  QWORD PTR [rsp+8], xmm0
        sub     rsp, 24
        mov     rax, QWORD PTR value$[rsp]
        mov     QWORD PTR val$[rsp], rax
        mov     rax, -1125899906842624                    ; fffc000000000000H
        mov     rcx, QWORD PTR val$[rsp]
        xor     rcx, rax
        mov     rax, rcx
        add     rsp, 24
        ret     0
````
And the new code:
````
        vmovsd  QWORD PTR [rsp+8], xmm0
        sub     rsp, 56                             ; 00000038H
        vmovsd  xmm0, QWORD PTR value$[rsp]
        vxorpd  xmm1, xmm1, xmm1
        vmovsd  xmm0, xmm1, xmm0
        vmovupd XMMWORD PTR $T1[rsp], xmm0
        vmovaps xmm0, XMMWORD PTR $T1[rsp]
        vmovdqu XMMWORD PTR $T2[rsp], xmm0
        vmovdqa xmm0, XMMWORD PTR $T2[rsp]
        vmovq   rax, xmm0
        mov     QWORD PTR val$[rsp], rax
        mov     rax, -1125899906842624                    ; fffc000000000000H
        mov     rcx, QWORD PTR val$[rsp]
        xor     rcx, rax
        mov     rax, rcx
        add     rsp, 56                             ; 00000038H
        ret     0
````

**Comment by jaykrell** [comment]
Lack of memory reference in the optimized form.

```
C:\s>type 2.cpp
typedef unsigned __int64 uint64;

#define FloatTag_Value 1 // I made this up.

extern "C" __declspec(selectany) const char _fltused = 0;

#include <intrin.h>

__declspec(dllexport)

    uint64 double_to_var_1(double value)
    {
       uint64 val = *(uint64*)&value;
       return val ^ FloatTag_Value;
    }


    uint64 double_to_var_2(double value)
    {
       uint64 val = _mm_cvtsi128_si64(_mm_castpd_si128(_mm_set_sd(value)));
       return val ^ FloatTag_Value;
    }

C:\s>cl /LD /O2 2.cpp /Zi /link /nod /noentry /incremental:no
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64

C:\s>link /dump /disasm 2.dll

?double_to_var_1@@YA_KN@Z:
  0000000180001000: F2 0F 11 44 24 08  movsd       mmword ptr [rsp+8],xmm0
  0000000180001006: 48 8B 44 24 08     mov         rax,qword ptr [rsp+8]
  000000018000100B: 48 83 F0 01        xor         rax,1
  000000018000100F: C3                 ret
?double_to_var_2@@YA_KN@Z:
  0000000180001010: 0F 28 C8           movaps      xmm1,xmm0
  0000000180001013: 0F 57 D2           xorps       xmm2,xmm2
  0000000180001016: F2 0F 10 D1        movsd       xmm2,xmm1
  000000018000101A: 66 48 0F 7E D0     movq        rax,xmm2
  000000018000101F: 48 83 F0 01        xor         rax,1
  0000000180001023: C3                 ret

```

**Comment by jaykrell** [comment]
ping?

**Comment by MikeHolman** [comment]
Sorry for the delay. I see now that I was accidentally not compiling optimized form when I looked at this earlier. Change looks good to me.

**Comment by jaykrell** [comment]
Fyi.
1. I'll resolve merge conflict.
2. This is doable similarly for x86.
3. Even more clearly for arm32/arm64, that have well named intrinsics for doing exactly this. Let me dig up my old change.

For this PR just 1 though, so as to not abuse the approval.

**Comment by jaykrell** [comment]
See inetcore change 1323200 by NTDEV\jaykrell@JOHNDALYFASTER0-131122130640 on 2013/11/22 14:07:33

```
#include <intrin.h>

// The important feature of these macros/intrinsics is that they
// don't take the address of a local or parameter, thereby making it
// easier for the compiler to stack pack. The savings in stack space are significant.
#if defined(_AMD64_) || _M_IX86_FP >= 2 || defined(__AVX__)
#define _CopyDoubleFromInt64(x)  (_mm_cvtsd_f64(_mm_castsi128_pd(_mm_cvtsi64_si128(x))))
#elif defined(_X86_)
#define _CopyDoubleFromInt64(x)  (*reinterpret_cast<double*>(&(x)))
#else
// intrinsic on most other architectures, including ARM
#endif

#if defined(_AMD64_)
#define _CopyInt64FromDouble(x)  (_mm_cvtsi128_si64(_mm_castpd_si128(_mm_set_sd(x))))
#elif defined(_X86_)
#define _CopyInt64FromDouble(x)  (*reinterpret_cast<__int64*>(&(x)))
#else
// intrinsic on most other architectures, including ARM
#endif
```

**Comment by MikeHolman** [comment]
I was thinking about this a little more, and there are other places where we do the same.

Usually we call `NumberUtilities::ToSpecial`. So I think it would be better to update `NumberUtilities::ToSpecial` and change `JavascriptNumber::ToVar` to call it.

Likewise, we can apply your other macro to `NumberUtilities::ReinterpretBits` and change `JavascriptNumber::GetValue` to call that.

I think for now it's fine just optimizing for the amd64/double cases, since they are the most common.
Would you mind making that change?

**Comment by jaykrell** [comment]
Yes, right, I will try to fully port my inetcore 1323200. I think stuff had moved around and/or I didn’t build the other targets.

**Comment by jaykrell** [comment]
I misread sorry. You want a change, not later additional changes. Ok.

**Comment by jaykrell** [comment]
I not sure what to do about GetValue. There is already a pointer, it seems.
Wasm could use something here too I think, I only added a comment.

**Comment by MikeHolman** [comment]
Not sure if you can see the CI results, but x86 builds are failing to find intrinsics `_mm_cvtsi128_si64` and `_mm_cvtsi64_si128`. It looks like those might need 64 bit registers. I think it's fine to just use the old way for x86.

**Comment by jaykrell** [comment]
You are right. It is obvious when I looked at intrin.h.

**Pull request merged**
