### PR TITLE
xplat: do pal initialization check debug only

### PR DESCRIPTION
**Pull request by obastemur**
`___cxa_guard_**` is expensive. At the moment, library / dependency initialization order is no longer an issue on our pal dependency. Make the checks and safe pre initialization DEBUG only.

### CODE REVIEW

**Comment by digitalinfinity** [comment]
is it cheaper to just make was_pal_initialized non-static?

**Comment by obastemur** [comment]
@digitalinfinity ‘static’ there is to prevent a double call during a premature initialization. Otherwise, not sure if there’s any reason to check if anything was initialized.

**Comment by obastemur** [comment]
@dotnet-bot test OSX static_osx_osx_debug please

**Comment by obastemur** [comment]
@digitalinfinity other concerns?

**Pull request merged**
