### PR TITLE
Remove Simd.js code from ChakraCore - Part 1 (ifdef out)

### PR DESCRIPTION
**Pull request by agarwal-sandeep**
Put SIMDjs code in library, language and backend under #ifdef ENABLE_SIMDJS
undef ENABLE_SIMDJS
Some portion of SIMD code (IRType, OpCodesSimd, AsmJsBuiltInNames etc.) is used in WASM simd so it is left as it is. This will be take care of under #3274
Haven't ifdef'd TypeIds_SIMD* as that will make the TypeIds enum messy. During final cleanup we can clean this.

This reduce Chakra.dll x64 release binary size by 0.52 MB and ChakraCore x64 release binary size by 0.43 MB

### CODE REVIEW

**Comment by agarwal-sandeep** [comment]
@LouisLaf @Cellule please take a look

**Comment by Cellule** [comment]
@arunetm @Krovatkin fyi

**Comment by Krovatkin** [comment]
@Cellule @agarwal-sandeep There's quite a few of `ENABLE_SIMDJS` in AsmJs-specific files. There's a 99% chance we are going to need that code. If the next step is to disappear all the `ENABLE_SIMDJS` code, I'd suggest we either use a different `ifdef` for asmjs stuff or we let it be (the second one is a bit more preferable since it would simplify a merge process for us). If the main goal of this PR to reduce dll memory footprint, asmjs-specific code wouldn't probably account to much comparing to JavaScript API

**Comment by Cellule** [comment]
@Krovatkin We want to give some time before actually removing the code so we can more precisely determine what we actually need for wasm.simd. Also, there is a lot of asm.js code that we don't want anymore either, I am thinking mostly of the bytecode generator.

Once we merge this PR, I suggest to integrate master into wasm.simd branch and that way we could start figuring out that code sooner. I would recommend at that time to rename the occurences of `#ifdef ENABLE_SIMDJS` to `#ifdef ENABLE_WASM_SIMD` which would help resolve potential conflicts in the future.

**Comment by Cellule** [comment]
Reviewed 415 of 415 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[lib/Backend/BailOut.cpp, line 825 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3296#-Komfh3bXD3Goo9Bu4nD:-Komfh3cKN6ldgM8Y2Jj:b-nsjiad) ([raw file](https://github.com/microsoft/chakracore/blob/87897065e7a6ce8a1dcefbc08d7eed452ac708bc/lib/Backend/BailOut.cpp#L825)):*
> ```cpp
>             {
>                 // SIMD_JS
>                 simdValue = layout->GetSimdValueAtOffset(offset);
> ```

Missed this block

---

*[lib/Backend/BailOut.cpp, line 886 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3296#-KomgltnE1laSFtBG3kr:-KomgltnE1laSFtBG3ks:b-nsjiad) ([raw file](https://github.com/microsoft/chakracore/blob/87897065e7a6ce8a1dcefbc08d7eed452ac708bc/lib/Backend/BailOut.cpp#L886)):*
> ```cpp
>                    )
>                 {
>                     simdValue = *((SIMDValue *)&(registerSaveSpace[offset - 1]));
> ```

Missed this block

---

*[lib/Backend/BailOut.cpp, line 1040 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3296#-Komh1gUg-Rdmb6TdFh8:-Komh1gUg-Rdmb6TdFh9:b-y5x4wy) ([raw file](https://github.com/microsoft/chakracore/blob/87897065e7a6ce8a1dcefbc08d7eed452ac708bc/lib/Backend/BailOut.cpp#L1040)):*
> ```cpp
> #else
>             // https://github.com/Microsoft/ChakraCore/issues/3274
>             // Change signature of RestoreValue if WASM simd doesn't use this
> ```

I doubt wasm simd will need this since we don't have bailouts in wasm. But it's okay to leave this for a later time.

---

*[lib/Backend/GlobOpt.cpp, line 16404 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3296#-Koml2W1_n_WwwFk4sYd:-Koml2W1_n_WwwFk4sYe:b-s6ios3) ([raw file](https://github.com/microsoft/chakracore/blob/87897065e7a6ce8a1dcefbc08d7eed452ac708bc/lib/Backend/GlobOpt.cpp#L16404)):*
> ```cpp
>             {
>                 IR::BailOutKind instrBailoutKind = instr->GetBailOutKind();
> #ifdef ENABLE_SIMDJS
> ```

Instead of copy/pasting the Assert here could we do
```js
                Assert(
#ifdef ENABLE_SIMDJS
                    instrBailoutKind == IR::BailOutSimd128F4Only ||
                    instrBailoutKind == IR::BailOutSimd128I4Only ||
#endif
                    instrBailoutKind == IR::BailOutIntOnly ||
                    instrBailoutKind == IR::BailOutExpectingInteger ||
                    instrBailoutKind == IR::BailOutOnNotPrimitive ||
                    instrBailoutKind == IR::BailOutNumberOnly ||
                    instrBailoutKind == IR::BailOutPrimitiveButString);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3296)*

**Comment by Krovatkin** [comment]
@Cellule 

> Once we merge this PR, I suggest to integrate master into `wasm.simd` branch and that way we could start figuring out that code sooner.

Sounds like a plan. Though, I'd prefer to merge two more changes (they are pretty stable and cleaned up) into `wasm.simd` before rebasing it onto `master`. This way, I won't have to rebase them piecemeal afterwards. It would be a good milestone since 99% of `32x4` ops should have been enabled/added. At that point, I'd also rename some `ENABLE_SIMDJS` to `ENABLE_WASM_SIMD`   as you are suggesting.

**Comment by agarwal-sandeep** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[lib/Backend/BailOut.cpp, line 825 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3296#-Komfh3bXD3Goo9Bu4nD:-Komvyrcg5AuplobGDQ3:bik9byd) ([raw file](https://github.com/microsoft/chakracore/blob/87897065e7a6ce8a1dcefbc08d7eed452ac708bc/lib/Backend/BailOut.cpp#L825)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

Missed this block
</blockquote></details>

Will leave it for when we change the function signature to remove isSimd* parameters

---

*[lib/Backend/BailOut.cpp, line 886 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3296#-KomgltnE1laSFtBG3kr:-KomwBRLktMBrtjvOzLX:bik9byd) ([raw file](https://github.com/microsoft/chakracore/blob/87897065e7a6ce8a1dcefbc08d7eed452ac708bc/lib/Backend/BailOut.cpp#L886)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

Missed this block
</blockquote></details>

Will leave it for when we change the function signature to remove isSimd* parameters

---

*[lib/Backend/GlobOpt.cpp, line 16404 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/3296#-Koml2W1_n_WwwFk4sYd:-KomwG8ZU8UFD_Ubn2Av:b-gdfjkj) ([raw file](https://github.com/microsoft/chakracore/blob/87897065e7a6ce8a1dcefbc08d7eed452ac708bc/lib/Backend/GlobOpt.cpp#L16404)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

Instead of copy/pasting the Assert here could we do
```js
                Assert(
#ifdef ENABLE_SIMDJS
                    instrBailoutKind == IR::BailOutSimd128F4Only ||
                    instrBailoutKind == IR::BailOutSimd128I4Only ||
#endif
                    instrBailoutKind == IR::BailOutIntOnly ||
                    instrBailoutKind == IR::BailOutExpectingInteger ||
                    instrBailoutKind == IR::BailOutOnNotPrimitive ||
                    instrBailoutKind == IR::BailOutNumberOnly ||
                    instrBailoutKind == IR::BailOutPrimitiveButString);
```
</blockquote></details>

That generates C2121 error 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3296)*

**Comment by Cellule** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/3296#-:-KomxIm49e5YUh1-ZQlx:bnfp4nl)*

**Pull request merged**
