### PR TITLE
swb: write barrier annotations 3

### PR DESCRIPTION
**Pull request by jianchun**
### swb: annotate SList, Array … 
Change SListNode to template on TAllocator. Annotate SList fields and fix
all usages.

Add PointerValue() function to retrieve a pointer type field's pointer
value. Simplifies casts.

Add SparseArraySegment<T>::From() function to simplify all
SparseArraySegment casts after annotation.

### swb: write barrier annotations 3 … 
This contains all the remaining annotations that can be detected by
current plugin. Mostly auto annotations + minor manual fixes.

### CODE REVIEW

**Comment by jianchun** [comment]
@dotnet-bot test Linux tests please

**Comment by jianchun** [comment]
@dotnet-bot test Linux tests please

**Comment by jianchun** [comment]
@dotnet-bot test OSX daily_osx_osx_debug_static please

**Comment by jianchun** [comment]
@dotnet-bot test Linux tests please

**Comment by leirocks** [comment]
:shipit:

**Pull request merged**
