### PR TITLE
Improve logs for Promise unhandledrejection

### PR DESCRIPTION
**Pull request by dilijev**

### CODE REVIEW

**Comment by dilijev** [comment]
This change is useful for debugging but because it prints a pointer, can't be tested with a baseline test. I think I'll add some state to track a promise ID and increment it for each new promise that is seen, and add a second flag to print the actual pointer (with no baseline test).

**Comment by rhuanjl** [comment]
I made that callback very simple as it was intended purely for use with the baseline test for testing the number, type (rejected or handled) and order of host promise rejection tracker calls.

**Comment by jackhorton** [comment]
You could add a HostConfigFlag for this? Default to printing the pointer, or don't print it if `-PromiseRejectionExtraInfo-` or whatever is passed.

**Comment by dilijev** [comment]
@jackhorton yep, that's what I was thinking

**Comment by mike-kaufman** [comment]
@dilijev - take a look @ #5320, this updates same code path to output stack if a "stack" property is available.  There's some minor conflict here.

**Comment by mike-kaufman** [comment]
My .02 here is there are already a ton of conflig flags to chakra & options to ch, and adding more just increases the complexity & usability.  

If this is something that is generally useful then I would say go for it, but I'm not convinced it is generally useful.  In particular, if I needed this (ability to see the addresses of promises when the events fired), I would need to dig through the code find out what the flag was anyway, and in that case, it seems almost as simple to update the output statement for my purposes of seeing the addresses.

**Comment by dilijev** [comment]
You're right this is probably unnecessary beyond my immediate interest.

**Pull request closed without merging**
