### PR TITLE
remove assertion on existence of expirable object on the list

### PR DESCRIPTION
**Pull request by leirocks**
this can cause hang in chk build

### CODE REVIEW

**Comment by leirocks** [comment]
@dotnet-bot test OSX static_osx_osx_debug please

**Comment by leirocks** [comment]
@dotnet-bot test Ubuntu shared_ubuntu_linux_test please

**Comment by digitalinfinity** [comment]
I wonder if there is a cheaper check we can do to check for the existence of an element in a list. One idea is to add a cookie field to the DListNode class in debug builds- let this cookie simply the be the list that the node is a part of- on removal, we null it out- then we can have a "fastHasElement" version which simply checks if the list is the same as the cookie. Thoughts?

**Comment by leirocks** [comment]
how about clear prev/next pointer after removing node from the DList, like I did for scriptContextList(https://github.com/Microsoft/ChakraCore/pull/2763/files#diff-6858ff2e7f3b97763dd5be71dfc9ae56R421)

```c++
    static void RemoveNode(NodeBase * node)
    {
        node->Prev()->Next() = node->Next();
        node->Next()->Prev() = node->Prev();

        // adding following two lines:
        node->Prev() = nullptr;
        node->Next() = nullptr;
    }
```

**Pull request merged**
