### PR TITLE
Add a flag to DecodeUnitsInto to detect the case where the buffer ends at a truncated unicode sequence

### PR DESCRIPTION
**Pull request by boingoing**
Only enabled this if the option to do chunked-decoding is enabled.

### CODE REVIEW

**Comment by boingoing** [comment]
dotnet-bot test Ubuntu_linux_debug please

**Comment by PaulWells** [comment]
+1

**Comment by boingoing** [comment]
@dotnet-bot test ubuntu tests please

**Comment by boingoing** [comment]
@dotnet-bot test static_ubuntu_linux_debug please

**Comment by boingoing** [comment]
@dilijev This parameter is to be used by a partner team which shares the UTF8Codex library.

**Comment by dilijev** [comment]
@boingoing I was just speaking with @Penguinwizzard about this code. Is it possible to add some tests that cover these scenarios? These functions should be static IIRC so adding Native Unit Tests to cover this should be fairly straightforward.

**Comment by boingoing** [comment]
@dilijev Turns out adding unit tests for this is doable and isn't even that hard. Pushed an update to the PR with tests included.

**Comment by dilijev** [comment]
@boingoing I didn't look too closely at the test cases but the test looks sound. Thanks!

**Comment by boingoing** [comment]
Thanks, @dilijev. This is landed in db4f000a80.

**Pull request merged**
