### PR TITLE
Add static binary build to linux jobs.

### PR DESCRIPTION
**Pull request by dilijev**
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1213)

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by dilijev** [comment]
@digitalinfinity does this look good?

**Comment by dilijev** [comment]
@mmitche Any objections to adding 3 more Linux configs?

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by dilijev** [comment]
@digitalinfinity recommend review with https://github.com/Microsoft/ChakraCore/pull/1213/files?w=1 since indentation of the whole block changed.

**Comment by dilijev** [comment]
Adding these _static jobs:

image

**Comment by digitalinfinity** [comment]
LGTM

**Pull request merged**
