### PR TITLE
WebAssembly prototype implementation

### PR DESCRIPTION
**Pull request by MikeHolman**
To better facilitate collaboration on our WebAssembly implementation, and have more iterative development, I'd like to merge our prototype into the Microsoft fork. Note that this is still not stable or complete, and it will change, frequently. Use is currently only available through WScript.LoadWasmFile in ch.exe (which uses the JsRunWasmScript JSRT API).

[Review on Reviewable](https://reviewable.io/reviews/microsoft/chakracore/63)

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test this please

**Comment by dilijev** [comment]
@MikeHolman 
In .gitattributes, I think you should mark this as `binary` instead of `-crlf`
See: http://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

**Comment by MikeHolman** [comment]
To keep things moving along, I'm going to merge this in (to the WebAssembly branch) so we can start putting in more changes on top. If you have any comments at this point, please open an issue.

**Comment by MikeHolman** [comment]
Squashed and merged in: https://github.com/Microsoft/ChakraCore/commit/e44a8b287b04698f423787965201a3e7d0c1c820

**Pull request closed without merging**
