### PR TITLE
Object.hasOwnProperty with no arguments or undefined should return true

### LINKED ISSUE #6477: A question about Object.prototype.hasOwnProperty
When the `obj` is `this` and  the method `Object.prototype.hasOwnProperty` has no arguments, other engines like V8, spiderMonkey, and javascriptCore pass a default value and get an output with a value of `true`, while chakraCore gets a `false`. Is this an issue about the default parameter?

#### version

```
v1.11.8
```

#### command

```
ChakraCore/out/Debug/ch testcase.js
```

#### testcase

```javascript
var NISLFuzzingFunc = function(){
    var obj = this;
    var res1 = obj.hasOwnProperty();
    print(res1);
    var res2 = obj.hasOwnProperty(undefined);
    print(res2);
};
NISLFuzzingFunc();
```

#### output

```
false
true
```

#### expected output

```
true
true
```

Contributor:[@YuanWangC](https://github.com/YuanWangC)

### PR DESCRIPTION
**Pull request by tondrej**
#6477

### CODE REVIEW

**Comment by rhuanjl** [comment]
Hi @tondrej thanks for this submission, I'm afraid this isn't quite the correct fix.

The condition on line 82 is checking for no arguments existing and previously we were doing an early return of false in this case.

What we actually need to do is not return `undefined` instead BUT instead use `undefined` instead of args[1], so do something like this:
```js
Var argument = args.Info.Count > 1 ? scriptContext->GetLibrary()->GetUndefined() : args[1];
```
And then use `argument` instead of `args[1]` further down.

**Comment by tondrej** [comment]
Hi @rhuanjl thank you for your help and sorry it seems I've misunderstood the problem completely. 😄 

I think you might have meant

```js
Var argument = args.Info.Count == 1 ? scriptContext->GetLibrary()->GetUndefined() : args[1];
```
(ie. when no argument provided, assume undefined)

Cheers!

**Comment by rhuanjl** [comment]
You're correct I had the condition backwards. We do indeed need to use undefined if args.Info.Count == 1.

**Comment by GentileFulvio** [comment]
Why was this PR closed ?

**Pull request closed without merging**
