### PR TITLE
Generating branch and compare fast paths in additional conditions

### PR DESCRIPTION
**Pull request by rajatd**
Allow generating string and object fast paths for branches and compares even if, along with strings and objects, we have seen objects of types other than string/object.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1898)

### CODE REVIEW

**Comment by rajatd** [comment]
@LouisLaf , @satheeshravi

**Comment by agarwal-sandeep** [comment]
LGTM me, please add tests. Targeted tests are always a good idea 😄

**Comment by rajatd** [comment]
@agarwal-sandeep could you take another look, please?

**Comment by rajatd** [comment]
Please hold off on reviewing this change. I have to overhaul the change to do what it intended to and keep it functionally correct.

**Comment by rajatd** [comment]
Closing this one. Will submit another PR after fixing all the issues.

**Pull request closed without merging**
