### PR TITLE
changed ./test.js to ./test

### PR DESCRIPTION
**Pull request by vinay72**
I think this might be the reason that module syntax errors are not showing properly. I have changed `import test from "./test.js"; ` to `import test from "./test";`. Issue #3357

### CODE REVIEW

**Comment by dilijev** [comment]
IMO the test not showing the error correctly reveals a problem, and this fix is hiding that problem rather than fixing the underlying cause. We're not so concerned about this particular test, but rather how the issue will appear to users.

**Comment by fatcerberus** [comment]
I'm a little confused by this PR - it claims to be a fix, but the only change in the PR is to add an entirely new HTML file...

**Comment by vinay72** [comment]
Is there anything else , I need to do to fix this issue.

**Comment by dilijev** [comment]
If you'll pardon my confusion, there doesn't seem to be a fix here at all. You've added a brand-new test file that may or may not exhibit a problem, have not hooked it up to our unit tests, and there is no actual code fix for the issue.

**Comment by vinay72** [comment]
Okkay Fine.

**Comment by fatcerberus** [comment]
@dilijev It seems like there was a misunderstanding here and the PR is "fixing" someone else's bug repro case.

**Comment by vinay72** [comment]
Okkay, No problem sir.

**Comment by dilijev** [comment]
Oh, I understand. I'm going to link to this PR from that issue, and add the suggestion as a comment over on that issue, and close the PR. Thanks for contributing to that issue, @vinay72

**Pull request closed without merging**
