### PR TITLE
Updating baseline file for test

### PR DESCRIPTION
**Pull request by mike-kaufman**

### CODE REVIEW

**Comment by VSadov** [comment]
No idea about the failures. The test should be stable. It basically checks that based on the flow analysis we see 1 jit-time bailout with AggressiveMulIntTypeSpecDisabled  (to prevent more aggressive bailouts later that impact code quality too much). The bailout should be deterministic.

**Comment by VSadov** [comment]
I also do not quite understand why rebaselining was needed. The test relies on bytecode offsets (that is a bit unfortunate). Sometimes those change because of unrelated changes, so I assumed that was the case. Now - why rebaselining needs only in release?
It seems as if we picked a change that results in different bytecode between release/debug. That seems strange.

**Comment by VSadov** [comment]
Either release or debug baselines validate what the test needs to check, it is just the offsets are different (and that is not the interesting part)
If possible, can we just disable the test in release? 
And enter a bug for me to follow up separately on why release has a different offset.

**Comment by mike-kaufman** [comment]
note sure it's a release/debug thing... It's passing with new baselines on x64 chk on my workstation.

**Comment by VSadov** [comment]
Lets just disable the test then.

**Comment by VSadov** [comment]
It does not look like we have a functional regression. It is just a test gone flakey - perhaps need to test in some different way.

**Comment by mike-kaufman** [comment]
@VSadov  - what exactly were you trying to test here?

**Comment by mike-kaufman** [comment]
OK, deleted test now.

**Comment by VSadov** [comment]
I am trying to check the exact number and the nature of bailouts. More precisely we want AggressiveMulIntTypeSpecDisabled, but we do not want AggressiveIntTypeSpecDisabled.

**Comment by dilijev** [comment]
@jackhorton did we add a flag to remove bytecode offset dependencies from baseline output?

**Pull request closed without merging**
