### PR TITLE
WASM.SIMD merge as of 07/26/2017 (WRONG TARGET -- needs to be merged in wasm.simd ) 

### PR DESCRIPTION
**Pull request by Krovatkin**
This PR merges the master branch (as of 07/17/2017) into `wasm.simd` to facilitate a SIMD.JS code cleanup

### CODE REVIEW

**Comment by Krovatkin** [comment]
@Cellule @MikeHolman Please disregard this PR for now. I need to double check it clears the tests first and also update the remaining `ENABLE_WASM` to `ENABLE_WASM_SIMD`. 
Thanks!

fyi @arunetm

**Comment by Krovatkin** [comment]
@Cellule Sorry to bother you. I was wondering if you could advise me `PrintI64` is currently being used in any of the wasm tests? I had to update it since `0xfd` is reserved for SIMD. Nothing seems to have blown up in my face...YET :-) Asking you is probably more efficient than decoding every single wasm module in `test` directory :-)

**Comment by Krovatkin** [comment]
updated to master's tip as of 07/26/2017 

```
$git log --oneline -10 msft/master
6d310c3 [1.7>master] [MERGE #3432 @MSLaguana] Fixing debug assert failure in WriteStringCopy
55a0eb1 [MERGE #3432 @MSLaguana] Fixing debug assert failure in WriteStringCopy
```

**Comment by Krovatkin** [comment]
@MikeHolman @Cellule ,guys, could you please take a look at this PR? It seems to be a decent starting point

**Comment by Cellule** [comment]
> @Cellule Sorry to bother you. I was wondering if you could advise me PrintI64 is currently being used in any of the wasm tests? I had to update it since 0xfd is reserved for SIMD. Nothing seems to have blown up in my face...YET :) Asking you is probably more efficient than decoding every single wasm module in test directory :)

We never produce these values directly. They're directly used from c++ for testing purposes. You can give them any values really. My intention initially was to use negative values for testing ops, but I didn't foresee that the new Wasm features would do the same. Just change what ever conflict for something else and I'll figure something else eventually.

**Comment by Cellule** [comment]
Right now this PR is to merge into master, the point was to merge master into wasm.simd. Can you change the branch target.

**Comment by Krovatkin** [comment]
@Cellule Yes, good catch!

**Comment by Krovatkin** [comment]
@Cellule I'm going to close this one and open a new one.

**Pull request closed without merging**
