### PR TITLE
swb,plugin: cleanup, support OSX and plugin arguments

### PR DESCRIPTION
**Pull request by jianchun**
Make the clang plugin work on OSX.

OSX note: Must run the same clang binary for which the plugin was built for. e.g.:

```
./build.sh -n -d --icu=/usr/local/opt/icu4c/include/ \
                 --cxx=/usr/local/opt/llvm/bin/clang++ \
                 --cc=/usr/local/opt/llvm/bin/clang \
                 --wb-check lib/Runtime/Base/FunctionBody.cpp
```

Clean up plugin build script and sources.

Add plugin arguments support. Arguments can be directly passed from top
level "build.sh".

Changed --wb-check default output to "ERROR" only. To output verbose, use
plugin argument "-verbose":

```
build.sh -n -d --wb-check lib/Runtime/Base/FunctionBody.cpp \
         --wb-args=-verbose
```

### CODE REVIEW

**Comment by jianchun** [comment]
@dotnet-bot test Linux tests please

**Comment by jianchun** [comment]
@leirocks Please help CR, thanks!

**Comment by digitalinfinity** [comment]
:shipit:

**Comment by jianchun** [comment]
Thanks @digitalinfinity !

**Pull request merged**
