### PR TITLE
Small cleanup in byte code gen. 

### PR DESCRIPTION
**Pull request by pleath**
Remove from FuncInfo the hasGlobalReference bit, which has no significant uses, and the hasCapturedThis bit, which has no uses at all.

### CODE REVIEW

**Comment by pleath** [comment]
@aneeshdk Can you look at this, and can you think about whether the "this lexically captured" bit can be cleaned up as well? (Thanks.)

**Comment by aneeshdk** [comment]
LGTM. I will look at the this lexically captured bit as part of the work to make this a normal symbol.

**Comment by akroshg** [comment]
:shipit:

**Comment by pleath** [comment]
@dotnet-bot please, please, please, test Windows ci_disablejit_x64_debug

**Pull request merged**
