### PR TITLE
Return exit code from unit test failure

### PR DESCRIPTION
**Pull request by digitalinfinity**

### CODE REVIEW

**Comment by digitalinfinity** [comment]
Expect these tests to fail- will update the PR to pass in the right flags to runtests to get the tests to pass once the failure is verified

**Comment by dilijev** [comment]
Failed test detection looks good -- now to fix up the tests :P

**Comment by digitalinfinity** [comment]
and now the tests pass :smile:

**Comment by jianchun** [comment]
👍 Nice! Thanks for fixing this!

**Comment by digitalinfinity** [comment]
Thanks @jianchun- rebased to squash commit- will merge once CI is green again

**Comment by dilijev** [comment]
LGTM :)

**Pull request merged**
