### PR TITLE
Function.name is a non-writable property

### LINKED ISSUE #153: Function.name property is non-writable. It should be initialized as such.
SimplePropertyDescriptor const JavascriptLibrary::SharedFunctionPropertyDescriptors[2] =
    {
        SimplePropertyDescriptor(BuiltInPropertyRecords::prototype, PropertyWritable),
        SimplePropertyDescriptor(BuiltInPropertyRecords::name, PropertyConfigurable | PropertyWritable)
    };

### PR DESCRIPTION
**Pull request by sankha93**
Fixes #153.

### CODE REVIEW

**Comment by farzonl** [comment]
LGTM

**Comment by rajatd** [comment]
Looks good. Could you also add some tests to test/es6/function.name.js to guard against such cases as you were trying to reproduce?

**Comment by farzonl** [comment]
I believe that test case already exists:
line 434
{
       name: "built-in function.name",
       body: function ()
       {
            assert.areEqual("slice",[].slice.name,"name should be slice");
            [].slice.name = "bar";
            assert.areEqual("slice",[].slice.name, "function names are read only");
       }
    },

**Comment by ianwjhalliday** [comment]
I don't think we have a good way to test this issue since it was an incorrect initial type that was just ignored (converted) when adding the actual property. @rajatd is there a good way to test this? Is it worthwhile to test this?

**Comment by rajatd** [comment]
@ianwjhalliday, Yes I agree that there's no test to add. The snippet shown by @farzonl serves the purpose

**Pull request merged**
