### PR TITLE
a few '/bin' file name case changes

### PR DESCRIPTION
**Pull request by jianchun**
Change a few '/bin' file names to consistent CamelCase and update
references.

Update a few includes in lib/Common/Common.h (which my previous regex
match missed).

### CODE REVIEW

**Comment by jianchun** [comment]
Not sure on "stdafx" vs. "StdAfx". Picked "stdafx" because most of our code uses it and a new VS2015 project uses it. @dilijev @digitalinfinity

**Comment by dilijev** [comment]
LGTM

**Comment by dilijev** [comment]
Agree on stdafx in all lowercase. It's alphabet soup anyway, not sure PascalCase would make a difference.

**Comment by jianchun** [comment]
@dilijev Thank you!

**Pull request merged**
