### PR TITLE
xplat: Improve ICU build options

### PR DESCRIPTION
**Pull request by obastemur**
- optional ICUDATA dependency
- Default to --no-icu instead of icucore on OSX

### CODE REVIEW

**Comment by obastemur** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug please

**Comment by obastemur** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug please

**Comment by obastemur** [comment]
Hmm. @dotnet-bot .. are you there? /cc @mmitche

**Comment by mmitche** [comment]
@dotnet-bot help

**Comment by mmitche** [comment]
@obastemur Hrmm...not sure what is up.  Checking

**Comment by mmitche** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug

**Comment by mmitche** [comment]
@obastemur There is an issue with GitHub I think.  It is now showing that no webhooks have been attempted to be delivered since around 9:30 (this is across multiple CI instances)

**Comment by obastemur** [comment]
@mmitche Thanks for looking into it. Will try again later.

**Comment by digitalinfinity** [comment]
I think this should let us use Node's ICU for node-chakracore. @kunalspathak can you look at how to make that work? Otherwise, LGTM /cc @kfarnung

**Comment by obastemur** [comment]
@digitalinfinity @kfarnung Thanks for the review

**Pull request merged**
