### PR TITLE
Delete NativeCodeGenerator on the background thread.

### PR DESCRIPTION
**Pull request by dilijev**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot help (testing help message)

**Comment by MikeHolman** [comment]
What is the motovation behind this change? Is there a perf benefit? I'd expect this one time cost is pretty small.

**Comment by digitalinfinity** [comment]
@dilijev does this also move PDATA/DATA unregistration to the background thread? I thought that was the expensive part?

**Comment by dilijev** [comment]
@MikeHolman In Speedometer, we see a lot of creation and deletion of ScriptContext as we create and destroy iframes for each test. Doing this cleanup work on the foreground thread adds to the total recorded execution time of the tests. This is work that can be done on the background thread. There's a lot of code here but the idea is really straightforward: run HeapDelete(nativeCodeGen) on the background thread as a work item that gets queued up when the ScriptContext is deleted.

@digitalinfinity The thought was that doing this would move xdata deregistration to the background thread as well, but after stepping through it we released that work is actually done elsewhere. Moving that to the background will be a future work item.

**Comment by digitalinfinity** [comment]
Interesting- if xdata unregistration isn't accounted for here, then what is the cost associated with freeing the NativeCodeGenerator? I suspect that the xdata cost during script context close is incurred when it walks through all the function bodies and calls cleanup. @curtisman had the idea to do a background finalizedispose phase- I reckon that would have helped on the xdata front

**Comment by dilijev** [comment]
@dotnet-bot test Windows daily_disablejit_x64_test please

**Comment by dilijev** [comment]
@dotnet-bot test Windows daily_disablejit_x64_test please

**Comment by dilijev** [comment]
Perf testing showed that there's no benefit to this change without also the xdata deregister moved to the background thread, and there may be a regression. Too risky to include at this time. Shelving this work for now.

**Pull request closed without merging**
