### PR TITLE
CrossPlatform: inc/type_traits shadowed by system header (__APPLE__)

### PR DESCRIPTION
**Pull request by obastemur**

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test Copyright Check please

**Comment by jianchun** [comment]
Thank you @obastemur for this fix. Could you please rebase it to latest linux HEAD?

**Comment by obastemur** [comment]
> Thank you @obastemur for this fix. Could you please rebase it to latest linux HEAD?

Done

**Comment by jianchun** [comment]
> Thank you @obastemur for this fix. Could you please rebase it to latest linux HEAD?
> 
> 
> Done

Sorry, the update seems leaked a .gyp file?

**Comment by obastemur** [comment]
> Sorry, the update seems leaked a .gyp file?

Sorry. updated / fixed.

**Comment by jianchun** [comment]
> Sorry, the update seems leaked a .gyp file?
> 
> 
> Sorry. updated / fixed.

I'm sorry, but it looks https://github.com/obastemur/ChakraCore/commits/linux_shadow_stl is not based on latest Microsoft/linux HEAD. Your commit parent is "Checkpoint commit: lib/common/core". Please rebase it to latest so parent be "build lib/common/DataStructures".

**Comment by jianchun** [comment]
@obastemur Please ignore previous rebase request. I've hand merged it and pushed. Again, thanks for your PR!

**Comment by obastemur** [comment]
@jianchun thanks!

**Pull request merged**
