### PR TITLE
Disable randombug.js on CCRobot until it is fixed

### PR DESCRIPTION
**Pull request by obastemur**

### CODE REVIEW

**Comment by jianchun** [comment]
I don't understand your 2nd commit -- why do you ignore output of xplatinterval test? On success it is supposed to print "pass" and before change is fine.

**Comment by obastemur** [comment]
It fails on Windows slow runs

**Comment by obastemur** [comment]
> As a note, <baseline/> is mostly only useful for one scenario -- your test wants to verify an ASSERT or AV which crashes and returns non-zero exit code.

Just realized.. on CH we don't set exit code to none 0 when we throw from JS land. Anyone knows why?

**Comment by obastemur** [comment]
@jianchun Thanks for the review

**Pull request merged**
