### PR TITLE
cross platform: ch runs on OSX and passes 1198 tests

### PR DESCRIPTION
**Pull request by obastemur**
We have some minor issues left with ICU, PAL and stack limits. (24 failing tests)

### CODE REVIEW

**Comment by obastemur** [comment]
Note: This PR needs #1234 is merged first

**Comment by obastemur** [comment]
Linux test fails are expected. After #1234 is merged, will re-run on CI.

**Comment by obastemur** [comment]
@digitalinfinity @jianchun ping?

**Comment by dilijev** [comment]
LGTM

**Comment by obastemur** [comment]
@dilijev Thanks for the review

**Pull request merged**
