### PR TITLE
WASM.SIMD merge as of 07/26/2017  

### PR DESCRIPTION
**Pull request by Krovatkin**
This PR merges the master branch (as of 07/17/2017) into `wasm.simd` to facilitate a SIMD.JS code cleanup

### CODE REVIEW

**Comment by Krovatkin** [comment]
@Cellule Opened a new PR against `wasm.simd`.

**Comment by Cellule** [comment]
@Krovatkin in test/wasm.simd/rlexe.xml, instead of adding `exclude_xplat` to every test, it will be simpler to add the tag to test/rlexedirs.xml to the wasm.simd folder

**Comment by Cellule** [comment]
FYI, there is an unresolved conflict in WasmSignature.cpp

**Comment by Krovatkin** [comment]
@Cellule 

> @Krovatkin in test/wasm.simd/rlexe.xml, instead of adding exclude_xplat to every test, it will be simpler to add the tag to test/rlexedirs.xml to the wasm.simd folder

Actually, there **is** `exclude_xplat ` tag on `wasm.simd` folder in `rlexedirs.xml`. I wanted to try out these tests on Linux but I forgot to switch it back before I pushed my last commit :-( 

> FYI, there is an unresolved conflict in WasmSignature.cpp
Missed this one :-( Thanks! I actually wanted to talk to you guys about short signatures after we get 64x2 types in.

**Comment by Cellule** [comment]
LGTM.
Also, in order to reduce the amount of effort needed to merge master into wasm.simd, we should try to do it at a more frequent pace (every 2 weeks maybe?).
Hopefully most merge would take no time at all.

**Comment by Cellule** [comment]
I'll do a quick test in ChakraFull then I'll merge this

**Comment by Cellule** [comment]
@Krovatkin, I did a merge in ChakraFull of master into wasm.simd of the matching commit you used and there are some unittest failures.
Are you able to see the run ?

**Comment by Krovatkin** [comment]
@Cellule 
> do it at a more frequent pace (every 2 weeks maybe?).
Hopefully most merge would take no time at all.

Aye, aye, captain!

> Are you able to see the run ?


I was wondering if you might have a link to those failures? I don't think I'm going to be able to access it, but I think @arunetm should be able to.

**Comment by Krovatkin** [comment]
@Cellule , could you please this fix?

**Comment by Cellule** [comment]
Yup will do. I get back to you with the testing result and merge if all green

**Comment by Krovatkin** [comment]
@Cellule thank you! Amusez-vous bien a Montreal! :-)

**Comment by Cellule** [comment]
I took the liberty to do one more integration of master into wasm.simd.
The merge was very easy and passed the CI on my end.

**Comment by Krovatkin** [comment]
@Cellule Wonderful! Thanks! 

> I took the liberty to do one more integration of master into wasm.simd.

Yeah, I should've done that :-(

**Comment by Cellule** [comment]
> Yeah, I should've done that :-(

Don't worry about it. It is much easier for me to do with access to ChakraFull

**Pull request merged**
