### PR TITLE
Proxy object should be allowed in WeakMaps

### PR DESCRIPTION
**Pull request by akroshg**
When we use the WeakMaps we set the internal property on the object,
however proxy object didn't handle the Set/GetInternalProperty. Fixed that
by adding the support.

Added a test

### CODE REVIEW

**Comment by akroshg** [comment]
@kunalspathak please have a look.

**Comment by akroshg** [comment]
Fixes #1662

**Comment by kunalspathak** [comment]
LGTM

**Comment by akroshg** [comment]
@dotnet-bot test OSX osx_osx_debug_static please

**Comment by akroshg** [comment]
@dotnet-bot test OSX osx_osx_debug_static please

**Pull request merged**
