### PR TITLE
Add -includeSlow to dev12 builds to improve test coverage.

### LINKED ISSUE #283: Enable -includeSlow on Legacy daily builds.
Currently -includeSlow is only specified on the [Builds with Slow Tests](https://github.com/Microsoft/ChakraCore/wiki/Build-Status#builds-with-slow-tests) configuration.

Since the Legacy builds also run once per day it makes sense to add -includeSlow to increase coverage.

### PR DESCRIPTION
**Pull request by dilijev**
Fixes #283

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test dev12 please

**Comment by dilijev** [comment]
Note that this change will not take effect until after it is merged in.

Note that failures here are existing failures in the daily build. Try again after they have been fixed.

**Comment by dilijev** [comment]
@dotnet-bot test Windows 7 daily_dev12_x64_test please

**Comment by dilijev** [comment]
@mmitche Any idea why the above comment triggered all of the default builds as well as the one I wanted? Is this because of the Jenkins system being reset recently? (The last update on this PR was almost 2 weeks ago.)

**Comment by mmitche** [comment]
Yes that's why.

Sent from my Windows Phone
________________________________

**Comment by abchatra** [comment]
Any update here?

**Comment by dilijev** [comment]
@abchatra Waiting on the pull requests which address existing breaks in Legacy builds to be committed to master first. Don't want to potentially introduce more breaks while it's already broken.

See #386 and #444 which will fix some or all of the issues.

**Comment by nmostafa** [comment]
#444 is already merged and should fix some failures. #386 will not fix Asmjs link failure. Seems AsmJs linking was broken for a while but not tested (with or without SIMD).

**Comment by dilijev** [comment]
Once #551 is merged, I'll try the tests again and if they pass we can merge this change as well.

**Comment by dilijev** [comment]
Since #609 has been merged to fix the issues, I'm trying these tests again.

**Comment by dilijev** [comment]
@dotnet-bot test dev12 tests please

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Pull request merged**
