### PR TITLE
Using WebAssembly.RuntimeErorrs

### PR DESCRIPTION
**Pull request by arunetm**
Throw WebAssembly.RuntimeErorrs for wasm traps.

Fixes: https://github.com/Microsoft/ChakraCore/issues/1991

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/2097)

### CODE REVIEW

**Comment by arunetm** [comment]
@Cellule Please review.

**Comment by Cellule** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/Backend/LowerMDShared.cpp, line 5901 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/2097#-KXgPnTOw6i8nKF3WVS9:-KXgPnTOw6i8nKF3WVSA:b-7q88w2) ([raw file](https://github.com/microsoft/chakracore/blob/438917d75b710f741d1d46794db83fc7a2d4a7ae/lib/Backend/LowerMDShared.cpp#L5901)):*
> IR::Instr *throwInstr = IR::Instr::New(
        Js::OpCode::RuntimeTypeError,
        IR::RegOpnd::New(TyMachReg, m_func),
        IR::IntConstOpnd::New(SCODE_CODE(VBSERR_Overflow), TyInt32, m_func),
        m_func);
    instr->InsertBefore(throwInstr);
    this->m_lowerer->LowerUnaryHelperMem(throwInstr, IR::HelperOp_RuntimeTypeError);

We should change to
```
this->m_lowerer->GenerateThrow(IR::IntConstOpnd::New(SCODE_CODE(VBSERR_Overflow), TyInt32, m_func), instr);
```

---

*[lib/Parser/rterrors.h, line 383 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/2097#-KXgQm-XS2PMei35co7q:-KXgQm-XS2PMei35co7r:b-i1vkbb) ([raw file](https://github.com/microsoft/chakracore/blob/438917d75b710f741d1d46794db83fc7a2d4a7ae/lib/Parser/rterrors.h#L383)):*
> ```objc
> RT_ERROR_MSG(WASMERR_ElementSegOutOfRange, 5681, "", "Element segment is out of range", kjstTypeError, 0)
> RT_ERROR_MSG(WASMERR_TableIndexOutOfRange, 5682, "", "Table index is out of range", kjstWebAssemblyRuntimeError, 0)
> RT_ERROR_MSG(WASMERR_ArrayIndexOutOfRange, 5683, "", "WebAssembly array index is out of range", kjstWebAssemblyRuntimeError, 0)
> ```

The array is known as `Memory` to the user.
We should use `Memory index is out of range` to be more constant with the other error messages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/2097)*

**Comment by arunetm** [comment]
*[lib/Backend/LowerMDShared.cpp, line 5901 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/2097#-KXgPnTOw6i8nKF3WVS9:-KXgWf8p_wFpyOQhxwQU:b-bsbvwp) ([raw file](https://github.com/microsoft/chakracore/blob/438917d75b710f741d1d46794db83fc7a2d4a7ae/lib/Backend/LowerMDShared.cpp#L5901)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

> IR::Instr *throwInstr = IR::Instr::New(
        Js::OpCode::RuntimeTypeError,
        IR::RegOpnd::New(TyMachReg, m_func),
        IR::IntConstOpnd::New(SCODE_CODE(VBSERR_Overflow), TyInt32, m_func),
        m_func);
    instr->InsertBefore(throwInstr);
    this->m_lowerer->LowerUnaryHelperMem(throwInstr, IR::HelperOp_RuntimeTypeError);

We should change to
```
this->m_lowerer->GenerateThrow(IR::IntConstOpnd::New(SCODE_CODE(VBSERR_Overflow), TyInt32, m_func), instr);
```
</blockquote></details>

Ah yes. sure. Had this change but lost it during a merge. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/2097)*

**Comment by arunetm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/Parser/rterrors.h, line 383 at r1](https://reviewable.io:443/reviews/microsoft/chakracore/2097#-KXgQm-XS2PMei35co7q:-KXgWrfcR5rhhV5vxB3b:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/438917d75b710f741d1d46794db83fc7a2d4a7ae/lib/Parser/rterrors.h#L383)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary><blockquote>

The array is known as `Memory` to the user.
We should use `Memory index is out of range` to be more constant with the other error messages
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/2097)*

**Comment by Cellule** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/2097#-:-KXgwsI4jJIugRgJgI1p:bnfp4nl)*

**Pull request merged**
