### PR TITLE
xplat: fix position independent compiler direction

### PR DESCRIPTION
**Pull request by obastemur**
+ minor fixes to JavascriptOperatorA.S

### CODE REVIEW

**Comment by obastemur** [comment]
Fixes #2009

**Comment by jianchun** [comment]
@obastemur Apologize for my CR delay. I had to refresh my memory of this "fake frame" thing, esp. seeing you adding debug info directives to `amd64_CallWithFakeFrame` and adjusting its stack layout.

It appears to me adding debug info directives here is unnecessary. They are (almost) never needed. The goal of `amd64_CallWithFakeFrame` is to simulate our JIT frame stack layout. When an exception occurs in JIT code (e.g. a try block) and the system needs to rewind native stack, the .eh_frame data for the `container` JIT function (the function containing the try block) applies. Since `amd64_CallWithFakeFrame` creates exactly the same stack layout, the `container` JIT function's .eh_frame data helps rewind stack to parent caller (OP_TryCatch/OP_TryFinally) correctly.

You are correct that in `OP_TryFinally` the 2nd call to `amd64_CallWithFakeFrame` fails because the first call corrupted the stack. The corruption is actually from

```
        // The stack walker uses this marker to skip this frame.
        // Note that we use rip-relative addressing here since this
        // library is shared and therefore the code has to be position independent
        lea rax, [rip + C_FUNC(amd64_ReturnFromCallWithFakeFrame)]
        mov [rsp+8h], rax
```

Note that it puts address of `amd64_ReturnFromCallWithFakeFrame` to *`[rsp + 8h]`* -- a stack location in parent frame (below return address). In the case of `OP_TryFinally`, that location happens to store parameter `finallyAddr`, causing the 2nd call skip real finally block and directly jumps to `amd64_ReturnFromCallWithFakeFrame`.

Could you please try a different fix instead? Just delete the lines above. It should not write to parent frame. I searched and did not find any proof of the statements in the comment. That is probably outdated. You can even delete the `extern "C" void *amd64_ReturnFromCallWithFakeFrame(void);` declaration from JavascriptStackWalker.cpp.

The same code may need to be deleted from "JavascriptOperatorsA.asm" too.

**Comment by obastemur** [comment]
@jianchun After seeing the usages below, I was more into fixing the problem on the place it happened.

see https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/LowerMDShared.cpp#L472-L500 

https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/amd64/LowererMDArch.cpp#L3110-L3133

in case the usage above is also `outdated`, agree cleanup is the best idea.

Opinions ?

**Comment by obastemur** [comment]
BTW; @jianchun Thanks for the in details explanation above, for sure I really admire the quality comments like that. 👍

**Comment by jianchun** [comment]
> @jianchun After seeing the usages below, I was more into fixing the problem on the place it happened.
> see https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/LowerMDShared.cpp#L472-L500
> https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/amd64/LowererMDArch.cpp#L3110-L3133
> in case the usage above is also outdated, agree cleanup is the best idea.
> Opinions ?

I also searched and read those code. I thought they were legitimate code, independent and unrelated to the problematic code I posted above. They push `amd64_ReturnFromCallWithFakeFrame` to stack and `RET`, that's how the `try` block code returns normally without exception. They don't use/need the problematic code above to store RET address. Any reason you concerned about them?

Thanks!

**Comment by obastemur** [comment]
@jianchun Thanks for the review and awesome comments

**Pull request merged**
