### PR TITLE
pal: do not init PAL sync manager thread

### PR DESCRIPTION
**Pull request by obastemur**
ChakraCore's usage of PAL doesn't require PAL sync manager thread. Nothing big here but CC will consume 1 less bg thread.

### CODE REVIEW

**Comment by MSLaguana** [comment]
@dotnet-bot test this please

**Comment by digitalinfinity** [comment]
What is the synchronization manager?

**Comment by obastemur** [comment]
https://github.com/Microsoft/ChakraCore/pull/3731/files#diff-eeebc3d73b2545f7ebf87a91712d4360L1818

a separate thread to handle cross pr/th messages those we have no use or intention to use.

**Pull request merged**
