### PR TITLE
enabling Reinterpret_ITF in codegen + simple tests 

### PR DESCRIPTION
**Pull request by Krovatkin**

### CODE REVIEW

**Comment by Krovatkin** [comment]
@Cellule Could you please take a look whenever you have a mnt? 

fyi: @commonlisp @arunetm

**Comment by Cellule** [comment]
:shipit:

**Comment by Krovatkin** [comment]
@commonlisp @arunetm guys could one of you merge this pls?

**Comment by arunetm** [comment]
I got this. Thanks.

**Comment by Krovatkin** [comment]
@Cellule could you please sign off on this again. Had to be rebased. fyi @arunetm

**Pull request merged**
