### PR TITLE
Wasm: Function bodies bugfix + cleanup

### PR DESCRIPTION
**Pull request by Cellule**
Fix bug with the last function bodies decoding
ProcessCurrentSection now reads the whole section.
Use different function for different behavior.
@MikeHolman @commonlisp can you guys review this

---
This change is [Review on Reviewable](https://reviewable.io/reviews/microsoft/chakracore/521)

### CODE REVIEW

**Comment by commonlisp** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/WasmReader/SExprParser.cpp, line 544 \[r1\]](https://reviewable.io:443/reviews/microsoft/chakracore/521#-KCXUoP5EByeB2BJ_aa_:-KCXUoP5EByeB2BJ_aaa:-1151596773) ([raw file](https://github.com/microsoft/chakracore/blob/fa961ca00c64afcaa7484967b369a8e91316dd7f/lib/WasmReader/SExprParser.cpp#L544)):*
Do we still need this test?

---

*[lib/WasmReader/WasmBinaryReader.cpp, line 509 \[r1\]](https://reviewable.io:443/reviews/microsoft/chakracore/521#-KCXmyKBNV5Oc72XclEk:-KCXmyKCEw4KzHfYVDHA:-826560650) ([raw file](https://github.com/microsoft/chakracore/blob/fa961ca00c64afcaa7484967b369a8e91316dd7f/lib/WasmReader/WasmBinaryReader.cpp#L509)):*
It would still be nice to factor this and associated error checking out since so many functions use it.

---

*[lib/WasmReader/WasmBinaryReader.cpp, line 598 \[r1\]](https://reviewable.io:443/reviews/microsoft/chakracore/521#-KCXX0meq6A6TKsq-dMD:-KCXX0mfNcZrXMTuX0p7:-2120557930) ([raw file](https://github.com/microsoft/chakracore/blob/fa961ca00c64afcaa7484967b369a8e91316dd7f/lib/WasmReader/WasmBinaryReader.cpp#L598)):*
Is entries == 0 even legal? If not, we should consider doing some error reporting.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/chakracore/521)*

**Comment by commonlisp** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/WasmReader/WasmReader.h, line 68 \[r1\]](https://reviewable.io:443/reviews/microsoft/chakracore/521#-KCXsMYTJgBzEM37HRWE:-KCXsMYUjNfr4eRkNh47:-880936052) ([raw file](https://github.com/microsoft/chakracore/blob/fa961ca00c64afcaa7484967b369a8e91316dd7f/lib/WasmReader/WasmReader.h#L68)):*
Is this closing #if DBG now? Is the order right for #if DBG and #ifdef ENABLE_WASM?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/chakracore/521)*

**Comment by Cellule** [comment]
Hold off on this PR for the moment. @MikeHolman and I were working on fixing some of the remaining bugs to run hello_world and zlib

**Comment by Cellule** [comment]
Closing in favor of #532

**Pull request closed without merging**
