### PR TITLE
Pal update

### PR DESCRIPTION
**Pull request by rhuanjl**
Trialing a possible fix for #5973 - want to see if it passes Ubuntu CI.

This takes @tomasdeml's fix though removes part of it that is wrapped in an #ifdef that should always be false.

This change was part of an update to the CoreCLR over a year after the ChakraCore team forked PAL for use in ChakraCore and not an intentional difference.

### CODE REVIEW

**Comment by rhuanjl** [comment]
**Further notes**
1. I scanned back through the CoreCLR commit history and found where these changes came in - they were after ChakraCore forked PAL and hence the omission was not intentional.

2. With the change the CI checks pass, that means that (among other things) built with this change on Ubuntu, ch (a CPP chakracore host) can successfully run a pretty extensive test suite. I'm not really sure how else we can usefully test this change for breakage; and considering that repro'ing the bug requires linking against .NET I don't think we can add the repro to the source tree, we may in the future be able to add a .NET use case to the CI, but that would be a non-trivial exercise.

3. @Taritsyn and @tomasdeml please could you confirm that this commit fixes the problems you've had?

4. Pensding on point 3 I'd be happy to land this in master and include whenever we release 1.12 (probably sometime in June). Though, @zenparsing do you have any thoughts?

**Comment by Taritsyn** [comment]
I tested this version on the [SegmentationFaultRepro](https://github.com/Microsoft/ChakraCore/files/2904622/SegmentationFaultRepro.zip) project under Ubuntu and everything works correctly.

It is useless to try on my test suite, because my library is only compatible with stable version of the ChakraCore (version 1.11.X).

**Comment by rhuanjl** [comment]
@Taritsyn Thanks for the quick reply - is there anything particular that's caused your library to break with ChakraCore master, we ideally want to avoid any regressions prior to releasing the next version.

**Comment by ppenzin** [comment]
There are some difference between PAL headers in Chakra and latest dotnet - that is what I stumbled into trying to build on FreeBSD (latest dotnet builds, while Chakra does not). I am not sure how compatible those headers have to be between dotnet and Chakra if one were to use Chakra from dotnet.

**Comment by Taritsyn** [comment]
> … - is there anything particular that's caused your library to break with ChakraCore master, we ideally want to avoid any regressions prior to releasing the next version.

There are a lot of things to check.

Perhaps, I may need to change a calculation of the length of return string:

```
Expected: ···"/second-file.jsx");
Actual:   ···"/second-file.jsx");\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0
```

Apparently, error descriptions have become more informative:

```
Expected: Syntax error
Actual:   Unexpected token ')' after '%'
```

When I have free time, I will definitely research and describe these errors.

**Comment by Taritsyn** [comment]
Created a [separate issue](https://github.com/microsoft/ChakraCore/issues/6408) for the errors described here.

**Comment by rhuanjl** [comment]
Note for anyone looking on this, holding off on merging it for now whilst considering possible alternative options in #6404. We intend to merge a fix for this issue before release 1.12, that may be this fix or an alternative per the #6404 discussion.

**Comment by Taritsyn** [comment]
I built the ChakraCore based on the [`3f2e9fe`](https://github.com/microsoft/ChakraCore/tree/3f2e9fe56f57c3b38d568fd3d5b34ef5cfb906ee) commit with replaced [`signal.cpp`](https://raw.githubusercontent.com/microsoft/ChakraCore/7076369d0fade238f1b746217896f0792925fdc2/pal/src/exception/signal.cpp) file. Then I ran tests on 64-bit versions of Windows 10, Ubuntu 16.04.1 and macOS 10.12. In general, all tests were completed except one:

```
Expected: Syntax error
Actual:   Unexpected token ')' after '%'
```

Since this is not an error, but an improvement, we can assume that all tests were successful.

**Review by ppenzin — APPROVED** [review]
I think fixing even some of the long standing issues justify merging this in, though we do need to think about how we handle portability going forward.

**Comment by rhuanjl** [comment]
> I think fixing even some of the long standing issues justify merging this in, though we do need to think about how we handle portability going forward.

Ok - I'll merge this when the tests pass. I think ideally we want to completely excise PAL from the source tree but that's going to be quite a bit of work.

We could fairly simply deal with the string handling stuff it's used for BUT it's also used for thread and exception handling which are messy/complex/pervasive features.

**Pull request merged**
