### PR TITLE
VarIsImpl for Activationobect should include cross-site vtble checks as well

### PR DESCRIPTION
**Pull request by akroshg**

### CODE REVIEW

**Comment by akroshg** [comment]
fixing #5998

**Comment by akroshg** [comment]
@MikeHolman @pleath @wyrichte  this should be quick review.

**Comment by MikeHolman** [comment]
This kind of scares me. How many other VarIs implementations should also be looking at CrossSiteObject?

**Comment by akroshg** [comment]
Most of the places we do typeid check. Only few places we have this problem.

**Pull request merged**
