### PR TITLE
use funPtr instead of voidPtr

### PR DESCRIPTION
**Pull request by obastemur**
This PR replaces https://github.com/Microsoft/ChakraCore/pull/772 and fixes https://github.com/Microsoft/ChakraCore/issues/758

### CODE REVIEW

**Comment by digitalinfinity** [comment]
@LouisLaf FYI

**Comment by digitalinfinity** [comment]
@obastemur have you looked at the test failures here? Seems like quite a few failures

**Comment by obastemur** [comment]
@digitalinfinity @LouisLaf I guess this one is ready for review now.

**Comment by LouisLaf** [comment]
:+1:

**Comment by obastemur** [comment]
Ping.. Can we merge this one?

**Comment by digitalinfinity** [comment]
@obastemur sorry for the delay on this- mind rebasing on the Linux branch please? I can merge this in for you after that.

**Comment by obastemur** [comment]
done rebasing

**Pull request merged**
