### PR TITLE
Run code analysis on dev14 only (dev12 has false positives).

### LINKED ISSUE #553: [Test failure] [Daily] [dev12] Legacy build PreFAST errors
Branched from issue #528 

http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/daily_dev12_x64_release/51/consoleFull#1026559514ac1851af-571d-472f-b664-6657b078a5dd

```
20:38:56 d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\ch.cpp(254): warning C6102: Using 'bcBuffer' from failed function call at line '179'. [d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\ch.vcxproj]
20:38:56 d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\ch.cpp(338): warning C6102: Using 'bcBuffer' from failed function call at line '319'. [d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\ch.vcxproj]
20:38:56 d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\chakrartinterface.cpp(28): warning C6102: Using 'modulename' from failed function call at line '27'. [d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\ch.vcxproj]
20:38:56 d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\helpers.cpp(52): warning C6387: 'file' could be '0':  this does not adhere to the specification for the function 'ftell'. See line 51 for an earlier location where this can occur [d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\ch.vcxproj]
20:38:56 d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\helpers.cpp(51): warning C6387: 'file' could be '0':  this does not adhere to the specification for the function 'fseek'.  [d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\ch.vcxproj]
20:38:56 d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\helpers.cpp(64): warning C6387: 'file' could be '0':  this does not adhere to the specification for the function 'fread'. See line 51 for an earlier location where this can occur [d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\ch.vcxproj]
20:38:56 d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\helpers.cpp(65): warning C6387: 'file' could be '0':  this does not adhere to the specification for the function 'fclose'. See line 51 for an earlier location where this can occur [d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\ch.vcxproj]
20:38:56 [daily_dev12_x---5f770fb3] $ powershell.exe -NonInteractive -ExecutionPolicy ByPass "& 'C:\Users\DOTNET~1\AppData\Local\Temp\2\hudson7084396863305529629.ps1'"
20:38:56 d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\helpers.cpp(52): warning C6387: 'file' could be '0':  this does not adhere to the specification for the function 'ftell'. See line 51 for an earlier location where this can occur
20:38:56 d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\helpers.cpp(51): warning C6387: 'file' could be '0':  this does not adhere to the specification for the function 'fseek'. 
20:38:56 d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\helpers.cpp(64): warning C6387: 'file' could be '0':  this does not adhere to the specification for the function 'fread'. See line 51 for an earlier location where this can occur
20:38:57 d:\j\workspace\daily_dev12_x---5f770fb3\bin\ch\helpers.cpp(65): warning C6387: 'file' could be '0':  this does not adhere to the specification for the function 'fclose'. See line 51 for an earlier location where this can occur
20:38:57 d:\j\workspace\daily_dev12_x---5f770fb3\lib\common\memory\arenaallocator.cpp(1196): warning C28182: Dereferencing NULL pointer. 'cache' contains the same NULL value as 'curWeakRef' did. See line 1196 for an earlier location where this can occur
20:38:57 d:\j\workspace\daily_dev12_x---5f770fb3\lib\common\memory\arenaallocator.cpp(1276): warning C28182: Dereferencing NULL pointer. 'cache' contains the same NULL value as 'curWeakRef' did. See line 1276 for an earlier location where this can occur
20:38:57 d:\j\workspace\daily_dev12_x---5f770fb3\lib\common\memory\recyclerweakreference.h(233): warning C28182: Dereferencing NULL pointer. 'buckets' contains the same NULL value as 'current' did. 
20:38:57 d:\j\workspace\daily_dev12_x---5f770fb3\lib\jsrt\jsrt.cpp(863): warning C28196: The requirement that '*_Param_(2)!=0' is not satisfied. (The expression does not evaluate to true.)
20:38:57 d:\j\workspace\daily_dev12_x---5f770fb3\lib\runtime\bytecode\bytecodegenerator.cpp(3733): warning C6011: Dereferencing NULL pointer 'invertedStmt'. 
20:38:57 d:\j\workspace\daily_dev12_x---5f770fb3\lib\runtime\language\dynamicprofileinfo.cpp(586): warning C6011: Dereferencing NULL pointer 'callSiteInfo[callSiteId].u.polymorphicCallSiteInfo'. See line 578 for an earlier location where this can occur
```

### PR DESCRIPTION
**Pull request by dilijev**
Only run code analysis on configurations for which it will definitely give us more information:

* Default builds: yes
* DisableJIT: yes (effective source code is different so this gives more info)
* Include Slow: no
* Dev12: no (Dev14's code analysis is better, and the code is the same)

Fixes #553 

This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/609)

### CODE REVIEW

**Comment by dilijev** [comment]
@dotnet-bot test dev12 tests please

**Comment by dilijev** [comment]
(Changes to netci.groovy won't take affect until after they are merged in. Not testing the daily builds.)

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by dilijev** [comment]
This change mostly supercedes #551

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by nmostafa** [comment]
Should I be seeing zero dev'12 failures in #603 after re-basing ?

**Comment by dilijev** [comment]
@nmostafa Yes, but the Jenkins tasks need to regenerate first. I'll ping you when they finish.

**Pull request merged**
