### PR TITLE
toFixed : should return toString from numbers >=abs(10^21)

### PR DESCRIPTION
**Pull request by akroshg**
We were doing that for positive value but missed that for negative value - fixed it.

### CODE REVIEW

**Comment by akroshg** [comment]
fixes OS 17774823

**Comment by akroshg** [comment]
thanks @sethbrenith @kfarnung . I should be rebasing this one on 1.10

**Comment by akroshg** [comment]
manually pushed this to 1.10 branch.

**Comment by dilijev** [comment]
For future reference, when you want to change the target branch, you can hit the "Edit" button up top and change the target branch so that you can still merge normally.

**Pull request closed without merging**
