### PR TITLE
Add any preprocessor definitions passed using msbuild enviornment to list of PreprocessorDefinitions

### PR DESCRIPTION
**Pull request by agarwal-sandeep**
This is needed for passing preprocessors to msbuild for node build https://github.com/Microsoft/ChakraCore/commit/62fe85a08bb12244626a51456222113544c706d7

### CODE REVIEW

**Comment by agarwal-sandeep** [comment]
@dilijev please take a look

**Comment by dilijev** [comment]
So the goal here is to use this to temporarily add definitions to all invocations of CL.exe via MsBuild by the following?

```
set AdditionalPreprocessorDefinitions=DEFINED_THING=1;ANOTHER_THING=2
msbuild ...
```

and/or

```
msbuild ... "/p:AdditionalPreprocessorDefinitions=DEFINED_THING=1;ANOTHER_THING=2" ...
```

I think either would work (although if both were used I think the `/p:...` would clobber the ENV var.

**Comment by dilijev** [comment]
Besides being interested in that clarification, this LGTM.

@digitalinfinity what do you think?

**Comment by agarwal-sandeep** [comment]
The idea is to use pass AdditionalPreprocessorDefinitions in msbuild switch for diabling ES6 features.
```
msbuild ... "/p:AdditionalPreprocessorDefinitions=DEFINED_THING=1;ANOTHER_THING=2" ...
```

**Comment by dilijev** [comment]
Sounds good. LGTM

**Comment by kunalspathak** [comment]
LGTM

**Pull request merged**
