### PR TITLE
Add dump:assembly for close-to-assemblable output

### PR DESCRIPTION
**Pull request by Penguinwizzard**
We got info about a use case that may benefit significantly from closer-to-machine-assembly output, so doing -dump:assembly with these bits should provide something closer to that. Note that there's still some symopnds in the output, and it doesn't necessarily support every case, but it should be enough for simple analysis. The most complicated part of the change is adding support for what's nearly a two-column mode to Output.

Edit: changed flag to new version.

### CODE REVIEW

**Comment by LouisLaf** [comment]
I don't really like -testtrace:assemblable.  This isn't really a trace.  How about just -dump:assembly.

**Comment by dilijev** [comment]
Tried this out on a few simple cases and got assertion failures while it was iterating through and printing. I know it's just an incomplete prototype but I'm not sure it's very useful as-is without addressing some issues.

**Comment by Cellule** [comment]
> I don't really like -testtrace:assemblable. This isn't really a trace. How about just -dump:assembly.

Also, I would remove the `BEGIN_CODEGEN_PHASE` it's not really a phase as it doesn't modify the IR and that would pollute `-dump:backend`

**Comment by Penguinwizzard** [comment]
Yeah, the reason that I went with testtrace in the first place was to have the codegen phase stuff in there. I'll update to -dump and remove the codegen phase stuff in the next update.

**Comment by Penguinwizzard** [comment]
New version uses -dump:assembly as requested, handles significantly more cases, doesn't have the codegen macros, and includes a change to the runtests.py to allow for testing for asserts in flags such as this one, which would normally be hard to test due to baseline conflicts.

**Pull request merged**
