### PR TITLE
Wasm: drop and tee_local

### PR DESCRIPTION
**Pull request by commonlisp**
- implemented drop and tee_local opcodes
- drop and tee_local test case plus fixes

There may need to be some validation (TBD) for block-like ops to ensure any nested ops do not yield values except for the last.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/chakracore/1382)

### CODE REVIEW

**Comment by commonlisp** [comment]
The spec test suite has an incoming PR that patches the tests to work with the drop and tee_local semantics https://github.com/WebAssembly/spec/pull/298/.

**Comment by commonlisp** [comment]
@Cellule @MikeHolman This is an initial cut at drop and tee_local opcodes. One thing that is missing from this PR (but is in the spec PR) is type checking in block-like constructs to verify that all enclosed ops return void except for the last one, thus necessitating drop. I could put that in a follow-up PR or include it in this one, but that would break a lot more test cases.

**Comment by Cellule** [comment]
Reviewed 7 of 9 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/WasmReader/WasmByteCodeGenerator.cpp, line 489 \[r2\]](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-KORlfRLqfX2dAaP7RfS:-KORlfRLqfX2dAaP7RfT:bl1yl1u) ([raw file](https://github.com/microsoft/chakracore/blob/be0ff05738be63961b69193c687fedb8bef9f960/lib/WasmReader/WasmByteCodeGenerator.cpp#L489)):*
> ```cpp
>         break;
>     case wbSetLocal:
>         info = EmitSetLocal(false);
> ```

We must not Push `info` to the stack, it would be like saying `set_local` returns void which is incorrect. It returns nothing.
Therefor, we should do `return EmitSetLocal(false);` here

---

*[test/wasm/dropteelocal.wast, line 1 \[r2\]](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-KORm3rPWfP_fq2P2nqv:-KORm3rPWfP_fq2P2nqw:bk73zao) ([raw file](https://github.com/microsoft/chakracore/blob/be0ff05738be63961b69193c687fedb8bef9f960/test/wasm/dropteelocal.wast#L1)):*
> ```
> ;;-------------------------------------------------------------------------------------------------------
> ```

Out of curiosity, what have you used to convert this to .wasm ? Neither Sexpr-wasm nor binaryen seems to have support for tee_local/drop and I couldn't find a PR for it.

---

*[test/wasm/dropteelocal.wast, line 14 \[r2\]](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-KORlVkEfK2rvjp9md4s:-KORlVkEfK2rvjp9md4t:bq3p1d4) ([raw file](https://github.com/microsoft/chakracore/blob/be0ff05738be63961b69193c687fedb8bef9f960/test/wasm/dropteelocal.wast#L14)):*
> ```
>     (block
>       (set_local 2 (i32.mul (get_local 1) (get_local 2)))
> 	  (drop (set_local 2 (i32.const 101)))
> ```

it makes no sense to `drop` after a `set_local` as it doesn't return a value

---

*[test/wasm/dropteelocal.wast, line 16 \[r2\]](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-KORlTO2YpMr7vTElJYJ:-KORlTO3IA010YImVM30:b-jjwxmk) ([raw file](https://github.com/microsoft/chakracore/blob/be0ff05738be63961b69193c687fedb8bef9f960/test/wasm/dropteelocal.wast#L16)):*
> ```
> 	  (drop (set_local 2 (i32.const 101)))
>       (if (i32.eqz (tee_local 1 (i32.sub (get_local 1) (i32.const 1))))  
> 	      (set_local 2 (i32.const 100))
> ```

nit:  tabs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1382)*

**Comment by commonlisp** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/WasmReader/WasmByteCodeGenerator.cpp, line 489 \[r2\]](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-KORlfRLqfX2dAaP7RfS:-KOeblzkkXClubqw-CdJ:b-ep4f4e) ([raw file](https://github.com/microsoft/chakracore/blob/be0ff05738be63961b69193c687fedb8bef9f960/lib/WasmReader/WasmByteCodeGenerator.cpp#L489)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> We must not Push `info` to the stack, it would be like saying `set_local` returns void which is incorrect. It returns nothing.
> Therefor, we should do `return EmitSetLocal(false);` here
</details>
Good catch. That should be the case most of the cases now. Importantly, we also need to change EmitMemStore to not yield any values. Judging from the spec PR, that breaks a lot of test cases, so I'm holding off on doing that for the non-yielding constructs other than set_local for now. 

---

*[test/wasm/dropteelocal.wast, line 1 \[r2\]](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-KORm3rPWfP_fq2P2nqv:-KOebpgopauUuDN5aSEp:b-oqpmzn) ([raw file](https://github.com/microsoft/chakracore/blob/be0ff05738be63961b69193c687fedb8bef9f960/test/wasm/dropteelocal.wast#L1)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> Out of curiosity, what have you used to convert this to .wasm ? Neither Sexpr-wasm nor binaryen seems to have support for tee_local/drop and I couldn't find a PR for it.
</details>
sexpr-wasm produced binary with hand edits

---

*[test/wasm/dropteelocal.wast, line 14 \[r2\]](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-KORlVkEfK2rvjp9md4s:-KOecirk0r4Li_AIBvSU:b-uplktl) ([raw file](https://github.com/microsoft/chakracore/blob/be0ff05738be63961b69193c687fedb8bef9f960/test/wasm/dropteelocal.wast#L14)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> it makes no sense to `drop` after a `set_local` as it doesn't return a value
</details>
Oops, that should have been a get_local.

---

*[test/wasm/dropteelocal.wast, line 16 \[r2\]](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-KORlTO2YpMr7vTElJYJ:-KOecx_wmK6WlIppj7ZT:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/be0ff05738be63961b69193c687fedb8bef9f960/test/wasm/dropteelocal.wast#L16)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> nit:  tabs
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1382)*

**Comment by Cellule** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/WasmReader/WasmByteCodeGenerator.cpp, line 490 \[r3\]](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-KOkllJdhY_jRm79rG7N:-KOkllJdhY_jRm79rG7O:b-ge6kbf) ([raw file](https://github.com/microsoft/chakracore/blob/ce9e8402f37236192ee24305a42122aaec00475c/lib/WasmReader/WasmByteCodeGenerator.cpp#L490)):*
> ```cpp
>     case wbSetLocal:
>         return EmitSetLocal(false);
>         break;
> ```

nit: useless break

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-:-KOkm2j-RVORdakegJ8K:bg7igk9)*

**Comment by commonlisp** [comment]
done.

---

Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-:-KOounetZIqER2OTo78s:b-7rl0jd)*

**Comment by commonlisp** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/WasmReader/WasmByteCodeGenerator.cpp, line 490 \[r3\]](https://reviewable.io:443/reviews/microsoft/chakracore/1382#-KOkllJdhY_jRm79rG7N:-KOoutGzPrCtohQQkz1D:b-896fix) ([raw file](https://github.com/microsoft/chakracore/blob/ce9e8402f37236192ee24305a42122aaec00475c/lib/WasmReader/WasmByteCodeGenerator.cpp#L490)):*
<details><summary><i>Previously, Cellule (Michael Ferris) wrote…</i></summary>
> nit: useless break
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/chakracore/1382)*

**Pull request merged**
