### PR TITLE
WASM.SIMD Comparison ops for 32x4 types

### PR DESCRIPTION
**Pull request by Krovatkin**
This PR includes
* enable comparison operations + tests
* binary arithmetic operations + tests
* unary arithmetic operations + tests
* flag fix to make sure we can pass around v128 within the same wasm module

### CODE REVIEW

**Comment by Krovatkin** [comment]
@Cellule could you please take a quick look? I'm going to rebase `wasm.simd` after this change, since my remaining changes (int64x2, missing 32x4 ops) are still very prototypish :-) , so we might as well make a detour at this point and focus on separating simd.js from wasm.simd as you suggested earlier.

**Comment by Krovatkin** [comment]
fyi @arunetm

**Comment by MikeHolman** [comment]
:shipit:

**Comment by Krovatkin** [comment]
@arunetm could you please try to merge this?

**Comment by Krovatkin** [comment]
@MikeHolman @Cellule Guys, could you please help us to merge this one? Arun is still figuring out his perms issue.

**Comment by Krovatkin** [comment]
@Cellule @MikeHolman very sorry to nudge you, guys, again about this PR. Could you please merge it when you have a moment?

**Pull request merged**
