### PR TITLE
Cleanup enumerator interface

### PR DESCRIPTION
**Pull request by curtisman**
GetCurrentValue is not used. Remove.

### CODE REVIEW

**Comment by akroshg** [comment]
:shipit:

**Comment by curtisman** [comment]
@dotnetbot test arm_test

**Comment by curtisman** [comment]
@dotnetbot test Window arm_test

**Comment by curtisman** [comment]
@dotnet-bot  test Windows arm_test

**Comment by agarwal-sandeep** [comment]
LGTM

**Pull request merged**
