### PR TITLE
Fix for assertion fired in JSON.stringify.

### PR DESCRIPTION
**Pull request by akroshg**
We called the GetLength twice assuming that the length will not change. However with proxy you can give different length both time and that will causes an assert. No fre impact so just removed the assert. While testing I found that we can pass more that 2^32 and that will cause the overflow in the length. However the CompoundString cannot handle more than MaxCharLength (INT_MAX-1) and it will eventually OOM. Instead of waiting till that point I am raising the RangeError.

### CODE REVIEW

**Comment by akroshg** [comment]
Fixes #2482

**Comment by akroshg** [comment]
@suwc @kunalspathak please have a look.

**Comment by kunalspathak** [comment]
:shipit:

**Comment by dilijev** [comment]
@dotnet-bot test Ubuntu ubuntu_linux_debug please

**Comment by suwc** [comment]
:shipit:

**Pull request merged**
