### PR TITLE
Add OOP JIT check

### PR DESCRIPTION
**Pull request by pleath**
Add OOP JIT check missing from code coming from release branch.

### CODE REVIEW

**Comment by pleath** [comment]
@rajatd @MikeHolman @satheeshravi , this is the fix for the omission we were just discussing.

**Comment by MikeHolman** [comment]
lgtm

**Comment by pleath** [comment]
@dotnet-bot test Ubuntu Ubuntu_linux_debug (please!)

**Comment by pleath** [comment]
@dotnet-bot please test Ubuntu Ubuntu_linux_test_static

**Comment by pleath** [comment]
@dotnet-bot please test Ubuntu Ubuntu_linux_release

**Comment by pleath** [comment]
@dotnet-bot please test Ubuntu Ubuntu_linux_debug

**Comment by pleath** [comment]
@dotnet-bot test   Ubuntu ubuntu_linux_debug

**Pull request closed without merging**
